### PR TITLE
Do not relaunch on factory reset

### LINKED ISSUE #1652: Rancher Desktop fails to start on Linux when using Moby
### Actual Behavior

When RD is started after a factory reset, it produces a pop-up saying it is going to ask you for the root password so that it can populate `/var/run/docker.sock`. However, the pop-up where you would enter the root password never appears and an error occurs.

### Steps to Reproduce

1. Factory reset RD.
2. Select dockerd/moby when it asks.
3. Note the behaviour.

### Result

RD does not start moby successfully.

### Expected Behavior

RD should start fine, and `docker` should work fine.

### Additional Information

Note that this also occurs when RD is installed via an rpm.

Logs:
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/8134398/background.log)
[k3s.log](https://github.com/rancher-sandbox/rancher-desktop/files/8134399/k3s.log)
[lima.ha.stderr.log](https://github.com/rancher-sandbox/rancher-desktop/files/8134400/lima.ha.stderr.log)
[lima.ha.stdout.log](https://github.com/rancher-sandbox/rancher-desktop/files/8134401/lima.ha.stdout.log)
[lima.serial.log](https://github.com/rancher-sandbox/rancher-desktop/files/8134402/lima.serial.log)

first
second

### Rancher Desktop Version

f6b5b2bd

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop OS 20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by adamkpickering**
Fixes #1652.

### CODE REVIEW

File: background.ts [hunk 1]
```diff
@@ -521,7 +521,6 @@ Electron.ipcMain.on('factory-reset', async() => {
   // Remove app settings
   await settings.clear();
   // Restart
```
Comment (mook-as) [inline background.ts:523]: Should update the comment; we no longer restarting.

**Review by mook-as — CHANGES_REQUESTED** [review]
It would be good to amend the commit where `relaunch` is removed to add more details about why we're doing this in the commit message.  In particular, please mention the `NoNewPrivs` thing in some fashion, so that we have some context if we need to look into this change in the future.

**Review by mook-as — APPROVED** [review]
Note to self: this _should_ be fine with respect to updates, because doing a factory reset would wipe out any cached updates too, so it will need to download a new one on start.
