### PR TITLE
Ignore leading command-line arguments.

### LINKED ISSUE #2080: Startup error due to macOS ProcessSerialNumber
### Actual Behavior

I see this in `background.log`:
```
2022-04-22T20:55:27.495Z: Failed to update command from argument -psn_0_1692061  Error: Unexpected argument '-psn_0_1692061' in command-line [-psn_0_1692061]
    at /Users/mook/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:84096
    at /Users/mook/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:84994
```

### Steps to Reproduce

- Grab a build (I used the CI build from b4ef0e3d287a09e1a2ea540c32dccc23b2e53f20)
- Open the app
- Read `background.log`

### Result

See _Actual Behaviour_

### Expected Behavior

No errors in the logs.

### Additional Information

I believe that's a `ProcessSerialNumber` (or at least, was in the Carbon days); this gets added to processes started from Finder (/ via LaunchServices), I think.

We just need to ignore (some) unknown arguments.

### Rancher Desktop Version

main (b4ef0e3d287a09e1a2ea540c32dccc23b2e53f20)

### Rancher Desktop K8s Version

N/A

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina 10.15.7

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixed #2080  

Once we see one that we recognize, complain about any further unrecognized
arguments.

Might not be the best name for the branch, but it's temporary.

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/config/settings.ts [hunk 1]
```diff
@@ -153,24 +153,31 @@ export function getUpdatableNode(cfg: Settings, fqFieldAccessor: string): [Recor
...
-  let i = 0;
   const lim = args.length;
+  let processingExternalArguments = true;
 
-  // Not using a for-loop here because `i` gets incremented in the loop to handle cases of `--option value`
-  // ... in the belief that we don't usually expect the body of for-loops to manipulate the loop index.
-  while (i < lim) {
+  // As long as processingExternalArguments is true, ignore anything we don't recognize.
+  // Once we see something that's "ours", set processingExternalArguments to false.
+  for (let i = 0; i < lim; i++) {
```
Comment (mook-as) [inline src/config/settings.ts:161]: This still feels weird because of the `i += 1` in the `default:` case; we should at least put a warning in the comment, maybe?

File: src/config/__tests__/settings.spec.ts [hunk 2]
```diff
@@ -158,20 +158,41 @@ describe('updateFromCommandLine', () => {
...
 
-  test('should complain about an unrecognized pref', () => {
+  test('should ignore an unrecognized option', () => {
     const arg = '--kubernetes-zipperhead';
+    const newPrefs = settings.updateFromCommandLine(prefs, [arg]);
+
+    expect(newPrefs).toEqual(origPrefs);
+  });
+
+  test('should ignoreleading options and arguments', () => {
```
Comment (mook-as) [inline src/config/__tests__/settings.spec.ts:175]:
```suggestion
  test('should ignore leading options and arguments', () => {
```

**Review by mook-as — CHANGES_REQUESTED** [review]

**Review by mook-as — APPROVED** [review]
