### PR TITLE
Don't k3s-stop when k3s is disabled. And catch errors.

### LINKED ISSUE #3022: rdctl shutdown may leave RD running in broken state
# Repro

* Perform a "Factory Reset"
* Restart Rancher Desktop and disable Kubernetes in the First-Run dialog
* Wait until Rancher Desktop is fully initialized
* Run `rdctl shutdown`. It looks like it succeeds, but the app remains running.

The internal API server shuts down, but the Lima VM and the UI remain up:

```console
$ rdctl shutdown
Shutting down.

$ rdctl api settings
Error: Get "http://localhost:6107/v0/settings": dial tcp [::1]:6107: connect: connection refused

$ rdctl shell rc-service containerd status
 * status: started
```

You can terminate the UI manually using the "Quit Rancher Desktop" menu option, but even then the Lima VM remains running.

```console
$ pgrep -lf 'Rancher Desktop.app/Contents/MacOS/Rancher Desktop'
$ pgrep -lf 'Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl'
19669 /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl hostagent --pidfile /Users/jan/Library/Application Support/rancher-desktop/lima/0/ha.pid --socket /Users/jan/Library/Application Support/rancher-desktop/lima/0/ha.sock 0
```

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #3022

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/backend/lima.ts [hunk 1]
```diff
@@ -1671,7 +1671,13 @@ CREDFWD_URL='http://${ hostIPAddr }:${ stateInfo.port }'
         const status = await this.status;
 
         if (defined(status) && status.status === 'Running') {
-          await this.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+          if (this.cfg?.enabled) {
+            try {
+              await this.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
```
Comment (mook-as) [inline src/backend/lima.ts:1676]: This should probably have `expectFailure: true` in the options (which just silences things in the log, since we're logging it later anyway).

File: src/backend/lima.ts [hunk 2]
```diff
@@ -2040,10 +2046,12 @@ class LimaKubernetesBackend extends events.EventEmitter implements K8s.Kubernete
   }
 
   async stop() {
-    try {
-      await this.vm.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
-    } catch (ex) {
-      console.error('k3s stop failed: ', ex);
+    if (this.cfg?.enabled) {
+      try {
+        await this.vm.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
```
Comment (mook-as) [inline src/backend/lima.ts:2051]: Same here.

**Review by mook-as — APPROVED** [review]
