### PR TITLE
Fix nil context in WSL config dir lookup

### LINKED ISSUE #9789: The rancher desktop appimage is not working on Ubuntu 24.04 WSL
### Actual Behavior

- The rancher desktop appimage is not working on Ubuntu 24.04 WSL.
- Image

### Steps to Reproduce

- Execute the following command in the login shell of a freshly installed Ubuntu 24.04 WSL:
```bash
sudo apt update && sudo apt upgrade --assume-yes
sudo usermod -a -G kvm "$USER"

sudo tee /etc/profile.d/myenvvars.sh <<EOF
export GALLIUM_DRIVER="d3d12"
EOF
```
- In PowerShell 7 on Windows 11, execute the following command:
```powershell
wsl --terminate Ubuntu-24.04
```
- Execute the following command in the login shell of Ubuntu 24.04 WSL. The string `EA9B7CAA32DDBBF1E8DED24592231C9A366B66B4` comes from the output of `gpg --generate-key`.
```bash
gpg --generate-key
sudo apt install --assume-yes pass libnspr4 libnss3 libasound2t64
pass init EA9B7CAA32DDBBF1E8DED24592231C9A366B66B4

sudo tee --append /etc/sysctl.conf <<EOF
net.ipv4.ip_unprivileged_port_start=80
EOF

sudo sysctl --load

curl --location --output /tmp/rancher-desktop.AppImage https://download.opensuse.org/repositories/isv:/Rancher:/stable/AppImage/rancher-desktop-latest-x86_64.AppImage
chmod a+x /tmp/rancher-desktop.AppImage
/tmp/rancher-desktop.AppImage
```

### Result

- An exception is thrown at this point, and the rancher desktop GUI fails to display correctly.
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: rdctl paths failed: {"status":2,"signal":null,"output":[null,"","panic: nil Context\n\ngoroutine 1 [running]:\nos/exec.CommandContext({0x0?, 0x0?}, {0x8dca3d?, 0x5112e7?}, {0xc000187c98?, 0xc00020e1f0?, 0xc000187cd8?})\n\t/opt/hostedtoolcache/go/1.25.0/x64/src/os/exec/exec.go:480 +0xf7\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config.getLocalAppDataPath({0x0, 0x0})\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/pkg/config/config.go:146 +0x8c\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config.wslifyConfigDir({0x0, 0x0})\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/pkg/config/config.go:158 +0x27\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config.DefineGlobalFlags(0xcbc520)\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/pkg/config/config.go:61 +0x4a\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/cmd.init.14()\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/cmd/root.go:56 +0xd7\n"],"pid":1305,"stdout":"","stderr":"panic: nil Context\n\ngoroutine 1 [running]:\nos/exec.CommandContext({0x0?, 0x0?}, {0x8dca3d?, 0x5112e7?}, {0xc000187c98?, 0xc00020e1f0?, 0xc000187cd8?})\n\t/opt/hostedtoolcache/go/1.25.0/x64/src/os/exec/exec.go:480 +0xf7\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config.getLocalAppDataPath({0x0, 0x0})\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/pkg/config/config.go:146 +0x8c\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config.wslifyConfigDir({0x0, 0x0})\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/pkg/config/config.go:158 +0x27\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config.DefineGlobalFlags(0xcbc520)\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/pkg/config/config.go:61 +0x4a\ngithub.com/rancher-sandbox/rancher-desktop/src/go/rdctl/cmd.init.14()\n\t/home/runner/work/rancher-desktop/rancher-desktop/src/go/rdctl/cmd/root.go:56 +0xd7\n"}
    at file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:2:171848
    at 6416 (file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:2:172032)
    at k (file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:29:39827)
    at 8514 (file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:29:3838)
    at k (file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:29:39827)
    at 394 (file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:2:3711)
    at k (file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:29:39827)
    at file:///tmp/.mount_ranchesMDUR8/opt/rancher-desktop/resources/app.asar/dist/app/background.js:29:41715
    at ModuleJob.run (node:internal/modules/esm/module_job:343:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
Dropped Escape call with ulEscapeCode : 0x03007703
Dropped Escape call with ulEscapeCode : 0x03007703
```

### Expected Behavior

- There were no issues, and the rancher desktop GUI displayed correctly.

### Additional Information

- None.

### Rancher Desktop Version

1.22.0

### Rancher Desktop K8s Version

I haven't seen the GUI yet, and I haven't selected a Kubernetes version.

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 24.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

### Windows User Only

I don't think this has anything to do with VPNs.

### PR DESCRIPTION
**Pull request by linghengqian**
- Fixes #9789 .
- Fix nil context in WSL config dir lookup.
- Linux AppImage execution in WSL was being conflated with native Linux by rdctl’s WSL detection, raising concerns about incorrect platform identification and WSL-specific behavior in non-WSL contexts. The changes ensure rdctl only treats a Linux environment as WSL when explicit WSL signals are present.
- I'm not sure if Go has a mock library similar to Java's https://site.mockito.org/ , but the unit tests I wrote were a bit ridiculous.
- It sounds like the only way to test is manually? I've opened some external issues at https://github.com/version-fox/vfox/issues/621 .
```bash
sudo apt update && sudo apt upgrade --assume-yes

sudo tee /etc/profile.d/myenvvars.sh <<'EOF'
export GALLIUM_DRIVER="d3d12"
EOF

# In PowerShell 7, execute `wsl --terminate Ubuntu-24.04`
sudo usermod -a -G kvm "$USER"
sudo apt install --assume-yes pass libnspr4 libnss3 libasound2t64 build-essential zlib1g-dev unzip imagemagick libcairo2

tee /tmp/foo.txt <<EOF
Key-Type: DSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: Joe Tester
Name-Comment: with stupid passphrase
Name-Email: joe@foo.bar
Expire-Date: 0
Passphrase: abc
%commit
EOF

gpg --batch --generate-key /tmp/foo.txt
pass init $(gpg --list-secret-keys --with-colons "joe@foo.bar" | awk -F: '$1 == "fpr" {print $10; exit}')

sudo tee --append /etc/sysctl.conf <<EOF
net.ipv4.ip_unprivileged_port_start=80
EOF

sudo sysctl --load
echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
sudo apt update
sudo apt install --assume-yes vfox
echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
source ~/.bashrc
vfox add golang nodejs
vfox install golang@1.22.0 nodejs@22.14.0
vfox use --global golang@1.22.0
vfox use --global nodejs@22.14.0
npm uninstall -g yarn pnpm
npm install -g corepack

git clone --depth 1 -b linux-wsl-check https://github.com/linghengqian/rancher-desktop.git
cd ./rancher-desktop/
yarn install
yarn build
yarn package
./dist/linux-unpacked/rancher-desktop
```
- image

### CODE REVIEW

File: src/go/rdctl/pkg/config/config.go [hunk 1]
```diff
@@ -51,14 +51,21 @@ var (
 	configPath string
 	// DefaultConfigPath - used to differentiate not being able to find a user-specified config file from the default
 	DefaultConfigPath string
+
+	wslDistroEnvs = []string{"WSL_DISTRO_NAME", "WSL_INTEROP", "WSLENV"}
+	lstatFunc    = os.Lstat
```
Comment (jandubois) [inline src/go/rdctl/pkg/config/config.go]: Maybe add a comment that this is purely for testing?

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

File: src/go/rdctl/pkg/config/config.go (hunk 1 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config.go]: Yes, lstatFunc allows tests to inject a stub for `/bin/wslpath` checks. I also fixed the CI for gofmt in the new commit.

File: src/go/rdctl/pkg/config/config.go [hunk 2]
```diff
@@ -132,11 +140,23 @@ func GetConnectionInfo(mayBeMissing bool) (*ConnectionInfo, error) {
...
+		return false
+	}
+	if fi.Mode()&os.ModeSymlink != os.ModeSymlink {
 		return false
 	}
-	return fi.Mode()&os.ModeSymlink == os.ModeSymlink
+	return hasWSLEnvs()
+}
+
+func hasWSLEnvs() bool {
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:154]: So this returns true if _any_ of the variables are set? Might be worth a function doc comment; my initial naive assumption was if _all_ were set.

File: src/go/rdctl/pkg/config/config_test.go [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+		}
+	})
+
+	t.Run("returns false when none set", func(t *testing.T) {
+		for _, envName := range wslDistroEnvs {
+			os.Unsetenv(envName)
+		}
+		if hasWSLEnvs() {
+			t.Fatalf("expected hasWSLEnvs to be false without WSL envs")
+		}
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: We already use `github.com/stretchr/testify`; just use `assert.False(t, hasWSLEnvs(), "expected…")`

File: src/go/rdctl/pkg/config/config_test.go [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+	})
+
+	t.Run("returns true when any set", func(t *testing.T) {
+		for _, envName := range wslDistroEnvs {
+			os.Unsetenv(envName)
+		}
+		os.Setenv(wslDistroEnvs[0], "Ubuntu")
+		if !hasWSLEnvs() {
+			t.Fatalf("expected hasWSLEnvs to be true with WSL envs")
+		}
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: Same as above, use `assert.True(…)`

File: src/go/rdctl/pkg/config/config_test.go [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+
+func (info fakeFileInfo) Name() string       { return "wslpath" }
+func (info fakeFileInfo) Size() int64        { return 0 }
+func (info fakeFileInfo) Mode() os.FileMode  { return info.mode }
+func (info fakeFileInfo) ModTime() time.Time { return time.Time{} }
+func (info fakeFileInfo) IsDir() bool        { return info.mode.IsDir() }
+func (info fakeFileInfo) Sys() any           { return nil }
+
+func TestIsWSLDistro(t *testing.T) {
+	originalEnvs := map[string]string{}
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: See env save/restore comments in `TestHasWSLEnvs`

File: src/go/rdctl/pkg/config/config_test.go [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+	for _, envName := range wslDistroEnvs {
+		originalEnvs[envName] = os.Getenv(envName)
+	}
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go:30]: Three things about the environment saving (here and in `TestHasWSLEnvs`):

- Instead of calling `t.Cleanup()` in each subtest and re-defining the function, just define it once:
	```go
	restoreEnv := func() {
		for envName, value := range originalEnvs {
			…
	}
	t.Cleanup(restoreEnv)
	```
- Unset and empty are different for environment variables on *nix, so we need to store it differently:
	```go
	restoreEnv := func() {
		for _, envName := range wslDistroEnvs {
			if value, ok := originalEnvs[envName]; ok
				os.Setenv(envName, value)
			} else {
				os.Unsetenv(envName)
			}
		}
	}
	```
 - Things can get easier if we use [`T.Setenv()`](https://pkg.go.dev/testing@go1.25.6#T.Setenv) instead:
	```go
		t.Setenv(envName, "") // Store the existing state
		os.Unsetenv(envName)
	```
	This way there's no need for us to restore thing manually.  Unfortunately, there's no `t.Unsetenv()`, so we need to set it to some other value before unsetting.

File: src/go/rdctl/pkg/config/config_test.go [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+			for envName, value := range originalEnvs {
+				if value == "" {
+					os.Unsetenv(envName)
+				} else {
+					os.Setenv(envName, value)
+				}
+			}
+		})
+		originalLstat := lstatFunc
+		t.Cleanup(func() { lstatFunc = originalLstat })
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: I don't see how `originalLstat` can ever not be `os.Lstat`, but okay.

File: src/go/rdctl/pkg/config/config_test.go [hunk 8]
```diff
@@ -0,0 +1,156 @@
...
+		lstatFunc = func(_ string) (os.FileInfo, error) {
+			return fakeFileInfo{mode: os.ModeSymlink}, nil
+		}
+		if isWSLDistro() {
+			t.Fatalf("expected isWSLDistro to be false without WSL envs")
+		}
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: See below; use [`assert.False()`](https://pkg.go.dev/github.com/stretchr/testify/assert#False).

File: src/go/rdctl/pkg/config/config_test.go [hunk 9]
```diff
@@ -0,0 +1,156 @@
...
+	})
+
+	t.Run("returns true with wslpath symlink and WSL envs", func(t *testing.T) {
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: These three tests feel like they can turn data-driven:
```go
for _, symlinkMode := range []os.FileMode{os.ModeSymlink, 0} {
	symlinkText := map[os.FileMode]string{
		os.ModeSymlink: "with wslpath symlink",
		0: "without wslpath symlink",
	}[symlinkMode]
	for _, hasEnvs := range []bool{true, false} {
		envText := map[bool]string{
			true: "with WSL envs",
			false: "without WSL envs",
		}[hasEnvs]
		expected := symlinkMode != 0 && hasEnvs
		t.Run(fmt.Sprintf("returns %s %s %s", expected, symlinkText, envText"), func(t *testing.T) {
			originalLstat := lstatFunc
			t.Cleanup(func() { lstatFunc = originalLstat })
			lstatFunc = func(_ string) (os.FileInfo, error) {
				return fakeFileInfo{mode: symlinkMode}
			}
			if hasEnvs {
				t.Setenv(wslDistroEnvs[0], "pikachu")
			} else {
				for _, envName := range wslDistroEnvs {
					t.Setenv(envName, "")
					os.Unsetenv(envName)
				}
			}
			if expected {
				assert.True(t, isWSLDistro(), …)
			} else {
				assert.False(t, isWSLDistro(), …)
			}
		}
	}
}
```

File: src/go/rdctl/pkg/config/config.go (hunk 2 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config.go:154]: The comment `any env` has been added to `hasWSLEnvs()`.

File: src/go/rdctl/pkg/config/config_test.go (hunk 3 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config_test.go]: It has been replaced with `assert.False` or `assert.True`.

File: src/go/rdctl/pkg/config/config_test.go (hunk 6 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config_test.go:30]: My idea is to add `saveWSLEnvs()` to unify saving and restoring, and avoid mixing `Setenv` and `Unsetenv`.

File: src/go/rdctl/pkg/config/config_test.go (hunk 7 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config_test.go]: `originalLstat` is most likely still `os.Lstat`. I've retained the original logic (the stub still needs to be restored during testing), but I've cleaned up other redundancies.

File: src/go/rdctl/pkg/config/config_test.go (hunk 9 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config_test.go]: I have switched to a data-driven testing setup: `symlinkMode` + `hasEnvs`.

File: src/go/rdctl/pkg/config/config_test.go [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+func (info fakeFileInfo) IsDir() bool        { return info.mode.IsDir() }
+func (info fakeFileInfo) Sys() any           { return nil }
+
+func saveWSLEnvs(t *testing.T) {
+	originalEnvs := map[string]string{}
+	originalPresent := map[string]bool{}
+	for _, envName := range wslDistroEnvs {
+		if value, ok := os.LookupEnv(envName); ok {
+			originalEnvs[envName] = value
+			originalPresent[envName] = true
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config_test.go]: `originalPresent` is redundant; these are equivalent:
```go
	value := originalEnvs[envName]
	present := originalPresent[envName]
```
```go
	value, present := originalEnvs[envName]
```

**Review by mook-as — CHANGES_REQUESTED** [review]
Mostly fine now, just a small nit.

File: src/go/rdctl/pkg/config/config_test.go (hunk 10 above)
Comment (linghengqian) [reply src/go/rdctl/pkg/config/config_test.go]: I submitted another change.

**Review by linghengqian — COMMENTED** [review]
The main reason I need to write unit tests like this is because I'm unsure if I might make some mistakes while fixing them, so I'm leaving a unit test in the PR. If Go had a mock library similar to Java's https://site.mockito.org/ , defining `lstatFunc` might be unnecessary.

`WSL_DISTRO_NAME` and `WSL_INTEROP` are both located at https://github.com/microsoft/WSL/blob/master/src/linux/init/util.h . `WSLENV` is located at https://github.com/microsoft/WSL/blob/master/src/linux/init/util.cpp .

My current testing method involves writing code on the first Ubuntu 24.04 WSL instance, then initializing a second Ubuntu 24.04 WSL instance, pulling the code from GitHub, and compiling it. However, I'm unsure how to compile the appimage; I seem to only be able to compile the binary file `./dist/linux-unpacked/rancher-desktop`. The Rancher Desktop GUI is currently visible correctly on the Ubuntu 24.04 WSL instance.  Of course, I only have one copy of IntelliJ IDEA installed on Windows 11.

```bash
sudo apt update && sudo apt upgrade --assume-yes
sudo usermod -a -G kvm "$USER"
sudo apt install --assume-yes pass libnspr4 libnss3 libasound2t64
gpg --generate-key
pass init <YOUR-GPG-KEY-ID>

sudo tee /etc/profile.d/myenvvars.sh <<'EOF'
export GALLIUM_DRIVER="d3d12"
EOF

sudo tee --append /etc/sysctl.conf <<EOF
net.ipv4.ip_unprivileged_port_start=80
EOF

sudo sysctl --load
# In PowerShell 7, execute `wsl --terminate Ubuntu-24.04`
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
source ~/.bashrc
nvm install 22.14.0
npm uninstall -g yarn pnpm
npm install -g corepack

echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
sudo apt update
sudo apt install --assume-yes vfox
echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
source ~/.bashrc
vfox add golang
vfox install golang@1.22.0
vfox use --global golang@1.22.0

sudo apt install --assume-yes build-essential zlib1g-dev unzip imagemagick libcairo2
git clone -b linux-wsl-check https://github.com/linghengqian/rancher-desktop.git
cd ./rancher-desktop/
yarn install
yarn build
yarn package
./dist/linux-unpacked/rancher-desktop
```

Image

**Comment by mook-as** [comment]
Our release flow for Linux is:
- `yarn package` builds a zip file
- That gets uploaded to a S3 bucket
- https://build.opensuse.org/package/show/isv:Rancher:dev/rancher-desktop-main packages that zip file as rpm/deb/AppImage. (`isv:Rancher:stable` is the release project; `isv:Rancher:dev` is for testing, though we mostly only look at it just before a release. We have a package per version.)
- We use OBS because that also handles repositories (which makes more sense for RPM and deb).
- I assume the Flatpak will also be built there, because that has [support for it](https://openbuildservice.org/help/manuals/obs-user-guide/cha-obs-package-formats#sec-pkgfmt-flatpak).
- That does mean a (free, self-service signup) OBS account for handling that.  You'll probably want to [branch](https://openbuildservice.org/help/manuals/obs-user-guide/art-obs-bg#sec-obsbg-uc-branchprj) `isv:Rancher:dev/rancher-desktop-main` and work on it there.
- If you prefer _not_ doing that, it's also possible to edit [`appimage.yaml`](https://github.com/rancher-sandbox/rancher-desktop/blob/main/packaging/linux/appimage.yml) and build it locally with that, and then once you're happy with it make a PR for just that file.

None of the above is relevant for _this_ PR, so it's more just informational.
