### PR TITLE
Fix versioning API endpoints from the client.

### LINKED ISSUE #3965: `rdctl api -X GET /no-such-endpoint` returns list of endpoints
### Actual Behavior

Works same as `GET /`

### Steps to Reproduce

Run `rdctl api /shazbat`

### Result

```
["GET /v1","GET /v1/about","GET /v1/diagnostic_categories","GET /v1/diagnostic_checks","POST /v1/diagnostic_checks","GET /v1/diagnostic_ids","PUT /v1/factory_reset","PUT /v1/propose_settings","GET /v1/settings","PUT /v1/settings","PUT /v1/shutdown","GET /v1/transient_settings","PUT /v1/transient_settings"]
```

### Expected Behavior

HTTP 404 - No such endpoint /v1/shazbat

### Additional Information

_No response_

### Rancher Desktop Version

1.7.0 dev

### Rancher Desktop K8s Version

doesn't matter

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS doesn't matter

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #3965

* Be more careful when prepending the version string.
* Write a test that a versioned non-existent endpoint is correctly flagged.

### CODE REVIEW

File: src/go/rdctl/cmd/root.go [hunk 1]
```diff
@@ -71,7 +71,10 @@ func init() {
 
 func versionCommand(version string, command string) string {
 	if version == "" {
-		return fmt.Sprintf("%s/%s", apiVersion, command)
+		version = apiVersion
+	}
+	if strings.HasPrefix(command, "/") {
+		return fmt.Sprintf("%s%s", version, command)
 	}
 	return fmt.Sprintf("%s/%s", version, command)
```
Comment (mook-as) [inline src/go/rdctl/cmd/root.go:79]: Equivalently,
```suggestion
	return fmt.Sprintf("%s/%s", version, strings.TrimLeft(command, "/"))
```
(But it's not an important change, merging as-is is fine too.)

**Review by mook-as — APPROVED** [review]
