### PR TITLE
Simplify diagnostic checking of docker plugin symlinks

### LINKED ISSUE #3020: UI of Diagnostics broken after changing symlink
### Actual Behavior

UI components of Diagnostics tab are breaking once user corrects docker-cli symlinks pointing to a wrong directory.

### Steps to Reproduce

1. Run Rancher Desktop 
2. Change the directories that the symlinks in docker cli are pointing to in ~/.rd/bin
`ln -sf ~/.bashrc docker-buildx`
`ln -sf ~/.rd/bin/docker-compose docker-compose`
3. Click Rerun to update the diagnostics warnings
4. Correct the symlinks by pointing them to the right directory: 
`ln -sf ~/.rd/bin/docker-buildx docker-buildx`
 `ln -sf ~/.rd/bin/docker-compose docker-compose`
5. Click rerun in the Diagnostics tab to check if warnings are updated
6. Click Other UI components in this same tab such as "Show Mute" and "Mute"

### Result

UI Components of Diagnostics are totally broken. Rerun does not update the warnings, mute does not hide selected warnings and show mute does not make muted warnings visible.
Error found in steve.log:
`2022-09-26T23:49:36.071Z: stderr: time="2022-09-26T16:49:36-07:00" level=error msg="Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]"`
components breaking in diagnostics

### Expected Behavior

Rerun button should update the warnings once clicked,
Mute must hide selected warnings from the table 
Show mute must make muted warnings visible.

### Additional Information

_No response_

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

_No response_

### LINKED ISSUE #3033: cli-plugins diagnostics message is incorrect when the 2nd symlink is wrong
```console
$ ls -l ~/.docker/cli-plugins/docker-buildx
lrwxr-xr-x  1 jan  staff  32 27 Sep 11:59 /Users/jan/.docker/cli-plugins/docker-buildx -> /Users/jan/.rd/bin/docker-buildx

$ ls -l ~/.rd/bin/docker-buildx
lrwxr-xr-x  1 jan  staff  18 27 Sep 11:59 /Users/jan/.rd/bin/docker-buildx -> /Users/jan/.bashrc
```

The diagnostic says:

> The file ~/.docker/cli-plugins/docker-buildx is a symlink to ~/Dropbox/dot/bash_profile, which is not from Rancher Desktop. It should be a symlink to ~/.rd/bin/docker-buildx.

Screen Shot 2022-09-27 at 12 08 14 PM

This is wrong. The error should be along the line of

> The file ~/.rd/bin/docker-buildx is a symlink to ~/Dropbox/dot/bash_profile, which is not from Rancher Desktop. It should be a symlink into the Rancher Desktop application.

### LINKED ISSUE #3038: Handle infinite symbolic link problems (in the diagnostics/preferences server)
```
cd ~/.rd/bin
ln -sf $(PWD)/docker-compose
```

This breaks the diagnostics/preferences server

### Rancher Desktop Version

1.6.0rc1

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #3020
Fixes #3033
Fixes #3038

### CODE REVIEW

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 1]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
-            } else {
-              state = `is a symlink to ${ replaceHome(link) }, but we could not read it (${ code })`;
-            }
-          }
-        }
-      } else {
-        state = `is a symlink to ${ replaceHome(link) }`;
+      link = await this.readlink(startingPath);
+
+      console.debug(`docker-cli symlink: ${ this.name }: first-level symlink ${ startingPath }: points to: ${ link } (expect ${ rdBinPath })`);
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:56]: FWIW, from the other checks I've found that using the id is better;
```suggestion
      console.debug(`${ this.id }: first-level symlink ${ startingPath }: points to: ${ link } (expect ${ rdBinPath })`);
```

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 2]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
-    const rdBinPath = path.join(paths.integration, this.name);
     const dockerCliPluginDir = path.join(os.homedir(), '.docker', 'cli-plugins');
-    let passed = false;
+    const startingPath = path.join(dockerCliPluginDir, this.name);
+    const rdBinPath = path.join(paths.integration, this.name);
+    const finalTarget = path.join(paths.resources, os.platform(), 'bin', this.name);
+    const finalDisplayableTarget = replaceHome(finalTarget);
     let state;
+    let link = '';
+    let description = `The file ${ startingPath }`;
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:50]:
```suggestion
    let description = `The file ${ replaceHome(startingPath) }`;
```

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 3]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
-        }
-      } else {
-        state = `is a symlink to ${ replaceHome(link) }`;
+      link = await this.readlink(startingPath);
+
+      console.debug(`docker-cli symlink: ${ this.name }: first-level symlink ${ startingPath }: points to: ${ link } (expect ${ rdBinPath })`);
+
+      if (link !== rdBinPath) {
+        return {
+          description: `${ description } should be a symlink to ${ replaceHome(rdBinPath) }, but points to ${ link }.`,
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:60]:
```suggestion
          description: `${ description } should be a symlink to ${ replaceHome(rdBinPath) }, but points to ${ replaceHome(link) }.`,
```

I'm basically thinking of it like raw paths are a string that requires normalizing before emitting to the user, similar to strings that need escaping.

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 4]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
-    } catch (ex) {
+    } catch (ex: any) {
       const code = (ex as any).code ?? '';
 
-      console.debug(`docker-cli symlink: ${ this.name } got exception ${ code }: ${ ex }`);
       if (code === 'ENOENT') {
-        state = `does not exist`;
+        state = 'does not exist';
       } else if (code === 'EINVAL') {
         state = `is not a symlink`;
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:71]:
```suggestion
        state = 'is not a symlink';
```
Since we changed the other two… (Not sure why it was originally backticks in the first place.)

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 5]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
+        fixes:       [],
+      };
     }
 
-    return {
-      description,
-      passed,
-      fixes: [],
-    };
+    description = `The file ${ rdBinPath }`;
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:83]:
```suggestion
    description = `The file ${ replaceHome(rdBinPath) }`;
```

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 6]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
+    try {
+      link = await this.readlink(link);
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:85]: This assignment to itself is confusing; at least, I find `this.readlink(rdBinPath)` to be much clearer (because that's a constant value, and more specifically named).

If we do that though, it'd make sense to make `link` scoped to within the `try` for both instances instead (`const link = await this.readlink(startingPath);` and `const link = await this.readlink(rdBinPath);` — that has the advantage that in the second `catch` clause it becomes really clear that `… is a symlink to ${ replaceHome(link) }` is really referring to `rdBinPath` instead (because the assignment never happened).

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 7]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
+      if (link === finalTarget) {
+        await this.access(link, fs.constants.X_OK);
+
+        return {
+          description: `${ startingPath } is a symlink to ${ finalDisplayableTarget } through ${ replaceHome(rdBinPath) }.`,
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:90]:
```suggestion
          description: `${ replaceHome(startingPath) } is a symlink to ${ finalDisplayableTarget } through ${ replaceHome(rdBinPath) }.`,
```
For consistency, I wonder about using `replaceHome(finalTarget)` too…

File: src/main/diagnostics/dockerCliSymlinks.ts [hunk 8]
```diff
@@ -40,71 +40,85 @@ export class CheckerDockerCLISymlink implements DiagnosticsChecker {
...
+      if (code === 'ENOENT') {
+        finalDescription = `${ description } is a symlink to ${ replaceHome(link) }, which does not exist.`;
+      } else if (code === 'EINVAL') {
+        state = `is not a symlink`;
+      } else if (code === 'ELOOP') {
+        state = `is a symlink with a loop`;
+      } else if (code === 'EACCES') {
+        finalDescription = `${ description } is a symlink to ${ replaceHome(link) }, which is not executable.`;
+      } else {
+        finalDescription = `${ description } is a symlink to ${ replaceHome(link) }, but cannot be read (${ code }).`;
```
Comment (mook-as) [inline src/main/diagnostics/dockerCliSymlinks.ts:113]:
```suggestion
        finalDescription = `${ description } is a symlink to ${ replaceHome(link) }, but cannot be read (${ code || 'unknown error' }).`;
```

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/main/diagnostics/dockerCliSymlinks.ts (hunk 1 above)
Comment (ericpromislow) [reply src/main/diagnostics/dockerCliSymlinks.ts:56]: done

File: src/main/diagnostics/dockerCliSymlinks.ts (hunk 6 above)
Comment (ericpromislow) [reply src/main/diagnostics/dockerCliSymlinks.ts:85]: Good point. No need to have a mutable `link` given that we're no longer walking loops.

File: src/main/diagnostics/dockerCliSymlinks.ts (hunk 8 above)
Comment (ericpromislow) [reply src/main/diagnostics/dockerCliSymlinks.ts:113]: done

File: src/main/diagnostics/dockerCliSymlinks.ts (hunk 7 above)
Comment (ericpromislow) [reply src/main/diagnostics/dockerCliSymlinks.ts:90]: Yes, I've set it up so all displayed paths are run through `replaceHome`

File: src/main/diagnostics/dockerCliSymlinks.ts (hunk 4 above)
Comment (ericpromislow) [reply src/main/diagnostics/dockerCliSymlinks.ts:71]: Yes

File: src/main/diagnostics/dockerCliSymlinks.ts (hunk 3 above)
Comment (ericpromislow) [reply src/main/diagnostics/dockerCliSymlinks.ts:60]: yes

**Review by mook-as — APPROVED** [review]
