### PR TITLE
2951 fix zsh check

### LINKED ISSUE #2951: Diagnostics check for zsh not working correctly
Testing using https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3094433305

The diagnostics claim:

```
The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your zsh shell. 
```

But this isn't true:

```console
$ zsh -c 'echo $PATH'
/Users/jan/.rd/bin:/Users/jan/bin:[...]
```

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2951

### CODE REVIEW

File: src/main/diagnostics/rdBinInShell.ts [hunk 1]
```diff
@@ -39,12 +40,15 @@ class RDBinInShellPath implements DiagnosticsChecker {
     let description: string;
 
     try {
-      const { stdout } = await spawnFile(this.executable, this.args, { stdio: 'pipe' });
-      const dirs = stdout.trim().split(/[:\n]/);
+      const { stdout } = await spawnFile(this.executable, this.args, { stdio: ['ignore', 'pipe', 'pipe'] });
+      const outputLines = stdout.split('\n').filter(line => line.startsWith(pathOutputDelimiter));
+      const dirs = outputLines[outputLines.length - 1].substring(pathOutputDelimiter.length).split(':');
```
Comment (mook-as) [inline src/main/diagnostics/rdBinInShell.ts:45]:
```suggestion
      const dirs = outputLines.pop().substring(pathOutputDelimiter.length).split(':');
```
Unless you wanted to keep `outputLines` unchanged for some reason.

Comment (mook-as) [reply src/main/diagnostics/rdBinInShell.ts:45]: If we make `pathOutputDelimiter` end with `:`, then we can just skip the `substring` call (because the prefix will not be the correct path).

File: src/main/diagnostics/rdBinInShell.ts [hunk 2]
```diff
@@ -67,7 +72,8 @@ class RDBinInShellPath implements DiagnosticsChecker {
   }
 }
 
-const RDBinInBash = new RDBinInShellPath('RD_BIN_IN_BASH_PATH', 'bash', '-i', '-c', 'echo $PATH');
-const RDBinInZsh = new RDBinInShellPath('RD_BIN_IN_ZSH_PATH', 'zsh', '-i', '-c', 'echo $PATH');
+// Use `bash -l` because `bash -i` causes RD to suspend
+const RDBinInBash = new RDBinInShellPath('RD_BIN_IN_BASH_PATH', 'bash', '-l', '-c', `printf "\n${ pathOutputDelimiter }%s\n" "$PATH"`);
+const RDBinInZsh = new RDBinInShellPath('RD_BIN_IN_ZSH_PATH', 'zsh', '-i', '-c', `printf "\n${ pathOutputDelimiter }%s\n" "$PATH"`);
```
Comment (mook-as) [inline src/main/diagnostics/rdBinInShell.ts:77]: Would it make sense to add the `printf…` in the constructor, instead of here?

File: src/main/diagnostics/rdBinInShell.ts (hunk 1 above)
Comment (ericpromislow) [reply src/main/diagnostics/rdBinInShell.ts:49]: Both good points. Funny I was wanting ruby/python's `ARRAY[-1]` and forgot js's `pop()`.

File: src/main/diagnostics/rdBinInShell.ts (hunk 2 above)
Comment (ericpromislow) [reply src/main/diagnostics/rdBinInShell.ts:81]: Sure. If we support a shell that for whatever reason needs a different command, we can revisit this.

**Review by mook-as — CHANGES_REQUESTED** [review]
LGTM other than the logging

**Comment by ericpromislow** [comment]
I can remove the logging now, but it will get removed when issue #2977 / PR #2987 gets merged. 

We still need the logging in case zsh fails on a packaged CI build.

**Comment by jandubois** [comment]
> I can remove the logging now, but it will get removed when issue #2977 / PR #2987 gets merged.

I think that is fine

**Review by mook-as — APPROVED** [review]
QQQ :D

**Comment by ericpromislow** [comment]
Sure. Just like coloring something red with CSS :)

**Comment by ericpromislow** [comment]
Mergeable, but needs Jan's check on macos of the CI build.
