### PR TITLE
Wait for Steve to be ready before enabling dashboard button

### LINKED ISSUE #8217: Cluster Dashboard does not display when invoked before metrics server is running
With Dashboard 2.11.0.rd1 I click the "Cluster Dashboard" button as soon as it becomes available (when the API server becomes responsive).

It brings up the dashboard window with a spinner, but it never becomes ready, even long after the metrics server is started successfully. The last line in `steve.log` says:

```
2025-02-10T19:37:30.954Z: stderr: time="2025-02-10T11:37:30-08:00" level=error msg="Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]"
```

The `dashboardServer.log` has:

```
2025-02-10T19:45:14.239Z: Proxy Error: Error: connect ECONNREFUSED 127.0.0.1:9443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9443
}
2025-02-10T19:45:14.240Z: [HPM] Error occurred while proxying request 127.0.0.1:6120/v1/namespaces/cattle-ui-plugin-system/services/http:ui-plugin-operator:80/proxy/index.json to https://127.0.0.1:9443/api [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

When I close the window with the spinner, and invoke the dashboard again, it comes up immediately.

So it looks like `steve` is not accepting a connection yet, and the dashboard server is not retrying to connect; it gives up after the first error, but continues to show the spinner:

Image

### PR DESCRIPTION
**Pull request by jandubois**
The dashboard button was being enabled as soon as K8s reached the STARTED state, but Steve (which serves the dashboard API on port 9443) wasn't ready to accept connections yet. This caused the dashboard to show a spinner that never went away if clicked too quickly.

This change makes Steve.start() wait until Steve is actually accepting connections before returning, and delays sending the STARTED state to the UI until after Steve is ready.

Fixes #8217

### CODE REVIEW

File: pkg/rancher-desktop/backend/steve.ts [hunk 1]
```diff
@@ -83,16 +86,71 @@ export class Steve {
...
 
-    console.debug(`Spawned child pid: ${ this.process.pid }`);
+    await new Promise<void>((resolve, reject) => {
+      this.process.once('spawn', () => {
+        this.isRunning = true;
+        console.debug(`Spawned child pid: ${ this.process.pid }`);
+        resolve();
+      });
+      this.process.once('error', (err) => {
+        reject(new Error(`Failed to spawn Steve: ${ err.message }`));
```
Comment (mook-as) [inline pkg/rancher-desktop/backend/steve.ts]: I wish we had go's `fmt.Errorf("%w")` here… this clobbers the error stack / exit code / etc.

File: background.ts [hunk 2]
```diff
@@ -1259,18 +1259,22 @@ function newK8sManager() {
...
       if ([K8s.State.STARTED, K8s.State.DISABLED].includes(state)) {
         if (!cfg.kubernetes.version) {
           writeSettings({ kubernetes: { version: mgr.kubeBackend.version } });
         }
         currentImageProcessor?.relayNamespaces();
 
-        if (enabledK8s) {
+        if (enabledK8s && state === K8s.State.STARTED) {
+          // Wait for Steve to be ready before notifying the UI that K8s is started,
+          // so the dashboard button is only enabled when Steve can accept connections.
```
Comment (mook-as) [inline background.ts]: I don't understand this change; this actually says "only start steve after Kubernetes has finished starting".  What you comment says is actually done by moving `window.send` to below the `await Steve.getInstance().start()`.

File: pkg/rancher-desktop/backend/steve.ts [hunk 3]
```diff
@@ -83,16 +86,71 @@ export class Steve {
...
+      });
+    });
+
+    await this.waitForReady();
```
Comment (mook-as) [inline pkg/rancher-desktop/backend/steve.ts]: It would be good to update the method doc comment to say that it only returns after steve is ready.

File: pkg/rancher-desktop/backend/steve.ts
Comment (mook-as) [inline pkg/rancher-desktop/backend/steve.ts:1]: Irrelevant architecture question for later:

Why do we have [`pkg/rancher-desktop/main/dashboardServer/index.ts`](https://github.com/rancher-sandbox/rancher-desktop/blob/3dbad1e5b328235b5a55bb203a9967ca13185430/pkg/rancher-desktop/main/dashboardServer/index.ts) as well as [`pkg/rancher-desktop/backend/steve.ts`](https://github.com/rancher-sandbox/rancher-desktop/blob/3dbad1e5b328235b5a55bb203a9967ca13185430/pkg/rancher-desktop/backend/steve.ts), since they're both essentially there to manage the dashboard?

File: pkg/rancher-desktop/backend/steve.ts (hunk 1 above)
Comment (mook-as) [inline pkg/rancher-desktop/backend/steve.ts]: This function previously didn't really try to throw; does this mean the caller should try to handle exceptions now?

File: pkg/rancher-desktop/backend/steve.ts [hunk 4]
```diff
@@ -83,16 +86,71 @@ export class Steve {
...
+        throw new Error('Steve process exited before becoming ready');
+      }
+
+      if (await this.isPortReady()) {
+        console.debug(`Steve is ready after ${ attempt } attempt(s)`);
+
+        return;
+      }
+
+      await new Promise(resolve => setTimeout(resolve, delayMs));
```
Comment (mook-as) [inline pkg/rancher-desktop/backend/steve.ts]: Consider using [`util.promisify()`](https://nodejs.org/api/util.html#utilpromisifyoriginal).

**Review by mook-as — CHANGES_REQUESTED** [review]

File: pkg/rancher-desktop/backend/steve.ts (hunk 1 above)
Comment (jandubois) [reply pkg/rancher-desktop/backend/steve.ts]: Good point; I changed it to just log the error but not throw.

I think I've addressed all other feedback as well.

**Review by mook-as — APPROVED** [review]
