### PR TITLE
RDX: preload: fix listContainers

### LINKED ISSUE #4372: RDX: listContainers response doesn't match the docker API spec
The listContainers response needs to be adjusted to match the docker API spec to match what extensions expect which is as per the API spec provided here - https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerList

### PR DESCRIPTION
**Pull request by mook-as**
The API is supposed to return what the HTTP API returns, but that's subtly different from what the CLI actually returns.  Fake it by using more CLI calls.

(Duplicates #4382 because I already had a mostly-written PR…)

Fixes #4372.
Closes #4382.

### CODE REVIEW

File: pkg/rancher-desktop/preload/extensions.ts [hunk 1]
```diff
@@ -334,27 +334,73 @@ class Client implements v1.DockerDesktopClient {
...
+
+      if (inspectResults.code || inspectResults.signal) {
+        throw new Error(`failed to inspect containers: ${ inspectResults.stderr }`);
+      }
+
+      const inspectContainers = inspectResults.parseJsonLines().flat();
+
+      return lsContainers.map((c) => {
+        const details = inspectContainers.find(i => i.Id.startsWith(c.ID));
+        const pick = (object: any, ...prop: (string | [string, string])[]) => {
```
Comment (mook-as) [inline pkg/rancher-desktop/preload/extensions.ts:379]: We're making our own `pick` here because we can't pull in any NodeJS packages (e.g. lodash) from the preload context; it breaks loading the script.

**Review by jandubois — APPROVED** [review]
Thanks, LGTM. Fixes Log Explorer.
