### PR TITLE
K8s: Fix port display in UI

### LINKED ISSUE #459: UI out of sync w.r.t port
Every time I change versions, the UI puts up a notification that there's a request to change the port from 0 to 6443, and therefore k8s needs to be reset.

### PR DESCRIPTION
**Pull request by mook-as**
- Make the port number available explicitly be the _desired_ port, and not the current port; that is, it will reflect the target port number while the backend is still starting.
- Make the k8s page request the desired port when mounting.

Fixes #459

### CODE REVIEW

File: background.ts [hunk 1]
```diff
@@ -270,7 +270,11 @@ Electron.ipcMain.on('k8s-state', (event) => {
   event.returnValue = k8smanager.state;
 });
 
-Electron.ipcMain.handle('current-port', event => k8smanager.port);
+Electron.ipcMain.on('k8s-current-port', () => {
+  console.log(`k8s-current-port: ${ k8smanager.desiredPort }`);
```
Comment (ericpromislow) [inline background.ts:274]: Do you want this line in here permanently?

**Review by ericpromislow — APPROVED** [review]
LGTM
