### PR TITLE
Wipe Kubeneretes data on downgrade

### LINKED ISSUE #508: Failing to switch version to older version
When I tried to switch from 1.21.3 to 1.17.7 on MacOS the system went into a failed state.

The lima.log contained...

```
Checking port: {"current":6443,"config":6443}
K3s exited gracefully.
time="2021-08-16T11:51:13-04:00" level=info msg="Using the existing instance \"rancher-desktop\""
time="2021-08-16T11:51:13-04:00" level=info msg="The instance \"rancher-desktop\" is already running. Run `limactl shell rancher-desktop` to open the shell."
Could not read k3s.yaml; retrying...
Could not read k3s.yaml; retrying...
/etc/rancher/k3s/k3s.yaml is ready.
K3s exited with status 255 signal null
time="2021-08-16T11:51:37-04:00" level=info msg="Sending SIGINT to hostagent process 64323"
time="2021-08-16T11:51:37-04:00" level=info msg="Waiting for the host agent and the qemu processes to shut down"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Received SIGINT, shutting down the host agent"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Shutting down the host agent"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Unmounting \"/Users/mfarina/Library/Caches/rancher-desktop/k3s\""
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Shutting down QEMU with ACPI"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Stopping forwarding TCP from 127.0.0.1:6444 to 127.0.0.1:6444"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Sending QMP system_powerdown command"
time="2021-08-16T11:51:37-04:00" level=warning msg="[hostagent] failed to stop forwarding TCP port 6444"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Stopping forwarding TCP from [::]:6443 to 127.0.0.1:6443"
time="2021-08-16T11:51:37-04:00" level=warning msg="[hostagent] failed to stop forwarding TCP port 6443"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Stopping forwarding TCP from [::]:10252 to 127.0.0.1:10252"
time="2021-08-16T11:51:37-04:00" level=warning msg="[hostagent] failed to stop forwarding TCP port 10252"
time="2021-08-16T11:51:37-04:00" level=info msg="[hostagent] Stopping forwarding TCP from 127.0.0.1:10010 to 127.0.0.1:10010"
time="2021-08-16T11:51:37-04:00" level=warning msg="[hostagent] failed to stop forwarding TCP port 10010"
time="2021-08-16T11:51:38-04:00" level=info msg="[hostagent] Stopping forwarding TCP from [::]:10251 to 127.0.0.1:10251"
time="2021-08-16T11:51:38-04:00" level=warning msg="[hostagent] failed to stop forwarding TCP port 10251"
time="2021-08-16T11:51:38-04:00" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedly"
time="2021-08-16T11:51:45-04:00" level=info msg="[hostagent] QEMU has exited"
```

The k3s.log file contained...

```
E0816 15:51:34.896849   12199 authentication.go:104] Unable to authenticate the request due to an error: invalid bearer token
E0816 15:51:34.901285   12199 authentication.go:104] Unable to authenticate the request due to an error: invalid bearer token
E0816 15:51:34.912197   12199 authentication.go:104] Unable to authenticate the request due to an error: invalid bearer token
E0816 15:51:35.211721   12199 authentication.go:104] Unable to authenticate the request due to an error: invalid bearer token
time="2021-08-16T15:51:35.716771848Z" level=info msg="Connecting to proxy" url="wss://192.168.5.15:6443/v1-k3s/connect"
time="2021-08-16T15:51:35.718227905Z" level=info msg="Handling backend connection request [lima-rancher-desktop]"
time="2021-08-16T15:51:35.721145935Z" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/var/lib/rancher/k3s/data/4b08ff55a6cec1960f6f97519da0ac5351986d629107a1ef4a1e216ff5579bf0/bin --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --container-runtime-endpoint=/run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=lima-rancher-desktop --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-labels= --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
I0816 15:51:35.721639   12199 server.go:412] Version: v1.17.7+k3s1
I0816 15:51:35.724500   12199 flannel.go:92] Determining IP address of default interface
I0816 15:51:35.724882   12199 flannel.go:105] Using interface with name eth0 and address 192.168.5.15
E0816 15:51:35.725563   12199 info.go:102] Failed to get system UUID: open /etc/machine-id: no such file or directory
W0816 15:51:35.725634   12199 info.go:51] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0816 15:51:35.725923   12199 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I0816 15:51:35.726288   12199 container_manager_linux.go:271] container manager verified user specified cgroup-root exists: []
I0816 15:51:35.726399   12199 container_manager_linux.go:276] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
I0816 15:51:35.726566   12199 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
I0816 15:51:35.726589   12199 container_manager_linux.go:311] Creating device plugin manager: true
I0816 15:51:35.726686   12199 fake_topology_manager.go:39] [fake topologymanager] AddHintProvider HintProvider:  &{kubelet.sock /var/lib/kubelet/device-plugins/ map[] {0 0} <nil> {{} [0 0 0]} 0x2c8a160 0x6e18af0 0x2c8aa30 map[] map[] map[] map[] map[] 0xc00f0bebd0 [] 0x6e18af0}
I0816 15:51:35.726784   12199 state_mem.go:36] [cpumanager] initializing new in-memory state store
E0816 15:51:35.726896   12199 container_manager_linux.go:335] failed to initialize cpu manager: could not initialize checkpoint manager: could not restore state from checkpoint: checkpoint is corrupted
Please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet.
F0816 15:51:35.727017   12199 server.go:269] failed to run Kubelet: could not initialize checkpoint manager: could not restore state from checkpoint: checkpoint is corrupted
Please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet.
time="2021-08-16T15:51:35.747455802Z" level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --healthz-bind-address=127.0.0.1 --hostname-override=lima-rancher-desktop --kubeconfig=/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig --proxy-mode=iptables"
W0816 15:51:35.747876   12199 server.go:213] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
exit status 255
```

When I restart RD so it should come back up in 1.17 it doesn't work and the k3s.log as the following...

```
I0816 16:01:01.307415    2588 state_mem.go:36] [cpumanager] initializing new in-memory state store
E0816 16:01:01.308390    2588 container_manager_linux.go:335] failed to initialize cpu manager: could not initialize checkpoint manager: could not restore state from checkpoint: checkpoint is corrupted
Please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet.
F0816 16:01:01.308401    2588 server.go:269] failed to run Kubelet: could not initialize checkpoint manager: could not restore state from checkpoint: checkpoint is corrupted
Please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet.
exit status 255
```

### PR DESCRIPTION
**Pull request by mook-as**
This wipes (selected) Kubernetes data on downgrade, but keeping `/var/lib/rancher/k3s/agent/containerd` so that the images are not removed.

Fixes #508.

### CODE REVIEW

File: src/k8s-engine/k3sHelper.ts [hunk 1]
```diff
@@ -611,4 +611,23 @@ export default class K3sHelper extends events.EventEmitter {
...
+   * Delete state related to Kubernetes.  This will ensure that images are not
+   * deleted.
+   * @param execAsRoot A function to run commands on the VM as root.
+   */
+  async deleteKubeState(execAsRoot: (...args: string[]) => Promise<void>) {
+    const directories = [
+      '/var/lib/kubelet', // https://github.com/kubernetes/kubernetes/pull/86689
+      // We need to keep /var/lib/rancher/k3s/agent/containerd for the images.
+      '/var/lib/rancher/k3s/data',
+      '/var/lib/rancher/k3s/server',
```
Comment (jandubois) [inline src/k8s-engine/k3sHelper.ts:625]: Should we delete `/var/lib/rancher/k3s/storage` as well? I believe this is the location used for PVC storage provided by our local-path-provisioner. I don't think the data can be recovered since the PVCs themselves are gone when you wipe the object store.

Please verify the path though; this is from memory.

Comment (mook-as) [reply src/k8s-engine/k3sHelper.ts:625]: Yes, we should; it wasn't included because I checked against a freshly deployed VM, which didn't have that directory because there were no PVCs…

Comment (mook-as) [reply src/k8s-engine/k3sHelper.ts:625]: Fixed in fc12446c30dc2ad165510ffa090eea3a119ca6b0 — checked the path after deploying wordpress (which uses PVCs) to the cluster.

**Comment by mattfarina** [comment]
I've not tracked down all the issues but I've found some doing QA style testing. I'll look for the reasons later. Wanted to pass this on right away.

Upgrading and downgrading on mac isn't working. When upgrading I get log messages in my k3s.log like...

```
I0817 00:25:02.578230    2628 state_mem.go:36] [cpumanager] initializing new in-memory state store
E0817 00:25:02.587988    2628 container_manager_linux.go:335] failed to initialize cpu manager: could not initialize checkpoint manager: could not restore state from checkpoint: checkpoint is corrupted
Please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet.
F0817 00:25:02.588093    2628 server.go:269] failed to run Kubelet: could not initialize checkpoint manager: could not restore state from checkpoint: checkpoint is corrupted
Please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet.
time="2021-08-17T00:25:02.732243531Z" level=info msg="labels have been set successfully on node: lima-rancher-desktop"
exit status 255
```

This happened when I went from 1.17 to 1.21. When I went from 1.21 to 1.17 the lima.log file says...

```
time="2021-08-16T20:31:26-04:00" level=info msg="READY. Run `limactl shell rancher-desktop` to open the shell."
sudo: r: command not found
exit status 1
sudo: r: command not found
exit status 1
sudo: r: command not found
exit status 1
sudo: r: command not found
exit status 1
sudo: r: command not found
exit status 1
Error starting lima: Error: /Users/mfarina/code/rancher-sandbox/rd/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Users/mfarina/code/rancher-sandbox/rd/dist/app/background.js:33537:27)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
sudo: r: command not found
exit status 1
```

This is just after the k8s.log file had...

```
Attempting to remove K3s state: /etc/rancher/k3s /run/k3s /var/lib/kubelet /var/lib/rancher/k3s/data /var/lib/rancher/k3s/server /var/lib/rancher/k3s/storage
```

The failed sudo r commands are the rm commands for the directories.

**Comment by mattfarina** [comment]
On windows things are failing, as well. In this case the logs say...

```
Cross-device error trying to rename a file: rename C:\Users\Matt\AppData\Local\Temp\kuberlr-kubectl-891226303 C:\Users\Matt\.kuberlr\windows-amd64\kubectl1.17.17.exe: The process cannot access the file because it is being used by another process. -- will do a full copy
F0816 20:37:52.143752   14380 main.go:69] rename C:\Users\Matt\AppData\Local\Temp\kuberlr-kubectl-891226303 C:\Users\Matt\.kuberlr\windows-amd64\kubectl1.17.17.exe: The process cannot access the file because it is being used by another process.
```

k8s starts up but an alert shows up because of the error and the state icon for RD is red. K8s does work, though.

**Review by mattfarina — CHANGES_REQUESTED** [review]
Found the mac issue. The windows issue is inside kuberlr and will handle it over there.

File: src/k8s-engine/lima.ts [hunk 2]
```diff
@@ -439,9 +446,50 @@ export default class LimaBackend extends events.EventEmitter implements K8s.Kube
...
+  protected async installTrivy() {
+    await this.lima('copy', resources.get('linux', 'bin', 'trivy'), `${ MACHINE_NAME }:./trivy`);
+    await this.lima('copy', resources.get('templates', 'trivy.tpl'), `${ MACHINE_NAME }:./trivy.tpl`);
+    await this.ssh( 'sudo', 'mv', './trivy', '/usr/local/bin/trivy');
+    await this.ssh( 'sudo', 'mv', './trivy.tpl', '/var/lib/trivy.tpl');
+  }
+
+  protected async deleteIncompatibleData(isDowngrade: boolean) {
+    if (isDowngrade) {
+      await this.k3sHelper.deleteKubeState(args => this.ssh('sudo', ...args));
```
[the remark this answers is not in the document]
Comment (mook-as) [reply src/k8s-engine/lima.ts]: Sorry about that, the issue was added when I refactored things when I implemented it for Windows… and forgot to double-check on mac. Fixed in 825eb4f2d277d0c6fecb107d0960ce436ae808ec

**Review by mattfarina — APPROVED** [review]
tested. it works.
