### PR TITLE
Windows: fix issues with containerd picking up ports after containerd restart

### LINKED ISSUE #8566: registry/creds BATS test fails on Windows when bug workaround is removed
The test claims that the workarounds can be removed once #7146 is fixed: https://github.com/rancher-sandbox/rancher-desktop/blob/e26380c75482780313b698e7c52c7ddcef1dabf1/bats/tests/registry/creds.bats#L178-L179

The issue is fixed, but commenting out the workaround make the test fail:

```
 ✓ factory reset [4098]
   Install location:             system
   Resources path:               /mnt/c/Program Files/Rancher Desktop/resources/resources

   Container engine:             containerd
   Kubernetes version:           1.29.6 (1.29.6)
   Mount type:
   Using image allow list:       false
   Using Windows executables:    true
   Using networking tunnel:      true

   Capturing logs:               false
   Tracing execution:            true
   Taking screenshots:           false
   Using ghcr.io images:         false
 ✓ start container engine [46517]
   (2025-04-25T18:41:11Z: launch_the_application): --application.debug --application.updater.enabled=false --kubernetes.enabled=false --container-engine.name=containerd
   (2025-04-25T18:41:55Z: try): 8/48 tries: rdctl shell grep ID= /etc/os-release
 ✓ wait for container engine [1582]
   (2025-04-25T18:41:58Z: wait_for_container_engine): waiting for api /settings to be callable
   (2025-04-25T18:41:58Z: wait_for_container_engine): 0/30 tries: rdctl api /settings
   (2025-04-25T18:41:58Z: wait_for_container_engine): waiting for VM to be available
   (2025-04-25T18:41:59Z: wait_for_container_engine): 0/48 tries: rdctl shell grep ID= /etc/os-release
   (2025-04-25T18:41:59Z: wait_for_container_engine): waiting for buildkitd to be started
   (2025-04-25T18:41:59Z: wait_for_container_engine): 0/30 tries: assert_service_status buildkitd started
   (2025-04-25T18:41:59Z: wait_for_container_engine): waiting for container engine info to be available
   (2025-04-25T18:41:59Z: wait_for_container_engine): 0/12 tries: get_container_engine_info
 ✓ verify credential is set correctly [479]
 ✓ verify allowed-images config [4963]
 ✓ create server certs for registry [5808]
 ✓ pull registry image [8103]
 ✓ create plain registry [1738]
   (2025-04-25T18:42:30Z: try): 0/20 tries: curl -k --silent --show-error https://localhost:5050/v2/_catalog
 ✓ tag image with registry [636]
 ✓ expect push image to registry to fail because CA cert has not been installed [853]
 ✓ install CA cert [1008]
   restart container engine to refresh certs                                               12/19 in 105 sec
 ✗ restart container engine to refresh certs [145907]
   (2025-04-25T18:42:41Z: wait_for_container_engine): 0/30 tries: rdctl api /settings
   (2025-04-25T18:42:41Z: wait_for_container_engine): waiting for VM to be available
   (2025-04-25T18:42:41Z: wait_for_container_engine): 0/48 tries: rdctl shell grep ID= /etc/os-release
   (2025-04-25T18:42:41Z: wait_for_container_engine): waiting for buildkitd to be started
   (2025-04-25T18:42:42Z: wait_for_container_engine): 0/30 tries: assert_service_status buildkitd started
   (2025-04-25T18:42:42Z: wait_for_container_engine): waiting for container engine info to be available
   (2025-04-25T18:42:42Z: wait_for_container_engine): 0/12 tries: get_container_engine_info
   (2025-04-25T18:45:05Z: try): 20/20 tries: curl -k --silent --show-error https://localhost:5050/v2/_catalog
   (from function `try' in file tests/helpers/utils.bash, line 291,
    from function `wait_for_registry' in file tests/registry/creds.bats, line 72,
    in test file tests/registry/creds.bats, line 197)
     `wait_for_registry' failed with status 7
    * Stopping Container Daemon ... [ ok ]
    * Starting Container Daemon ... [ ok ]
   {
     "version": 14,
     "WSL": {
       "integrations": {
         "Ubuntu-24.04": true
       }
     },
     "containerEngine": {
       "allowedImages": {
         "enabled": false,
         "patterns": [
           "docker.io"
         ]
       },
       "name": "containerd"
     },
     "experimental": {
       "virtualMachine": {
         "type": "qemu",
         "useRosetta": false,
         "mount": {
           "type": "reverse-sshfs",
           "9p": {
             "securityModel": "none",
             "protocolVersion": "9p2000.L",
             "msizeInKib": 128,
             "cacheMode": "mmap"
           }
         },
         "proxy": {
           "enabled": false,
           "address": "",
           "password": "",
           "port": 3128,
           "username": "",
           "noproxy": [
             "0.0.0.0/8",
             "10.0.0.0/8",
             "127.0.0.0/8",
             "169.254.0.0/16",
             "172.16.0.0/12",
             "192.168.0.0/16",
             "224.0.0.0/4",
             "240.0.0.0/4"
           ]
         }
       },
       "containerEngine": {
         "webAssembly": {
           "enabled": false
         }
       },
       "kubernetes": {
         "options": {
           "spinkube": false
         }
       }
     },
     "application": {
       "adminAccess": false,
       "debug": true,
       "extensions": {
         "allowed": {
           "enabled": false,
           "list": []
         },
         "installed": {}
       },
       "pathManagementStrategy": "manual",
       "telemetry": {
         "enabled": true
       },
       "updater": {
         "enabled": false
       },
       "autoStart": false,
       "startInBackground": false,
       "hideNotificationIcon": false,
       "window": {
         "quitOnClose": false
       }
     },
     "virtualMachine": {
       "memoryInGB": 2,
       "numberCPUs": 2
     },
     "kubernetes": {
       "version": "",
       "port": 6443,
       "enabled": false,
       "options": {
         "traefik": true,
         "flannel": true
       },
       "ingress": {
         "localhostOnly": false
       }
     },
     "portForwarding": {
       "includeKubernetesServices": false
     },
     "images": {
       "showAll": true,
       "namespace": "default"
     },
     "containers": {
       "showAll": true,
       "namespace": "default"
     },
     "diagnostics": {
       "showMuted": false,
       "mutedChecks": {}
     }
   }
   ID="rancher-desktop-wsl-distro"
   VERSION_ID="0.81"
   BUILD_ID="cf320071e328046040b411fd394c01835b240342"

   WARNING: No swap limit support
   Client:
    Namespace:  default
    Debug Mode: false

   Server:
    Server Version: v2.0.0
    Storage Driver: overlayfs
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Cgroup Version: 2
    Plugins:
     Log:     fluentd journald json-file none syslog
     Storage: native overlayfs
    Security Options:
     seccomp
      Profile: builtin
     cgroupns
    Kernel Version:   6.6.75.1-microsoft-standard-WSL2
    Operating System: Rancher Desktop WSL Distribution
    OSType:           linux
    Architecture:     x86_64
    CPUs:             8
    Total Memory:     39.15GiB
    Name:             rd-w11-test-1
    ID:               352399c3-b876-4611-8ff0-315c61b5c578

   curl: (7) Failed to connect to localhost port 5050 after 2249 ms: Could not connect to server
 ✗ expect push image to registry to succeed now [761]
   (from function `nerdctl' in file tests/helpers/commands.bash, line 69,
    from function `ctrctl' in file tests/helpers/commands.bash, line 42,
    in test file tests/registry/creds.bats, line 201)
     `ctrctl push "$REGISTRY/registry"' failed
   time="2025-04-25T11:45:07-07:00" level=info msg="pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.list.v2+json, sha256:9e5c9974419a9829ac217c4c1b96457c99a5bbe4077fbd9b4f9b9b04d6a024a4)"
   time="2025-04-25T11:45:07-07:00" level=fatal msg="failed to do request: Head \"https://registry.192.168.143.1.sslip.io:5050/v2/registry/blobs/sha256:fe88d67f473ca63bdce57cf03a3e2ed2e201809c472970040b018f538a841789\": EOF"
   index-sha256:9e5c9974419a9829ac217c4c1b96457c99a5bbe4077fbd9b4f9b9b04d6a024a4:    waiting        |--------------------------------------|
   manifest-sha256:85d4cd48754d4e8e4d4fe933bbde017d969e0e20775507add9faca39064bf9b0: waiting        |--------------------------------------|
   layer-sha256:32a19664cea732d19655fe73f24b0b3c22ddf2b51bb3fbb005ba651fb1febbcf:    waiting        |--------------------------------------|
   layer-sha256:55f7fac5d815c6d815af9cd4a55d79c15f938c8b4dfbec0699b4155800cba752:    waiting        |--------------------------------------|
   layer-sha256:58116d8bf56953e5f30b7f50257c5bb2b5ba4aba460cb69f2ac57eea00aaa5dc:    waiting        |--------------------------------------|
   layer-sha256:8a49fdb3b6a5ff2bd8ec6a86c05b2922a0f7454579ecc07637e94dfd1d0639b6:    waiting        |--------------------------------------|
   layer-sha256:fe88d67f473ca63bdce57cf03a3e2ed2e201809c472970040b018f538a841789:    waiting        |--------------------------------------|
   config-sha256:f5352b75f67e2e2df2bf2d96509248d1f618b8aa66d8b8c89d21e29111424881:   waiting        |--------------------------------------|
   elapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)
   create registry with basic auth                                                         14/19 in 255 sec
 ✗ create registry with basic auth [144984]
g
   (from function `try' in file tests/helpers/utils.bash, line 291,
    from function `wait_for_registry' in file tests/registry/creds.bats, line 72,
    from function `create_registry' in file tests/registry/creds.bats, line 67,
    in test file tests/registry/creds.bats, line 212)
     `-v "$(host_path "$AUTH_DIR"):/auth" \' failed with status 7
   74b723d43f69d6875ee537ee71afe96f506917f779d6af9bc21a856e673a0cd9

   curl: (7) Failed to connect to localhost port 5050 after 2243 ms: Could not connect to server
 ✓ verify that registry requires basic auth [1015]
 ✓ verify that pushing fails when not logged in [3123]
 ✓ verify that pushing succeeds after logging in [1634]
 ✓ verify credentials in host cred store [930]
 ✓ verify the docker-desktop credential helper is replaced with the rancher-desktop default [47794]
   (2025-04-25T18:47:52Z: launch_the_application): --application.debug --application.updater.enabled=false --kubernetes.enabled=false --container-engine.name=containerd
   (2025-04-25T18:47:52Z: wait_for_container_engine): waiting for api /settings to be callable
   (2025-04-25T18:47:58Z: wait_for_container_engine): 1/30 tries: rdctl api /settings
   (2025-04-25T18:47:58Z: wait_for_container_engine): waiting for VM to be available
   (2025-04-25T18:48:30Z: wait_for_container_engine): 6/48 tries: rdctl shell grep ID= /etc/os-release
   (2025-04-25T18:48:31Z: wait_for_container_engine): waiting for buildkitd to be started
   (2025-04-25T18:48:36Z: wait_for_container_engine): 1/30 tries: assert_service_status buildkitd started
   (2025-04-25T18:48:36Z: wait_for_container_engine): waiting for container engine info to be available
   (2025-04-25T18:48:37Z: wait_for_container_engine): 0/12 tries: get_container_engine_info

19 tests, 3 failures in 469 seconds
```

### PR DESCRIPTION
**Pull request by mook-as**
This contains two separate fixes to fix #8566 where we fail to forward ports correctly after containerd restarts.  Note that this is a draft as it is based on #9056 and will need to be rebased after that merges.

### CODE REVIEW

File: src/go/guestagent/pkg/containerd/events_linux.go [hunk 1]
```diff
@@ -410,21 +411,29 @@ func createLoopbackIPtablesRules(ctx context.Context, networks []string, contain
...
+func createPortMappingFromContainer(id string, labels map[string]string) (nat.PortMap, error) {
+	var data struct {
+		PortMappings []Port `json:"portMappings"`
+	}
 	portMap := make(nat.PortMap)
 
-	if portMapping == "" {
+	if portString := labels[portsKey]; portString != "" {
+		if err := json.Unmarshal([]byte(portString), &data.PortMappings); err != nil {
+			return nil, err
```
Comment (Nino-K) [inline src/go/guestagent/pkg/containerd/events_linux.go]: If unmarshaling fails, it currently just returns nil. We could improve this by attempting to read from the stateDir as a fallback to look up port mappings. The following approach might be more robust:

1) Attempt to retrieve portMappings from the label.
2) If they don’t exist or an error occurs, try reading from the stateDir.
3) If that also fails, return nil along with the error.
