### PR TITLE
Convert backslashes in paths to forward slashes.

### LINKED ISSUE #5232: `yarn test:e2e e2e/FILE ...` is broken on Windows
### Actual Behavior

When I run `yarn test:e2e`, it runs the tests, but when I specify one or more files it starts running, but then shuts down saying 'Error: No tests found`

### Steps to Reproduce

```
yarn test:e2e .\e2e\main.e2e.spec.ts
```

(or any number of command-line files > 0

### Rancher Desktop Version

1.9.1dev

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5232

Otherwise playwright fails to convert them to URIs.

### CODE REVIEW

**Review by rak-phillip — APPROVED** [review]
LGTM after some quick testing

File: scripts/e2e.ts [hunk 1]
```diff
@@ -56,7 +56,10 @@ class E2ETestRunner extends events.EventEmitter {
 
   #testProcess: null | childProcess.ChildProcess = null;
   startTestProcess(): Promise<void> {
-    const args = process.argv.slice(2).filter(x => x !== '--serial');
+    const args = process.argv.slice(2).filter(x => x !== '--serial').map((s) => {
+      return s[0] === '-' ? s : s.replace(/\\/g, '/');
+    });
```
Comment (jandubois) [inline scripts/e2e.ts:61]: Can you add a comment on why the replacement is necessary? And why "option arguments" are excluded from the transformation? What happens if an argument is `--file=e2e\foobar.baz`?

Comment (ericpromislow) [reply scripts/e2e.ts]: This doesn't have to be a general solution, only one that handles the possible arguments that are used to run e2e tests. Which as far as I can tell are an optional list of filenames. But I'm leaving the `-*` alone because those arguments are intended for playwright internally.

From `node ./node_modules/@playwright/test/cli.js test --help` this could be an issue for `--config|-c FILE` or `--output DIR` but that's easily handled by using `/` or `\\` on the command-line. And it's not a typical use case for us.

**Review by jandubois — APPROVED** [review]
Thanks, LGTM
