### PR TITLE
Prevent AppImage version of RD from deleting conflicting filesystem nodes in integrations directory at exit

### LINKED ISSUE #848: [AppImage] When exiting the application links in ~/.local/bin are removed even when managed by another app
**For bugs, describe what you're seeing**
Let's say I have a symlink to helm in ~/.local/bin that isn't managed by RD via the AppImage. When I exit Rancher Desktop, this symlink is deleted along with kubectl, helm, kim, and nerdctl. It shouldn't be.

Note, we aren't currently shipping an AppImage. This is experimental.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get or build an AppImage for Rancher Desktop
2. For one of the tools that we include linking support for (i.e., kubectl, helm, kim, nerdctl) create a link to something not related to Rancher Desktop.
3. Start and then exit RD.
4. See that the symlink is gone.

**Expected behaviour**
Symlinks should only be deleted if RD created it.

**Setup (please complete the following information):**
 - OS: Linux
 - Rancher Desktop version: main
 - Kubernetes version: N/A

### PR DESCRIPTION
**Pull request by adamkpickering**
Fixes #848.

### CODE REVIEW

File: background.ts [hunk 1]
```diff
@@ -576,46 +577,64 @@ async function getVersion() {
...
+    throw error;
+  }
 
-    if (err) {
-      console.error(`Error unlinking symlink for ${ linkPath }: ${ err.message }`);
+  const mountPath = process.env['APPDIR'];
 
-      return err;
+  if (mountPath) {
+    if (linkedTo.includes(mountPath)) {
```
Comment (jandubois) [inline background.ts:632]: Shouldn't this be `startsWith` instead of `includes`? And maybe make sure that `mountPath` has a trailing slash?

Comment (adamkpickering) [reply background.ts:632]: I agree, `startsWith` would be better - I'll make that change.

As for the trailing slash, I'm not sure what checking for it will get us. What is your rationale here?

Comment (jandubois) [reply background.ts]: If `mountPath` is `/tmp` and `linkedTo` is `/tmpdir/file`, then `linkedTo.startsWith(mountPath)` will return `true` even though that is wrong.

If `mountPath` is `/tmp/` then `linkedTo.startsWith(mountPath)` properly returns `false`.

Now, I agree that this probably cannot happen here, but I think it is good practice to make code handle edge cases correctly, even when they currently can't happen.

File: background.ts [hunk 2]
```diff
@@ -576,46 +577,66 @@ async function getVersion() {
...
     }
+    throw error;
+  }
+
+  if (linkedTo.startsWith(mountPath)) {
+    return true;
   }
 
-  return null;
+  return false;
```
Comment (jandubois) [inline background.ts:639]: This could be just

```
    return linktedTo.StartWith(mountPath);
```

But I'm fine with leaving it as-is unless you have other changes to apply.

**Review by jandubois — COMMENTED** [review]
Looks fine to me now; but I'll leave final approval to the TypeScript people. 😄

File: background.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import fs from 'fs';
+import fsPromises from 'fs/promises';
```
Comment (mook-as) [inline background.ts:2]: This is actually accessible via `fs.promises.*` as well.

File: background.ts [hunk 4]
```diff
@@ -576,46 +577,62 @@ async function getVersion() {
...
+  if (desiredPresent) {
+    try {
+      await fsPromises.symlink(resources.executable(name), linkPath);
+    } catch (error: any) {
+      console.warn(`Failed to create symlink ${ linkPath }: ${ error.message }`);
+    }
+  } else if (await isManagedIntegration(linkPath)) {
+    try {
+      await fsPromises.unlink(linkPath);
+    } catch (error: any) {
```
Comment (mook-as) [inline background.ts:602]: We should check if this is `ENOENT` and do nothing.

File: background.ts [hunk 5]
```diff
@@ -576,46 +577,62 @@ async function getVersion() {
...
+  } catch (error: any) {
+    console.error(`Error creating integrations directory ${ paths.integration }: ${ error.message }`);
+  }
 
-    return err;
+  if (desiredPresent) {
+    try {
+      await fsPromises.symlink(resources.executable(name), linkPath);
+    } catch (error: any) {
+      console.warn(`Failed to create symlink ${ linkPath }: ${ error.message }`);
```
Comment (mook-as) [inline background.ts:597]: This used to also returns the error (so the caller can deal with it as necessary); do we no longer want that?

File: background.ts [hunk 6]
```diff
@@ -576,46 +577,62 @@ async function getVersion() {
...
   }
+}
 
-  if (state) {
-    err = await new Promise((resolve) => {
-      fs.symlink(resources.executable(name), linkPath, 'file', resolve);
-    });
+/**
+ * Tests whether a path is an integration symlink that is safe to delete.
+ * Only valid when running RD as an AppImage.
```
Comment (mook-as) [inline background.ts:610]: Isn't this also called on macOS (or rpm / etc.)? We should make _something_ handle that correctly.

File: background.ts [hunk 7]
```diff
@@ -576,46 +577,62 @@ async function getVersion() {
...
+ * @param path -- absolute path to the filesystem node that may be an integration symlink
+ */
+async function isManagedIntegration(path: string): Promise<boolean> {
+  let mountPath = process.env['APPDIR'];
 
-    if (err) {
-      console.error(`Error creating symlink for ${ linkPath }: ${ err.message }`);
+  if (!mountPath) {
+    throw new Error('isManagedIntegration is only valid when running as AppImage');
```
Comment (mook-as) [inline background.ts:617]: The `APPDIR` environment variable seems like it might collide with non-AppImage things (because it sounds so generic); maybe check that `APPIMAGE` is set first?

File: background.ts [hunk 8]
```diff
@@ -576,46 +577,62 @@ async function getVersion() {
...
+  }
 
-      return err;
-    }
-  } else {
-    err = await new Promise((resolve) => {
-      fs.unlink(linkPath, resolve);
-    });
+  if (!mountPath.endsWith('/')) {
```
Comment (mook-as) [inline background.ts:620]: I know this will only ever be `/` (because AppImage only runs on Linux), but it's a bit nicer to use [`path.sep`](https://nodejs.org/docs/latest-v16.x/api/path.html#pathsep) instead.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: background.ts (hunk 3 above)
Comment (adamkpickering) [reply background.ts:2]: Ok, I changed it to `fs.promises`

File: background.ts (hunk 6 above)
Comment (adamkpickering) [reply background.ts]: It isn't at the moment, though there is nothing preventing someone from assuming it is at the moment. I changed things so that it just returns false if `APPIMAGE` is not set.

File: background.ts (hunk 7 above)
Comment (adamkpickering) [reply background.ts]: Done

File: background.ts [hunk 9]
```diff
@@ -576,46 +577,62 @@ async function getVersion() {
...
-  if (state) {
-    err = await new Promise((resolve) => {
-      fs.symlink(resources.executable(name), linkPath, 'file', resolve);
-    });
+/**
+ * Tests whether a path is an integration symlink that is safe to delete.
+ * Only valid when running RD as an AppImage.
+ * @param path -- absolute path to the filesystem node that may be an integration symlink
+ */
+async function isManagedIntegration(path: string): Promise<boolean> {
```
[the remark this answers is not in the document]
Comment (adamkpickering) [reply background.ts]: I think so. I've made that change. I want to test it on the built appimage before merging though

File: background.ts (hunk 4 above)
Comment (adamkpickering) [reply background.ts:601]: Done.

File: background.ts [hunk 10]
```diff
@@ -576,46 +576,59 @@ async function getVersion() {
...
+    return false;
+  }
 
-      return err;
+  let linkedTo: string;
+
+  try {
+    linkedTo = await fs.promises.readlink(pathToCheck);
+  } catch (error: any) {
+    if (error.code === 'EINVAL') {
```
Comment (mook-as) [inline background.ts:625]: Would we need to guard against `ENOENT` here too? (`EINVAL` would be a file exists, but is not a symlink.)

**Review by mook-as — CHANGES_REQUESTED** [review]

File: background.ts (hunk 10 above)
Comment (jandubois) [reply background.ts:625]: Shouldn't **any** error result in a `false` return? I would think `linkedTo` is undefined when an error has ben thrown, so the following comparison should return `false` anyways.

Comment (jandubois) [reply background.ts:625]: Sorry, I was confused, but the point still remains: why would you want to throw an error? This is being called when the app shuts down, so what value would the user get from getting an error about reading a symlink?

Unless the `pathToCheck` is a symlink that points to the right location, this function should just return `false` and not throw an error.

Comment (adamkpickering) [reply background.ts]: Yeah that's a good idea, done.

**Review by mook-as — DISMISSED** [review]
LGTM; please double check Jan's comment (about not throwing from `isManagedIntegration`), and if you think that shouldn't be address just merge directly.

File: background.ts (hunk 10 above)
Comment (adamkpickering) [reply background.ts]: Sorry Jan, for some reason github didn't display your comments when I looked at it yesterday. I will make that change.

**Review by mook-as — APPROVED** [review]
