### PR TITLE
Lima: Fix switching vmnet interfaces.

### LINKED ISSUE #3067: Switching to socket_vmnet does not properly restart the VM
I do a Factory Reset, and then start RD with all default settings. When k8s is working, I try to switch from `vde_vmnet` to `socket_vmnet`:

```console
$ rdctl api --method PUT --body '{"kubernetes":{"experimental":{"socketVMNet":true}}}' settings
reconfiguring Rancher Desktop to apply changes (this may take a while)
```

The old VM is stopped, and I'm asked for the admin password (presumably because the sudoers file will change). After entering the password, nothing else happens; the VM is not started.

`lima.log` looks confused: There are attempts to stop `k3s` after already shutting down the VM with `limactl stop 0`.

The output from `limactl sudoers` also looks wrong. The problem seems to be that `_config/networks` contains neither `paths.socketVMNet` nor `paths.vdeVMNet`.

Full log: [lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/9687697/lima.log)

### PR DESCRIPTION
**Pull request by mook-as**
This should fix #3067 and possibly what Eric saw in #3068 (but maybe not the original error).

The core of the issue is that when we didn't have network configuration (or it was invalid), we used the default value without copying; hence when we later mutated it, we mutated the default configuration in-place.

This PR also fixes some of the places where we run a command with special handling for the failure (to check if the sudoers file is up to date, for example); before this PR, we'd log the failure complete with stack trace.  This ended up being misleading when things failed for other reasons.

### CODE REVIEW

File: src/backend/lima.ts [hunk 1]
```diff
@@ -300,7 +300,7 @@ export default class LimaBackend extends events.EventEmitter implements VMBacken
     case State.STOPPED:
     case State.ERROR:
     case State.DISABLED:
-      await this.kubeBackend.stop();
+      await this.kubeBackend.destroy();
```
Comment (ericpromislow) [inline src/backend/lima.ts:303]: Is this not too drastic? Do we need a second parameter to `setState` to indicate we actually want to do this?

File: src/backend/lima.ts [hunk 2]
```diff
@@ -687,7 +687,17 @@ export default class LimaBackend extends events.EventEmitter implements VMBacken
   /**
    * Run `limactl` with the given arguments, and return stdout.
    */
-  protected async limaWithCapture(this: Readonly<this>, ...args: string[]): Promise<string> {
+  protected async limaWithCapture(this: Readonly<this>, ...args: string[]): Promise<string>;
+  protected async limaWithCapture(this: Readonly<this>, expectFailure: true, ...args: string[]): Promise<string>;
+  protected async limaWithCapture(this: Readonly<this>, argOrExpectFailure: true | string, ...args: string[]): Promise<string> {
+    let expectFailure = false;
```
Comment (ericpromislow) [inline src/backend/lima.ts:693]: I was thinking it was time to add a field like this as well :)

File: src/backend/lima.ts [hunk 3]
```diff
@@ -2086,12 +2099,20 @@ class LimaKubernetesBackend extends events.EventEmitter implements K8s.Kubernete
   async stop() {
     if (this.cfg?.enabled) {
       try {
-        await this.vm.execCommand({ root: true, expectFailure: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+        const script = 'if [ -e /etc/init.d/k3s ]; then /sbin/rc-service --ifstarted k3s stop; fi';
```
Comment (ericpromislow) [inline src/backend/lima.ts:2102]: How about `'test -e /etc/init.d/k3s && /sbin/rc-service --ifstarted k3s stop` ?

Also, don't you want to do this in `LimaBackend::stop` as well?

File: src/backend/lima.ts [hunk 4]
```diff
@@ -2086,12 +2099,20 @@ class LimaKubernetesBackend extends events.EventEmitter implements K8s.Kubernete
...
+
+        await this.vm.execCommand({ root: true, expectFailure: true }, '/bin/sh', '-c', script);
       } catch (ex) {
-        console.error('k3s stop failed: ', ex);
+        console.error('Failed to stop k3s while stopping kube backend: ', ex);
       }
     }
+    await this.destroy();
```
Comment (ericpromislow) [inline src/backend/lima.ts:2109]: Same question ... do we really want to destroy the VM every time we stop it?

**Review by ericpromislow — CHANGES_REQUESTED** [review]
This seems drastic. What about deleting the VM only if we're switching the `socketVMNet` pref?

But I can be convinced that we need to do this...

Assuming this is what we need to do, a suggestion using `test -e ... && ...` instead of `if ... fi` and doing it that in the other place where we call `k3s stop`.

File: src/backend/lima.ts (hunk 3 above)
Comment (mook-as) [reply src/backend/lima.ts:2102]: `foo && bar` would still fail if `foo` is falsy.  So I'm explicitly using `if; then` instead.

I'm not doing this in `LimaBackend::stop` because that didn't seem necessary (because we should have k3s installed already).

File: src/backend/lima.ts (hunk 1 above)
Comment (mook-as) [reply src/backend/lima.ts:303]: Perhaps we should rename `destroy`? I think this (before the refactor) was just clearing the k8s client anyway, so maybe just call it `destroyClient`?

File: src/backend/lima.ts (hunk 4 above)
Comment (mook-as) [reply src/backend/lima.ts:2109]: The VM is not being destroyed, just the k8s client. I'll rename the methods.

File: src/backend/lima.ts (hunk 3 above)
Comment (ericpromislow) [reply src/backend/lima.ts:2102]: Makes sense.

File: src/backend/lima.ts (hunk 4 above)
Comment (ericpromislow) [reply src/backend/lima.ts:2109]: I followed the link, and yes, it's jus closing server things that would be closed anyway.

**Review by ericpromislow — APPROVED** [review]
Looks good.

Understood that if you're going to switch interfaces you need to shut down RD to read in the new pref setting.
