### PR TITLE
Replace `confirm` and `alert` with electron equivalent 

### LINKED ISSUE #1865: Windows 10 Pro - Can't focus on Image to Pull/Build after changing container runtime
### Actual Behavior

Image to Pull/Build does not focus and cannot be given focus after changing container runtime

### Steps to Reproduce

1. Toggle container runtime from `dockerd` to `containerd` and wait for Kubernetes to restart.

2. Navigate to Images => Add an Image

3. Image to Pull does not focus

4. Image to Pull cannot be given focus

### Result

Image to Pull/Build does not focus and cannot be given focus after changing container runtime

### Expected Behavior

Image to Pull/Build should be able to focus.

User should be able to enter a value.

### Additional Information

_No response_

### Rancher Desktop Version

1.2.0 - Release Candidate

### Rancher Desktop K8s Version

N/A

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

10.0.19044 Build 19044

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

N/A

### PR DESCRIPTION
**Pull request by rak-phillip**
This replaces all browser implementations of `confirm` and `alert` in `K8s.vue` with the electron equivalent by making use of the ipc `show-message-box` event. 

This also adds a new argument to `show-message-box` so that we can make the message box behave as a modal. Doing this will help to keep the UI functioning similar to how it did before.

### macOS 1.3.0

Screen Shot 2022-06-07 at 4 35 18 PM

### macOS PR #2336 

Screen Shot 2022-06-07 at 5 34 28 PM

### Linux 1.3.0

image

### Linux PR #2336 

image

### Windows 1.3.0

image

### Windows PR #2336 

image

Closes #1865

### CODE REVIEW

File: src/pages/K8s.vue [hunk 1]
```diff
@@ -435,6 +446,30 @@ export default {
...
       this.handleNotification('error', key, message);
     },
+    confirm(message) {
+      return ipcRenderer.invoke(
+        'show-message-box',
+        {
+          message,
+          type:     'question',
+          title:    'Rancher Desktop - Kubernetes Settings',
+          buttons:  ['Ok', 'Cancel'],
```
Comment (ericpromislow) [inline src/pages/K8s.vue:456]: Text should be `OK` (see src/assets/translations/en-us.yaml)

Comment (ericpromislow) [inline src/pages/K8s.vue:456]: Also note that with the buttons in that order, pressing "OK" will return 0, and pressing "Cancel" or the ESC key will return 1. The code above is handling the opposite....

File: src/pages/K8s.vue [hunk 2]
```diff
@@ -397,14 +406,16 @@ export default {
...
       if (value === this.settings.kubernetes.options.traefik) {
         return;
       }
 
       const confirmationMessage = `Kubernetes will restart after ${ value ? 'enabling' : 'disabling' } Traefik. \n\nDo you want to proceed?`;
 
-      if (!confirm(confirmationMessage)) {
+      const confirm = await this.confirm(confirmationMessage);
+
+      if (!confirm.response) {
```
Comment (ericpromislow) [inline src/pages/K8s.vue:418]: This is the opposite of what you intend, but I would explicitly compare results, and I would be even more explicit:
```
const OK_POSITION = 0;
const CANCEL_POSITION = 1;
...
if (confirm.response === CANCEL_POSITION) {
  return;
}
...
const buttons = new Array(2);
buttons[OK_POSITION] = 'OK';
buttons[CANCEL_POSITION] = 'Cancel';
...
'show-message-box', { ... buttons: buttons ... }
```

File: src/pages/K8s.vue [hunk 3]
```diff
@@ -305,7 +305,9 @@ export default {
         false: 'Resetting Kubernetes will delete all workloads and configuration.',
       }[wipe];
 
-      if (confirm(`${ consequence }\n\nDo you want to proceed?`)) {
+      const confirm = await this.confirm(`${ consequence }\n\nDo you want to proceed?`);
+
+      if (!confirm.response) {
```
Comment (ericpromislow) [inline src/pages/K8s.vue:310]: Same comment about explicity testing for `OK_POSITION`

File: src/pages/K8s.vue [hunk 4]
```diff
@@ -329,11 +331,14 @@ export default {
           confirmationMessage = `Changing from version ${ this.settings.kubernetes.version } to ${ event.target.value } will upgrade Kubernetes`;
         }
         confirmationMessage += '\n\nDo you want to proceed?';
-        if (confirm(confirmationMessage)) {
+
+        const confirm = await this.confirm(confirmationMessage);
+
+        if (!confirm.response) {
```
Comment (ericpromislow) [inline src/pages/K8s.vue:337]: Same comment about explicity testing for OK_POSITION

File: src/pages/K8s.vue [hunk 5]
```diff
@@ -342,7 +347,9 @@ export default {
         const confirmationMessage = [`Changing container engines from ${ this.containerEngineNames[this.currentEngine] } to ${ this.containerEngineNames[desiredEngine] } will require a restart of Kubernetes.`,
           '\n\nDo you want to proceed?'].join('');
 
-        if (confirm(confirmationMessage)) {
+        const confirm = await this.confirm(confirmationMessage);
+
+        if (!confirm.response) {
```
Comment (ericpromislow) [inline src/pages/K8s.vue:352]: Same suggestion about `confirm.response === OK_POSITION`

File: src/pages/K8s.vue [hunk 6]
```diff
@@ -372,7 +379,9 @@ export default {
           '\n\nDo you want to proceed?'
         ].join('');
 
-        if (confirm(confirmationMessage)) {
+        const confirm = await this.confirm(confirmationMessage);
+
+        if (!confirm.response) {
```
Comment (ericpromislow) [inline src/pages/K8s.vue:384]: Same suggestion about using `confirm.response === OK_POSITION`

**Review by ericpromislow — CHANGES_REQUESTED** [review]
The traefix button is broken -- the confirm does the reverse of the intention -- but I would be more aware of how this dialog will behave on all three platforms -- for example, will any of them put the `Cancel` button before `OK` because of UI standards? In any case, being more explicit about determining the result of a dialog will be safer in the long run.

File: src/pages/K8s.vue (hunk 1 above)
Comment (rak-phillip) [reply src/pages/K8s.vue]: I just opted to use i18n so we don't have to guess.

File: src/pages/K8s.vue (hunk 2 above)
Comment (rak-phillip) [reply src/pages/K8s.vue]: We explicitly check for `cancelPosition` in the `confirm` method now. I also opted to guard in each method that makes use of `confirm` so that we consistently make use of the same pattern throughout. Let me know what you think.

**Review by ericpromislow — APPROVED** [review]
LGTM

**Comment by rak-phillip** [comment]
@ericpromislow tests passed after rebase, but I need another review. No changes were made since the rebase.

**Review by ericpromislow — APPROVED** [review]
LGTM
