### PR TITLE
WSL Proxy: just ignore whitespace when looking for duplicates.

### LINKED ISSUE #5366: User cannot delete a no-proxy host
### Actual Behavior

By trying to delete a host from the no-proxy list, the Preferences dialog displays an error dialog with the message: "Errors in proposed settings: field "experimental.virtualMachine.proxy.noproxy" has duplicate entries: "", that blocks the user to save the changes. 

### Steps to Reproduce

1. Go to Preferences > WSL > proxy
2. Hit enter and leave the new line empty 
3. Delete a host from the leaving the line empty
4. Check the error message that pops up

### Result

the Preferences dialog displays an error dialog with the message: "Errors in proposed settings: field "experimental.virtualMachine.proxy.noproxy" has duplicate entries: "", that blocks the user to save the changes. 

no-proxy

### Expected Behavior

User must be able to delete hosts and successfully save the changes

### Additional Information

The exclusion of whitespaces in the no-proxy list can prevent this behaviour

### Rancher Desktop Version

1.9.1-520-g18b7fa88

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5366 (second time)

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
This seems incorrect; I can add multiple entries that are the same except for trailing whitespace.

Presumably the desired behaviour is closer to changing it to `onChange(…, ….split('\n').map(s => s.strip()).filter(x => x))`.

**Comment by ericpromislow** [comment]
Note that issue #5344 will do a better job of dealing with this problem, but entails more work.

File: background.ts [hunk 1]
```diff
@@ -467,10 +467,8 @@ Electron.app.on('before-quit', async(event) => {
     await k8smanager?.stop();
 
     console.log(`2: Child exited cleanly.`);
-  } catch (ex) {
-    if (isK8sError(ex)) {
-      console.log(`2: Child exited with code ${ ex.errCode }`);
-    }
+  } catch (ex: any) {
```
Comment (mook-as) [inline background.ts:470]: This seems like a change from #5463

**Review by mook-as — CHANGES_REQUESTED** [review]

File: background.ts (hunk 1 above)
Comment (ericpromislow) [reply background.ts]: Figured it out ... it's gone now

**Comment by ericpromislow** [comment]
With commit 'Ignore white-space only noproxy-IP entries' the code that consumes this preference item ignores all white-space-only entries, so it doesn't matter what the white-space lines look like in the textarea.

File: pkg/rancher-desktop/backend/wsl.ts [hunk 2]
```diff
@@ -852,7 +852,7 @@ export default class WSLBackend extends events.EventEmitter implements VMBackend
       await this.writeFile(`/etc/moproxy/proxy.ini`, '; no proxy defined');
     }
 
-    await this.modifyConf('moproxy', { MOPROXY_NOPROXY: proxy.noproxy.join(',') });
+    await this.modifyConf('moproxy', { MOPROXY_NOPROXY: proxy.noproxy.filter(ip => ip).join(',') });
```
Comment (mook-as) [inline pkg/rancher-desktop/backend/wsl.ts:855]: Should this strip whitespace & make things unique? I end up with:

> `MOPROXY_NOPROXY="…,240.0.0.0/4,foo,foo ,foo  ,foo   "`

I'm mostly worried that the user will copy & paste something and then end up with space at the end of the line unintentionally, and then get confused that things aren't working.

**Review by mook-as — APPROVED** [review]

File: pkg/rancher-desktop/backend/wsl.ts (hunk 2 above)
Comment (ericpromislow) [reply pkg/rancher-desktop/backend/wsl.ts:855]: Yes, obviously. I was just filtering out empty lines, but need to do more.

File: pkg/rancher-desktop/backend/wsl.ts [hunk 3]
```diff
@@ -852,7 +852,7 @@ export default class WSLBackend extends events.EventEmitter implements VMBackend
       await this.writeFile(`/etc/moproxy/proxy.ini`, '; no proxy defined');
     }
 
-    await this.modifyConf('moproxy', { MOPROXY_NOPROXY: proxy.noproxy.join(',') });
+    await this.modifyConf('moproxy', { MOPROXY_NOPROXY: proxy.noproxy.filter(ip => ip.trim()).join(',') });
```
Comment (mook-as) [inline pkg/rancher-desktop/backend/wsl.ts:855]: Pretty sure you never want `a.filter(x => x.trim())`, but instead `a.map(x => x.trim()).filter(x => x)` instead (since currently you're not keeping the result of the trim).

**Review by mook-as — CHANGES_REQUESTED** [review]

**Review by mook-as — APPROVED** [review]
