### PR TITLE
RDX: Bypass CORS

### LINKED ISSUE #8285: RDX: Extensions should not do CORS
### Actual Behavior

We currently make CORS requests (`HTTP OPTIONS`) when extension UI makes XHR requests.

### Steps to Reproduce

1. Run Rancher Desktop in dev mode (to get dev tools)
2. Install extension that makes XHR requests
3. Read the network logs

### Result

CORS requests are made (with `Origin` of `x-rd-extension://…`).

### Expected Behavior

For compatibility, it seems like we shouldn't be making CORS requests when the extension UI makes requests (to the wider internet, as in XHR).

### Additional Information

_No response_

### Rancher Desktop Version

1.18.0-54-gb0f0c47de

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.7.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by mook-as**
For compatibility reasons, we need to let the extensions enjoy Internet-wide access without having to worry about silly things like CORS.  Fixes #8285.

Unfortunately, trying to properly disable CORS did not work: the only thing that managed was to set `webSecurity: false`, but that broke the preload script (as in, it wasn't being loaded at all).

As a workaround, I'm intercepting requests and responses and faking the CORS response to be always successful.

### CODE REVIEW

File: pkg/rancher-desktop/window/index.ts [hunk 1]
```diff
@@ -218,6 +218,57 @@ function createView() {
...
+        callback({});
+
+        return;
+      }
+
+      // Insert (or overwrite) CORS headers to pretend this was allowed.  While
+      // ideally we can just disable `webSecurity` instead, that seems to break
+      // the preload script (which breaks the extension APIs).
+      const responseHeaders: Record<string, string|string[]> = { ...details.responseHeaders };
+      const { compare } = new Intl.Collator('en', { sensitivity: 'accent' });
```
Comment (Nino-K) [inline pkg/rancher-desktop/window/index.ts:249]: I assume this means `é` and `e` are different, but `A` and `a` are treated the same? nit; it would be nice to document.

File: pkg/rancher-desktop/window/index.ts [hunk 2]
```diff
@@ -218,6 +218,57 @@ function createView() {
...
+      }
+
+      if (details.method !== 'OPTIONS') {
+        // For any request that's not a CORS preflight, just overwrite the headers.
+        callback({ responseHeaders });
+      } else {
+        // For CORS preflights, also change the status code.
+        const prefix = /\s+/.exec(details.statusLine)?.shift() ?? 'HTTP/1.1';
+
+        callback({ responseHeaders, statusLine: `${ prefix } 204` });
```
Comment (Nino-K) [inline pkg/rancher-desktop/window/index.ts:269]: nit; would it make sense to make a constant for 204 (noContent)?

**Review by Nino-K — APPROVED** [review]

File: pkg/rancher-desktop/window/index.ts (hunk 1 above)
Comment (mook-as) [reply pkg/rancher-desktop/window/index.ts:249]: Yes; but HTTP headers only support standard ASCII anyway.

File: pkg/rancher-desktop/window/index.ts (hunk 2 above)
Comment (mook-as) [reply pkg/rancher-desktop/window/index.ts:269]: It didn't seem like it was worth it, because it needs to be in the string anyway. I'll add the `No Content` part to the string so it's easier to read?
