### PR TITLE
RDX: Set up the API synchronously.

### LINKED ISSUE #4320: This version of @docker/extension-api-client is not supported
```
index.js:5 Uncaught Error: This version of @docker/extension-api-client is not supported by your version of Docker Desktop. Please upgrade to the latest version.
    at index.js:5:15
    at useDockerDesktopClient.ts:19:16
    at index.js:35:1
    at index.js:35:1
(anonymous) @ index.js:5
(anonymous) @ useDockerDesktopClient.ts:19
(anonymous) @ index.js:35
(anonymous) @ index.js:35
```

### PR DESCRIPTION
**Pull request by mook-as**
It looks like some extensions expect the API to be ready immediately, so we can't wait around for the main process to pass info in before setting it up.  Instead, get the main process to pass everything in as arguments to the window (via `process.argv`).

Fixes #4320.  Probably a bit lower priority than various API implementations.

### CODE REVIEW

File: pkg/rancher-desktop/preload/extensions.ts [hunk 1]
```diff
@@ -266,18 +266,18 @@ class Client implements v1.DockerDesktopClient {
     openExternal: (url: string) => {
       ipcRenderer.send('extensions/open-external', url);
     },
-    platform: '<unknown>',
-    arch:     '<unknown>',
+    platform: process.platform,
+    arch:     process.arch,
```
Comment (adamkpickering) [inline pkg/rancher-desktop/preload/extensions.ts:270]: So `host.arch` defaults to `process.arch`, but can be overridden by passing a value into the constructor. I can see the default behavior causing subtle bugs - maybe it would be better to require `arch` to be passed in the constructor?  I see that we always set it explicitly anyways.

**Review by adamkpickering — DISMISSED** [review]
Just one comment. I'm fine with it either way - please merge merge if you don't want to change it.

**Review by adamkpickering — APPROVED** [review]
