### PR TITLE
rdctl: don't fail on missing or bad config file until we need it.

### LINKED ISSUE #2143: rdctl start fails after factory reset
### Actual Behavior

```
(⎈ |rancher-desktop:default) ~/p/w/hubble-timescape ❯❯❯ rdctl start --flannel-enabled=false                                                                                                                  pr/chancez/helm-custom-ca ⬆ ⬇ ✭ ◼
2022/04/29 10:24:27 Error trying to read file /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: open /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: no such file or directory
```

### Steps to Reproduce

- Start rancher desktop
- Perform factory reset
- use `rdctl start`

### Result

```
2022/04/29 10:24:27 Error trying to read file /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: open /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: no such file or directory
```

### Expected Behavior

Rdctl starts rancher-desktop, using default values for unspecified options, and does not error.

### Additional Information

```
(⎈ |rancher-desktop:default) ~/p/w/hubble-timescape ❯❯❯ rdctl version                                                                                                                                        pr/chancez/helm-custom-ca ⬆ ⬇ ✭ ◼
rdctl client version: 1.1.0, targeting server version: v0
(⎈ |rancher-desktop:default) ~/p/w/hubble-timescape ❯❯❯ which rdctl                                                                                                                                          pr/chancez/helm-custom-ca ⬆ ⬇ ✭ ◼
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/rdctl
```

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

n/a

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Darwin dune.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2143 

So the key here is to get the error associated with the command-server config file, but only display the error and fail if we need the information.

There are two cases where this happens:

1. The commands that need to talk to the server: the user specifies settings for all of `--user`, `--password`, and `--port`.

2. The command is `rdctl start` and Rancher Desktop isn't running, so we're going to actually start.
Note that this variant of `rdctl start` fails if RD is running and for some reason the user has deleted `rd-engine.json`, turned off permissions, or changed its contents. In this rare case, the app will try to run `rdctl start`, and then the user will get a message (in background.log?) stating that it's already running.

One complication is that `rdctl start` is a hybrid -- if it has arguments and RD is running, it quietly switches to `rd set` (but still needs to give any error messages from the point of view of someone who typed `rdctl start`).

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
At this point, `root.go` is doing too much; we should refactor that so config initialization is in a package.  Especially the smuggling of the config parsing error is just too confusing.

File: src/go/rdctl/pkg/config/config.go [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+*/
+
+// Package config handles all the config-related parts of rdctl
+
+package config
+
+import (
+	"encoding/json"
+	"fmt"
+	"github.com/spf13/cobra"
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:24]: Hmm, the imports should be in stdlib / libs / internal order.

File: src/go/rdctl/cmd/root.go [hunk 2]
```diff
@@ -19,16 +19,13 @@ package cmd
...
 	"io/ioutil"
-	"log"
 	"net/http"
 	"os"
-	"path/filepath"
-	"strconv"
 	"strings"
 
+	"github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config"
 	"github.com/spf13/cobra"
```
Comment (mook-as) [inline src/go/rdctl/cmd/root.go:29]:
```suggestion
	"github.com/spf13/cobra"

	"github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config"
```
(Import ordering)

File: src/go/rdctl/pkg/config/config.go [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+	port     string
+	password string
+
+	configDir           string
+	configPath          string
+	defaultConfigPath   string
+	deferredConfigError error
+)
+
+// DefineGlobalFlags sets up the global flags, available for all sub-commands
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:51]: The comment should be changed, I think, to say something about configs.  `root.go` is free to add even more flags.

Maybe rename the function too?

File: src/go/rdctl/pkg/config/config.go [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+	rootCmd.PersistentFlags().StringVar(&configPath, "config-path", "", fmt.Sprintf("config file (default %s)", defaultConfigPath))
+	rootCmd.PersistentFlags().StringVar(&user, "user", "", "overrides the user setting in the config file")
+	rootCmd.PersistentFlags().StringVar(&host, "host", "", "default is localhost; most useful for WSL")
+	rootCmd.PersistentFlags().StringVar(&port, "port", "", "overrides the port setting in the config file")
+	rootCmd.PersistentFlags().StringVar(&password, "password", "", "overrides the password setting in the config file")
+}
+
+// GetConnectionInfo returns the connection info if it has it, and an error message explaining why
+// it isn't available if it doesn't have it.
+func GetConnectionInfo() (string, string, string, string, error) {
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:69]: There should be some documentation about the return values: having a pile of `string` in a row is super confusing (imagine accidentally expecting `user, password, host, port` instead).

That's kind of why I like structs better…

File: src/go/rdctl/pkg/config/config.go [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+	if deferredConfigError != nil && insufficientConnectionInfo() {
+		return "", "", "", "", deferredConfigError
+	}
+	return host, port, user, password, nil
+}
+
+// InitConfig is run after all modules are loaded and before the appropriate Execute function is invoked
+func InitConfig() {
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:77]: This doesn't need to be exported, right? Just called from within `GetConnectionInfo` (possibly via a `sync.Once`)?

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/go/rdctl/pkg/config/config.go (hunk 3 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:51]: I don't understand this comment. Of course more global flags can be defined in `root.go`, but the name of the function strongly suggests it shouldn't.

Right now all the global flags are for connection parameters, but that could be expanded in the future. I think the names in this package are general enough to allow for that.

File: src/go/rdctl/pkg/config/config.go (hunk 4 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:69]: OK, going with a struct...

File: src/go/rdctl/pkg/config/config.go (hunk 5 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:77]: Well, the function needs to be invoked after the flags have been processed, but before the subcommand's `RunE` method is invoked.  From the cobra code:
```
// OnInitialize sets the passed functions to be run when each command's
// Execute method is called.
```

This does exactly what we want. I could experiment with a different approach, but this isn't a typical Cobra-based approach, and I don't see what it accomplishes.

File: src/go/rdctl/cmd/root.go (hunk 2 above)
Comment (ericpromislow) [reply src/go/rdctl/cmd/root.go:29]: done

File: src/go/rdctl/pkg/config/config.go (hunk 1 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:24]: done

File: src/go/rdctl/cmd/root.go [hunk 6]
```diff
@@ -19,35 +19,22 @@ package cmd
...
 	"strings"
 
 	"github.com/spf13/cobra"
+
+	"github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config"
 )
 
 type APIError struct {
 	Message          *string `json:"message,omitifempty"`
 	DocumentationUrl *string `json:"documentation_url,omitifempty"`
```
Comment (mook-as) [inline src/go/rdctl/cmd/root.go:35]: Just realized this is a typo — it should be `omitempty` not `omitifempty`. Probably separate PR though.

File: src/go/rdctl/pkg/config/config.go (hunk 5 above)
Comment (mook-as) [reply src/go/rdctl/pkg/config/config.go:84]: But it doesn't need to run before `RunE`; it just needs to be done before `GetConnectionInfo` returns (because that's the only point at which other packages can get the results).

> This does exactly what we want. I could experiment with a different approach, but this isn't a typical Cobra-based approach, and I don't see what it accomplishes.

The typical cobra-based approach involves _zero knowledge_ of cobra outside `cmd/`. So this is already a non-standard approach; it would be better to excise cobra from here completely.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/go/rdctl/pkg/config/config.go (hunk 5 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:84]: Once again it turns out following Mark's suggestion makes for cleaner code. About to push a commit that gets rid of the `deferredConfigError` variable, should be more straightforward.

File: src/go/rdctl/cmd/root.go (hunk 6 above)
Comment (ericpromislow) [reply src/go/rdctl/cmd/root.go:35]: best to get it fixed now

File: src/go/rdctl/pkg/config/config.go [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+)
+
+// The CLIConfig struct is used to store the json data read from the config file.
+type CLIConfig struct {
+	User     string
+	Password string
+	Port     int
+}
+
+type ConnectionInfo struct {
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:40]: I know this is pretty obvious, but we should still document exported types.

File: src/go/rdctl/pkg/config/config.go [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+		// If the default config file isn't available, it might not have been created yet,
+		// so don't complain if we don't need it.
+		// But if the user specified their own --config-path and it's not readable, complain immediately.
+		return err, configPath != defaultConfigPath
+	}
+
+	var settings CLIConfig
+	err = json.Unmarshal(content, &settings)
+	if err != nil {
+		return fmt.Errorf("error in config file %s: %s", configPath, err), configPath != defaultConfigPath
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:101]:
```suggestion
		return fmt.Errorf("error in config file %s: %w", configPath, err), configPath != defaultConfigPath
```
Prefer `%w` when wrapping other errors.

File: src/go/rdctl/pkg/config/config.go [hunk 9]
```diff
@@ -0,0 +1,118 @@
...
+	if connectionSettings.User == "" {
+		connectionSettings.User = settings.User
+	}
+	if connectionSettings.Password == "" {
+		connectionSettings.Password = settings.Password
+	}
+	if connectionSettings.Port == "" {
+		connectionSettings.Port = strconv.Itoa(settings.Port)
+	}
+	return nil, false
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:113]: Any reason not to just implement `insufficientConnectionInfo` inline here instead?

File: src/go/rdctl/pkg/config/config.go [hunk 10]
```diff
@@ -0,0 +1,118 @@
...
+	rootCmd.PersistentFlags().StringVar(&connectionSettings.Port, "port", "", "overrides the port setting in the config file")
+	rootCmd.PersistentFlags().StringVar(&connectionSettings.Password, "password", "", "overrides the password setting in the config file")
+}
+
+// GetConnectionInfo returns the connection info if it has it, and an error message explaining why
+// it isn't available if it doesn't have it.
+// So if the user runs an `rdctl` command after a factory reset, there is no config file (in the default location),
+// but it might not be necessary. So only use the error message for the missing file if it is actually needed.
+func GetConnectionInfo() (*ConnectionInfo, error) {
+	err, isImmediateError := initConfig()
```
Comment (mook-as) [inline src/go/rdctl/pkg/config/config.go:76]: We should do something to prevent `initConfig` from being called multiple times; it's harmless but confusing for something called `init…`. Hence the [`sync.Once`](https://pkg.go.dev/sync#Once) suggestion earlier.

**Review by mook-as — CHANGES_REQUESTED** [review]
Please consider adding some tests for `config.go`.

File: src/go/rdctl/pkg/config/config.go (hunk 9 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:113]: Yes, because it's long enough that it made sense to me to use the function name as a form of documentation.

File: src/go/rdctl/pkg/config/config.go (hunk 10 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:76]: In a larger system I could see a case being made for this, but the code is small and straightforward enough -- `GetConnectionInfo` is invoked on two different code paths (one for GET requests, one for POST requests), and nothing else calls it.

I had a look at `sync.Once` and using that would introduce other complications because it's geared more to `void` functions, and we'd need a wrapper.

This seems like more of a consideration in an environment with more hostile actors, but this is a standalone client.

And I don't see any problems if in fact the function is called subsequent times. Most of the time it updates parameters that aren't set yet, and they should all be set after the first call.

As a compromise, I renamed the function to `finishConnectionSettings`

File: src/go/rdctl/pkg/config/config.go (hunk 8 above)
Comment (ericpromislow) [reply src/go/rdctl/pkg/config/config.go:101]: ok

**Comment by ericpromislow** [comment]
And I added some e2e tests on the missing config-file.

File: e2e/rdctl.e2e.spec.ts [hunk 11]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+          expect(stderr).not.toContain('Usage:');
+          expect(stdout).toEqual('');
+        });
+
+        test('it works with all parameters,', async() => {
+          const { stdout, stderr, error } = await rdctl(parameters.concat(['list-settings']));
+
+          expect(error).toBeUndefined();
+          expect(stderr).toEqual('');
+          expect(stdout).toMatch(/"kubernetes":/);
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:303]: `.toContain` / `expect.stringContaining` seems like a better match here?

File: e2e/rdctl.e2e.spec.ts [hunk 12]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+          const settings = JSON.parse(stdout);
+
+          expect(['version', 'kubernetes', 'portForwarding', 'images', 'telemetry', 'updater', 'debug', 'pathManagementStrategy']).toMatchObject(Object.keys(settings));
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:306]: Is this backwards? You're asserting that this is a _superset_ of the actual properties, I believe.
```suggestion
          expect(settings).toMatchObject({
            version: expect.anything(),
            kubernetes: expect.anything(),
            …
          });
```
(If you take the suggested for, you can also optionally use `.toEqual` instead of `.toMatchObject` to ensure no extra properties.)

File: e2e/rdctl.e2e.spec.ts [hunk 13]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+        });
+        test("it complains when some parameters aren't specified", async() => {
+          for (let idx = 0; idx < parameters.length; idx += 1) {
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:309]: (This can now be expressed as `for (const idx in parameters)`, but I'm not sure it's clearer.)

File: e2e/rdctl.e2e.spec.ts [hunk 14]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+            const partialParameters: string[] = parameters.slice(0, idx).concat(parameters.slice(idx + 1));
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:310]: The type declaration here is redundant.

This can also be expressed as `const partialParameters = parameters.concat(); partialParameters.splice(idx, 1);` but again I'm not sure that's clearer.

File: e2e/rdctl.e2e.spec.ts [hunk 15]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+            expect(stderr).not.toContain('Usage:');
+            expect(stdout).toEqual('');
+          }
+        });
+        test.describe('when a non-existent config file is specified', () => {
+          test('it fails even when all parameters are specified', async() => {
+            let badConfigFile = '/less/salt/more/gravy.json';
+            let i = 0;
+
+            // Ensure the specified configFile doesn't exist. Give up if we have to add 100 x's to the end.
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:324]: Why not just use [`fs.promises.mkdtemp()`](https://nodejs.org/docs/latest-v16.x/api/fs.html#fspromisesmkdtempprefix-options) to make a guaranteed non-existant directory (and therefore know that it doesn't contain any named config file)?

File: e2e/rdctl.e2e.spec.ts (hunk 13 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:309]: I tried that but typescript assumes `idx` is a string, and then it complains that `TS2345: Argument of type 'string' is not assignable to parameter of type 'number | undefined'.`.

If I try `const idx: number in parameters` I get `TS2404: The left-hand side of a 'for...in' statement cannot use a type annotation.`

And if I try `parameters.slice(0, idx as number)` I get `TS2352: Conversion of type 'string' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.`

There comes a time where it makes sense to stop fighting with TypeScript and go with the code I submitted.

File: e2e/rdctl.e2e.spec.ts (hunk 15 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:324]: Good point.

File: e2e/rdctl.e2e.spec.ts [hunk 16]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+        test.beforeAll(async() => {
+          const dataRaw = await fs.promises.readFile(configFilePath, 'utf-8');
+
+          serverState = JSON.parse(dataRaw);
+          parameters = [`--password=${ serverState.password }`,
+            `--port=${ serverState.port }`,
+            `--user=${serverState.user }`,
+          ];
+          try {
+            await spawnFile(mvCommand, [configFilePath, backupPath]);
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:274]: Because I need to reread the `fs` docs more often :)

File: e2e/rdctl.e2e.spec.ts [hunk 17]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+          } catch (err) {
+            console.log(`Error trying to ${ mvCommand } ${ configFilePath} ${ backupPath }: `, err);
+            expect(err).toBeUndefined();
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:277]: Got that one with the better `fs.promises.rename...`

File: e2e/rdctl.e2e.spec.ts (hunk 13 above)
Comment (mook-as) [reply e2e/rdctl.e2e.spec.ts:309]: Argh. Yeah, not worth the trouble, then.

File: e2e/rdctl.e2e.spec.ts [hunk 18]
```diff
@@ -255,6 +255,92 @@ test.describe('Command server', () => {
...
+          }
+        });
+
+        test('it complains with no parameters,', async() => {
+          const { stdout, stderr, error } = await rdctl(['list-settings']);
+
+          expect(error).toBeDefined();
+          expect(stderr).toContain(`Error: open ${ configFilePath }: no such file or directory`);
+          expect(stderr).not.toContain('Usage:');
+          expect(stdout).toEqual('');
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:295]: Had to run a round to verify these work when there are errors.

File: e2e/rdctl.e2e.spec.ts (hunk 13 above)
Comment (rak-phillip) [reply e2e/rdctl.e2e.spec.ts:309]: @ericpromislow @mook-as The behavior you describe makes sense and I think you might want `for...of` instead of `for...in`:

> It is better to use a [for](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for) loop with a numeric index, [Array.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), or the [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loop, because they will return the index as a number instead of a string, and also avoid non-index properties.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#array_iteration_and_for...in

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#difference_between_for...of_and_for...in

File: e2e/rdctl.e2e.spec.ts (hunk 12 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:306]: It wasn't backwards -- I was deliberately verifying that there weren't other fields in the payload. This way sets the required fields, so I'll go with that.

File: e2e/rdctl.e2e.spec.ts [hunk 19]
```diff
@@ -255,71 +255,201 @@ test.describe('Command server', () => {
...
+        stdout, stderr, error
+      }).toEqual({
+        error:  undefined,
+        stderr: '',
+        stdout: expect.stringContaining('"kubernetes":'),
+      });
       const settings = JSON.parse(stdout);
 
-      expect(['version', 'kubernetes', 'portForwarding', 'images', 'telemetry', 'updater', 'debug', 'pathManagementStrategy']).toMatchObject(Object.keys(settings));
+      expect(settings).toMatchObject({
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:365]: You said you wanted to not have extras, right? Should that be `.toEqual` instead of `.toMatchObject`, then?

(And would you want to do `Object.fromEntries(Object.keys(settings.defaultSettings).map(k => [k, expect.anything()]))` to future-proof?)

**Review by mook-as — APPROVED** [review]
I didn't expect you to go fix every case to use a large `toEqual` instead of multiple small ones, but I'm glad you did!

File: e2e/rdctl.e2e.spec.ts (hunk 19 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:365]: My intention was to do a sanity-check on `rdctl list-settings`.
