### PR TITLE
Override default input event in `RdSelect`

### LINKED ISSUE #4916: First Run dialog: Unable to select version
### Actual Behavior

The Kubernetes version cannot be selected in the first run dialog.

### Steps to Reproduce

1. Run `rdctl factory-reset`
2. Start Rancher Desktop (resulting in the first run dialog)
3. Leave Kubernetes enabled (per default)
4. Select a non-default version of Kubernetes

### Result

The version selector goes blank (it appears that the _Recommended Versions_ heading is selected)…

image image

Note that in this situation I can't re-select the original default either.

### Expected Behavior

Before selecting:
image

We should select a version.

### Additional Information

_No response_

### Rancher Desktop Version

1.7.0-1669-g22e4b6c2

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Big Sur 11.7.7

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by rak-phillip**
The problem described in issue #4916 appears to be related to using arrow keys to select options within the `RdSelect` component when used with `v-model`. In this scenario, the entire `vnode` was emitted instead of just the selected value. 

To resolve this issue, we override the default listeners for `RdSelect` by adding a custom `input` event that emits `e.target.value` to ensure that the correct value is emitted when selecting values.

This issue was specific to the first run dialog, as other usages of `RdSelect` throughout Rancher Desktop utilize `:val` and `@change`.

While investigating this bug, I observed that other frameworks avoid wrapping selects and re-implement select behavior from scratch. There may be a reason behind this approach and we might want to take this into consideration in the future.

closes #4916

### CODE REVIEW

File: pkg/rancher-desktop/components/RdSelect.vue [hunk 1]
```diff
@@ -27,6 +27,13 @@ export default Vue.extend({
         this.$emit('input', newValue);
       },
     },
+    computedListeners(): Record<string, Function | Function[]> & { input: (e: any) => any; } {
```
Comment (mook-as) [inline pkg/rancher-desktop/components/RdSelect.vue:30]: It may be a good idea to have (a more concise version of?) the PR description as a comment here, to explain why we're doing this.

Or maybe hook up the singular listener on `mount` or something?

**Review by mook-as — APPROVED** [review]

**Review by mook-as — APPROVED** [review]
