### PR TITLE
Address integration management shortcomings

### LINKED ISSUE #3034: Files in ~/.rd/bin should always be overwritten
I modified `~/.rd/bin/docker-buildx` to be a symlink to a different file (see also #3033). It shows the error in the diagnostics.

When I stopped and restarted Rancher Desktop, the file was still a symlink to the wrong location.

The `~/.rd/bin` directory is under the sole control of Rancher Desktop. We should fix any incorrect link on application startup. There is no need to prompt the user, or save the old content; we can simply replace it to bring the directory content in sync with the application configuration.

It is the files in `~/.docker/cli-plugins` that we should not remove/replace without user consent.

### LINKED ISSUE #3113: Modify `UnixIntegrationManager` so that it modifies symlinks with a target path containing `/opt/rancher-desktop/resources/resources/linux/bin/`
Related to #2456.

@himslm01 is getting the following diagnostic error message:

> The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to /opt/rancher-desktop/resources/resources/linux/bin/docker-buildx.

Currently, `UnixIntegrationManager` only updates a symlink in `~/.docker/cli-plugins` when its target path starts with `~/.rd/bin`. We need to modify it so that it will also update symlinks whose target path starts with `/opt/rancher-desktop/resources/resources/linux/bin/`, which appears to be something that RD created in the past (pre-1.3.0 as far as I can tell).

### PR DESCRIPTION
**Pull request by adamkpickering**
Closes #3034.
Closes #3113.

Also related to Jan's comment in #2445.

This addresses various minor issues with integration management. If you want to see the specific cases that are now fixed, the best place to do that would be the unit tests - each case has its own test. I was able to keep things pretty coherent from commit to commit, so going by commit is probably easiest way to review this.

Note that this is based off of #3183, so we should merge that one first.

### CODE REVIEW

File: src/integrations/unixIntegrationManager.ts [hunk 1]
```diff
@@ -67,15 +67,35 @@ export default class UnixIntegrationManager implements IntegrationManager {
...
+    } catch (error: any) {
+      if (error.code !== 'ENOENT') {
+        throw error;
+      }
+    }
+
+    // remove current integrations that are not valid
+    await Promise.all(currentIntegrationNames.map(async(name) => {
+      if (!validIntegrationNames.includes(name)) {
+        await fs.promises.rm(path.join(this.integrationDir, name), { force: true });
```
Comment (ericpromislow) [inline src/integrations/unixIntegrationManager.ts:85]: I don't know if we should delete files that we don't recognize, even if it is "our" directory. Users might have put files there my accident ... I just think it's better to err on the side of caution when it comes to users' files.

Comment (adamkpickering) [reply src/integrations/unixIntegrationManager.ts:85]: What if we stop bundling a utility? Without this, we are left with a dangling symlink. This hasn't happened yet, and I don't see how it would cause a problem, but it's nice to keep things clean.

@jandubois what do you think?

I don't have strong feelings either way.

Comment (ericpromislow) [reply src/integrations/unixIntegrationManager.ts:85]: True, good point on assuming we own that directory and have the right to clean it up.

**Review by ericpromislow — DISMISSED** [review]
LGTM - various tests worked, including creating a non-writable kubectl owned by root in `~/.rd/bin`, and it gets removed without a peep, as expected.

**Review by ericpromislow — APPROVED** [review]
