### PR TITLE
Ensure that `rancher-desktop` distro is created after unregistering it when upgrading

### LINKED ISSUE #2934: CI Build Test: Ran into ENOENT: no such file or directory, open '\\wsl$\rancher-desktop\etc\hosts'
### Actual Behavior

Ran into ENOENT: no such file or directory, open '\\wsl$\rancher-desktop\etc\hosts' at the first launch post installation.

### Steps to Reproduce

I noticed this behavior with the CI build: 

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3071306322

Steps:

- Have the current release 1.5.1 installed on your machine.
- Close the Rancher Desktop application if it's running
- Install above CI build
- After installation, I ran into the error as shown in the screenshot.

At this stage, no commands (I tried nerdctl, kubectl ) work. I had to perform `Reset Kubernetes` to restore the session to a working state.

### Result

image

### Expected Behavior

Rancher Desktop launches with out any error.

### Additional Information

_No response_

### Rancher Desktop Version

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3071306322

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by adamkpickering**
`upgradeDistroAsNeeded` unregisters the `rancher-desktop` distro when it is out of date, but does not create it again. This was the case in 1.5.1 as well, but it wasn't a problem there because `ensureDistroRegistered` was called immediately after `upgradeDistroAsNeeded`.

Closes #2934.

### CODE REVIEW

File: src/backend/wsl.ts [hunk 1]
```diff
@@ -1014,6 +1012,7 @@ export default class WSLBackend extends events.EventEmitter implements VMBackend
         const prepActions = [(async() => {
           await this.ensureDistroRegistered();
           await this.initDataDistribution();
+          await this.upgradeDistroAsNeeded();
```
Comment (mook-as) [inline src/backend/wsl.ts:1015]: `initDataDistribution` needs to the the upgraded distro registered, so that it can copy files from there into the data distribution.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/backend/wsl.ts [hunk 2]
```diff
@@ -267,9 +267,6 @@ export default class WSLBackend extends events.EventEmitter implements VMBackend
    */
   protected async ensureDistroRegistered(): Promise<void> {
     if (await this.isDistroRegistered()) {
-      // rancher-desktop distribution is already registered.
-      await this.progressTracker.action('Checking distribution version', 50, this.upgradeDistroAsNeeded());
```
Comment (mook-as) [inline src/backend/wsl.ts:271]: Please add a note that we'll do any upgrades immediately after.

File: src/backend/wsl.ts [hunk 3]
```diff
@@ -288,6 +285,8 @@ export default class WSLBackend extends events.EventEmitter implements VMBackend
     if (!await this.isDistroRegistered()) {
       throw new Error(`Error registering WSL2 distribution`);
     }
+
+    await this.initDataDistribution();
```
Comment (mook-as) [inline src/backend/wsl.ts:289]: This needs to always be called (we can have the main distro registered without the data distro existing).

**Review by mook-as — APPROVED** [review]
