### PR TITLE
Only set `pathManagementStrategy` in first run modal when on Unix

### LINKED ISSUE #2057: First run modal sets `settings.pathManagementStrategy` to `RcFiles`, causing crash on Windows
This may be a problem for the path update modal as well.

### PR DESCRIPTION
**Pull request by adamkpickering**
Closes #2057.

`PathUpdate.vue` is not an issue since opening it is behind an `if` statement that depends on the platform.

### CODE REVIEW

File: src/store/applicationSettings.js [hunk 1]
```diff
@@ -27,6 +27,6 @@ export const actions = {
 
 export const getters = {
   getPathManagementStrategy({ pathManagementStrategy }) {
-    return pathManagementStrategy !== PathManagementStrategy.NotSet ? pathManagementStrategy : PathManagementStrategy.RcFiles;
+    return pathManagementStrategy;
```
Comment (rak-phillip) [inline src/store/applicationSettings.js:30]: Changing this getter will remove the default that we provide in `src/pages/PathUpdate.vue`. I think we have two choices to resolve this:

1. Revert this change and update `src/pages/FirstRun.vue` so that we don't write the `pathManagementStrategy` in the `onChange` method
2. Update `src/pages/PathUpdate.vue` so that it will properly set a default value

File: src/pages/FirstRun.vue [hunk 2]
```diff
@@ -119,6 +119,9 @@ export default Vue.extend({
       this.settings.kubernetes.enabled = config.kubernetes.enabled;
     });
     ipcRenderer.send('k8s-versions');
+    if (this.pathManagementRelevant) {
+      this.setPathManagementStrategy(PathManagementStrategy.RcFiles)
```
Comment (rak-phillip) [inline src/pages/FirstRun.vue:123]: Linting errors, missing semicolon

**Review by rak-phillip — CHANGES_REQUESTED** [review]
Great catch on this one

I think we'll need to change a few things before we merge 🙂

File: src/store/applicationSettings.js (hunk 1 above)
Comment (adamkpickering) [reply src/store/applicationSettings.js:29]: Nice catch. I opted for 2 - it should work properly now.

**Review by rak-phillip — APPROVED** [review]
LGTM
