### PR TITLE
Fail with a fatal error if the settings.json file has no version.

### LINKED ISSUE #5922: `version` field in `settings.json` should be mandatory
The application should refuse to start (with a fatal error dialog) if `settings.json` doesn't include a valid `version` field.

This is necessary to correctly determine which migrations should be performed.

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5922

### CODE REVIEW

File: background.ts [hunk 1]
```diff
@@ -218,6 +218,9 @@ Electron.app.whenReady().then(async() => {
       const message = err.message || err.toString();
 
       showErrorDialog(titlePart, message, true);
+      if (err instanceof settings.SettingsError) {
```
Comment (mook-as) [inline background.ts:221]: We're passing in `fatal=true`, and the app quits immediately; please add a comment on why the extra `return` is required (because it's very non-obvious).

File: pkg/rancher-desktop/config/settingsImpl.ts [hunk 2]
```diff
@@ -32,19 +32,28 @@ let settings: Settings | undefined;
...
 
   try {
     // If the existing settings file is partial, fill in the missing fields with defaults.
-    merge(cfg, JSON.parse(rawdata.toString()));
+    const currentConfig = JSON.parse(rawdata.toString());
+
+    if (!('version' in currentConfig)) {
+      throw new SettingsError(`No version specified in ${ settingsPath }`);
+    }
+    merge(defaultConfig, currentConfig);
```
Comment (mook-as) [inline pkg/rancher-desktop/config/settingsImpl.ts:46]: `currentConfig` here is possibly some old version; if we merge the current-version defaults in first that seems like an issue. We should migrate the (complete?) settings before merging with the defaults.

File: pkg/rancher-desktop/config/settingsImpl.ts [hunk 3]
```diff
@@ -32,19 +32,28 @@ let settings: Settings | undefined;
...
 
-    return migrateSettingsToCurrentVersion(cfg);
+    return migrateSettingsToCurrentVersion(defaultConfig);
   } catch (err: any) {
+    if (err instanceof SettingsError) {
+      throw err;
+    }
```
Comment (mook-as) [inline pkg/rancher-desktop/config/settingsImpl.ts:52]: It seems like the `try`/`catch` should only cover the `JSON.parse`, and not the rest?

File: e2e/startup-profiles.e2e.spec.ts [hunk 4]
```diff
@@ -171,6 +173,31 @@ test.describe.serial('track startup windows based on existing profiles and setti
...
+        application: {
+          debug:                  true,
+          pathManagementStrategy: PathManagementStrategy.Manual,
+          startInBackground:      false,
+        },
+      };
+      const settingsFullPath = path.join(paths.config, 'settings.json');
+
+      fs.mkdirSync(paths.config, { recursive: true });
+      fs.writeFileSync(settingsFullPath, JSON.stringify(versionLessSettings));
```
Comment (mook-as) [inline e2e/startup-profiles.e2e.spec.ts:191]: You're in an `async` function, prefer the promise version over sync.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: background.ts (hunk 1 above)
Comment (ericpromislow) [reply background.ts:221]: We've been using `Electron.app.quit()` which shuts things down gracefully, but the code is still running asynchronously. Maybe we should create an issue to use `Electron.app.exit` instead?

File: pkg/rancher-desktop/config/settingsImpl.ts (hunk 3 above)
Comment (ericpromislow) [reply pkg/rancher-desktop/config/settingsImpl.ts:52]: Yes, that makes sense.

File: e2e/startup-profiles.e2e.spec.ts (hunk 4 above)
Comment (ericpromislow) [reply e2e/startup-profiles.e2e.spec.ts:191]: yup

File: background.ts [hunk 5]
```diff
@@ -218,6 +218,12 @@ Electron.app.whenReady().then(async() => {
       const message = err.message || err.toString();
 
       showErrorDialog(titlePart, message, true);
+      // if (err instanceof settings.SettingsError) {
+      //   // Even though we're passing fatal=true to showErrorDialog,
+      //   // this process still runs after the call to `Electron.app.quit()`,
+      //   // so stop processing this handler.
+      //   return;
+      // }
```
Comment (mook-as) [inline background.ts:226]: Did you mean to have commented out code here? Is that needed?

**Review by mook-as — CHANGES_REQUESTED** [review]

File: background.ts (hunk 5 above)
Comment (jandubois) [reply background.ts:226]: We are using version control, so should generally just delete code that isn't needed anymore.

If parts of the comments need to stay, then move them out of the conditional and make sure they are understandable on their own.

Comment (ericpromislow) [reply background.ts]: Yes, it is needed. If we switch from `Electron.app.quit()` to `Electron.app.exit()` we don't but that change will need a lot of testing, and should be a separate issue.

**Comment by ericpromislow** [comment]
Exit issue added at #6038

File: background.ts (hunk 1 above)
Comment (mook-as) [reply background.ts:221]: Okay, in that case: why do we _not_ need to do the early return if `err` is _not_ `SettingsError` (where we still pass `fatal=true`)?

That is: I don't understand why the condition exists (rather than just always returning early).

**Review by mook-as — CHANGES_REQUESTED** [review]

File: background.ts (hunk 1 above)
Comment (ericpromislow) [reply background.ts:221]: Because the current JavaScript code block is still executing. Once it's done, the shutdown process will start. This is what the output looks like without the return statement:
```
Error

No version specified in /Users/ericp/Library/Preferences/rancher-desktop/settings.json
2023-11-28T21:42:35.666Z: Error starting up: TypeError: Cannot read properties of undefined (reading 'application') TypeError: Cannot read properties of undefined (reading 'application')
    at /Users/ericp/git/ericpromislow/rancher/desktop/dist/app/background.js:44122:113
```

The `return` stmt prevents the `Cannot read properties of undefined` lines from appearing.  These message are appearing because `settings` is unset.

The app is going to shut down anyway, and those lines just confuse things.

Comment (mook-as) [reply background.ts:221]: Okay, why don't we need it for all the _other_ cases? What makes this one special? (And that needs to live in the code, not in a PR comment…)

Comment (ericpromislow) [reply background.ts:221]: We really needed to return in this case, because `cfg` is null. I explain that, but I added a `return` for the other class of fatal errors because there's no point continuing to run the `whenReady` handler for them as well.

File: background.ts [hunk 6]
```diff
@@ -232,16 +235,13 @@ Electron.app.whenReady().then(async() => {
...
-        // Errors related to either deployment profiles or
-        // attempts to change locked fields on the command-line are both fatal,
-        // and should appear in a dialog box (or be written to console if
-        // --no-modal-dialogs was specified on the command-line).
         handleFailure(err).catch((err2: any) => {
           console.log('Internal error trying to show a failure dialog: ', err2);
           process.exit(2);
         });
+
+        // showErrorDialog doesn't exit immediately; avoid running the rest of the function
```
Comment (mook-as) [inline background.ts:243]: This code path doesn't call `showErrorDialog`? It _does_ call `handleFailure`, which does call `showErrorDialog(…, true)`.

```suggestion
        // Avoid running the rest of the function while handleFailure runs.
```

**Review by mook-as — CHANGES_REQUESTED** [review]
Just a final comment change.

File: background.ts (hunk 6 above)
Comment (ericpromislow) [reply background.ts]: ok, with a slight elaboration without getting into implementation details

**Review by mook-as — APPROVED** [review]
