### PR TITLE
Open only a single Dashboard window

### LINKED ISSUE #1787: Rancher Dashboard Integration (Deskboard) - Limit to single window
### Actual Behavior

Clicking on the Dashboard entry multiple time in the tray menu will open a new Dashboard window for each click. We should limit to a single window.

### Steps to Reproduce

1. Make sure Kubernetes is enabled
2. Wait for Kubernetes to start
3. Click on the Rancher Desktop tray icon and select Dashboard
4. Click on the Rancher Desktop tray icon and select Dashboard a second time

### Result

Two Dashboard windows are opened

### Expected Behavior

Just a single dashboard is opened.

The open dashboard window is given focus when selecting dashboard a second time.

### Additional Information

_No response_

### Rancher Desktop Version

1.1.1-dev

### Rancher Desktop K8s Version

NA

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

NA

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by rak-phillip**
This limits the number of open dashboard windows to 1 by checking if a dashboard window already exists in the window mapping. 

closes #1787

### CODE REVIEW

File: src/window/dashboard.ts [hunk 1]
```diff
@@ -1,10 +1,18 @@
 import { BrowserView, BrowserWindow } from 'electron';
-import { windowMapping } from '.';
+import { windowMapping, didRestoreWindow } from '.';
 
 const dashboardURL = 'http://127.0.0.1:9080/dashboard/c/local/explorer';
 
+const getDashboardWindow = () => ('dashboard' in windowMapping) ? BrowserWindow.fromId(windowMapping['dashboard']) : null;
+
 export function openDashboard() {
```
Comment (mook-as) [inline src/window/dashboard.ts:8]: This function does not handle clicking external links (e.g. links to docs or GitHub page). I assume this is okay?

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/window/index.ts [hunk 2]
```diff
@@ -23,15 +23,11 @@ function getWebRoot() {
...
- * @param options A hash of options used by `new BrowserWindow(options)`
- * @param prefs Options to control the new window.
+ * Restore or focus a window if it is already open
+ * @param window The Electron Browser window to show or restore
+ * @returns Boolean: True if the browser window is shown or restored
  */
-function createWindow(name: string, url: string, options: Electron.BrowserWindowConstructorOptions) {
-  let window = (name in windowMapping) ? BrowserWindow.fromId(windowMapping[name]) : null;
-
+export const didRestoreWindow = (window: Electron.BrowserWindow | null): window is Electron.BrowserWindow => {
```
[the remark this answers is not in the document]
Comment (rak-phillip) [reply src/window/index.ts:30]: My original intent was to name this function in a way so that it would be clear that it was answering the question of "did this window restore/get focus? If not, we need to create a new window". I originally started with something like `hasWindowToRestore`, but that didn't make sense because we're actually performing an action; it was then a tossup between `canRestoreWindow` vs `didRestoreWindow`.

In hindsight, I guess prefixing with `did` kind of has that association with checking if something happened in the past.. I'm open to prefixing with `try`, but in my mind that would infer that a function has wrapped some other function in a `try...catch` block. Perhaps that's an incorrect assumption on my part.. in the end I'd rather go with whatever is most clear to the rest of the team.

File: src/window/dashboard.ts (hunk 1 above)
Comment (rak-phillip) [reply src/window/dashboard.ts:8]: I don't think that's a concern here.. maybe we can review a potential use case to make sure I'm not overlooking something?

Comment (mook-as) [reply src/window/dashboard.ts:8]: I poked around the dashboard and couldn't find any links to external addresses. We can probably punt on this until somebody complains? (We don't seem to be doing any SSL cert overrides, so having a page incorrectly opening in the dashboard window shouldn't be fatal.)

File: src/window/index.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (rak-phillip) [reply src/window/index.ts]: I think `restoreWindow` is a fair compromise. It honestly gets the point across quite effectively without any of the `try`, `did`, `can` nonsense 😆

**Review by mook-as — APPROVED** [review]
