### PR TITLE
Ignore trailing slash(es) when checking for integration dir in PATH.

### LINKED ISSUE #2977: Diagnostics check for ~/.rd/bin fails if there is a trailing slash
If I manually configure the `PATH` and add `/Users/jan/.rd/bin/`, then the diagnostic fails, even though the directory is correct and works.

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2977

Note that this relies on PR #2982 to avoid gnarly conflicts in the future.

This PR also assumes the temporary log statements from 2951 are no longer needed

- Paths coming from $PATH are user-supplied and need to be verified.
- paths.integration should never have a trailing slash, but we might as well check.

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/main/diagnostics/rdBinInShell.ts [hunk 1]
```diff
@@ -71,6 +73,12 @@ class RDBinInShellPath implements DiagnosticsChecker {
       fixes,
     };
   }
+
+  static removeTrailingSlash(s: string): string {
+    const m = /(.*?)(\/+)$/.exec(s);
+
+    return m ? (m[1] || '/') : s;
```
Comment (jandubois) [inline src/main/diagnostics/rdBinInShell.ts:80]: Simler expression:

```suggestion
    return s.replace(/(.)\/*$/, "$1");
```

Demo:

```
> "/foo/bar//".replace(/(.)\/*$/, "$1")
'/foo/bar'
> "/".replace(/(.)\/*$/, "$1")
'/'
> "//".replace(/(.)\/*$/, "$1")
'/'
> "".replace(/(.)\/*$/, "$1")
''
```

**Review by jandubois — APPROVED** [review]
LGTM, but I would simplify the `removeTrailingSlash` function.

**Review by jandubois — DISMISSED** [review]
LGTM

**Review by jandubois — APPROVED** [review]
