### PR TITLE
WSL: Fix `docker run --mount`

### LINKED ISSUE #1077: Issue using VS Code Remote Container extension
As 0.7.0.beta.1 has docker support, I am trying to get the VS Code extension [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) with Rancher Desktop.

When I tried to open a locally cloned copy of this [repo](https://github.com/microsoft/vscode-remote-try-node), I ran into below error.

`Error response from daemon: invalid mount config for type "bind": invali
d mount path: 'c:/2021/remotecontainers/vscode-remote-try-node' mount path must
be absolute.`

Note - I tried this on my Windows machine, some discussion forums say that it's a windows specific issue and this functionality might work in Mac, Linux environments.

### PR DESCRIPTION
**Pull request by mook-as**
This adds support for `docker run --mount=…`; there are two places the moby API supports volume mounts.

This requires https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/18 to land first (and the distro to be tagged as 0.9).  The tagging is complete, and CI is currently building the new distribution.

Fixes #1077.

### CODE REVIEW

File: src/go/wsl-helper/cmd/root.go [hunk 1]
```diff
@@ -27,10 +27,7 @@ var rootCmd = &cobra.Command{
 	Short: "Rancher Desktop WSL2 integration helper",
 	Long:  `This command handles various WSL2 integration tasks for Rancher Desktop.`,
 	PersistentPreRun: func(cmd *cobra.Command, args []string) {
-		if viper.GetBool("verbose") {
-			logrus.SetLevel(logrus.TraceLevel)
-		}
-		logrus.SetLevel(logrus.TraceLevel)
+		logrus.SetLevel(logrus.InfoLevel + logrus.Level(viper.GetInt("verbose")))
```
Comment (ericpromislow) [inline src/go/wsl-helper/cmd/root.go:30]: Is this conventional? To me it looks like it's relying on `logrus.InfoLevel + viper.GetInt('verbose') == logrus.TraceLevel`. Unless it's typical usage, I would prefer an `if/else` stmt

Comment (mook-as) [reply src/go/wsl-helper/cmd/root.go:30]: That's for being able to set `--verbose=2` to get trace (`--verbose` by itself is just debug).  `if/else` would have to have multiple levels.

**Review by ericpromislow — COMMENTED** [review]
Code looks ok but I'll defer to Guna's review because I didn't try it with the VS Code extensions.

**Comment by mook-as** [comment]
We can at least try it with the [reduced steps](https://github.com/rancher-sandbox/rancher-desktop/issues/1077#issuecomment-988317775) (one `docker run`) — it sounds like this by itself wouldn't fix all of Guna's problems.

**Review by gunamata — APPROVED** [review]
This PR resolves the mount issue. I am approving it but I would let Eric review the code changes.
