### PR TITLE
Extend timeout for network connectivity diagnostic

### LINKED ISSUE #3283: Extend timeout for online diagnostic
The code to check if the host is online tries to fetch `http://example.com` with a 2 second timeout. Several people on Slack have reported that this diagnostic shows up incorrectly, most likely because the timeout is too low.

I would suggest increasing the timeout to 5s and also adding an environment variable like `RD_ONLINE_CHECK_TIMEOUT` to allow overriding the default.

### PR DESCRIPTION
**Pull request by adamkpickering**
Closes #3283.

Signed-off-by: Adam Pickering <adam.pickering@suse.com>

### CODE REVIEW

File: src/main/diagnostics/connectedToInternet.ts [hunk 1]
```diff
@@ -2,19 +2,36 @@ import fetch from 'node-fetch';
...
 
+import Logging from '@/utils/logging';
+
+const console = Logging.diagnostics;
+
+let timeout = 5000;
+
+if (process.env.RD_CONNECTED_TO_INTERNET_TIMEOUT) {
+  timeout = parseInt(process.env.RD_CONNECTED_TO_INTERNET_TIMEOUT);
+}
```
Comment (jandubois) [inline src/main/diagnostics/connectedToInternet.ts:13]: Instead of caching the value, I would like to query the environment variable every time we start the timeout.

If/when #3284 is implemented, we will be able to change settings on-the-fly without stopping the app. Querying the variable is cheap, so caching doesn't really matter, but changing settings at runtime will help us with writing automated tests.

File: src/main/diagnostics/connectedToInternet.ts [hunk 2]
```diff
@@ -2,19 +2,45 @@ import fetch from 'node-fetch';
...
+import Logging from '@/utils/logging';
+
+const console = Logging.diagnostics;
+
+// Returns the timeout, in milliseconds, for the network connectivity check.
+function getTimeout(): number {
+  if (process.env.RD_CONNECTED_TO_INTERNET_TIMEOUT) {
+    const parsedTimeout = parseInt(process.env.RD_CONNECTED_TO_INTERNET_TIMEOUT);
+
+    if (!isNaN(parsedTimeout) && parsedTimeout > 0) {
```
Comment (jandubois) [inline src/main/diagnostics/connectedToInternet.ts:14]: All comparison operators return `false` if one of their operands is `NaN`, so the extra check is not necessary:

```suggestion
    if (parsedTimeout > 0) {
```

**Review by jandubois — APPROVED** [review]
Thanks, LGTM!
