### PR TITLE
Fix checking for ~/.rd/bin in shell rc files

### LINKED ISSUE #2951: Diagnostics check for zsh not working correctly
Testing using https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3094433305

The diagnostics claim:

```
The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your zsh shell. 
```

But this isn't true:

```console
$ zsh -c 'echo $PATH'
/Users/jan/.rd/bin:/Users/jan/bin:[...]
```

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2951

* Use -ic 'echo $PATH' for both bash and zsh
* Don't assume the full paths for bash and zsh
* Allow for shell login processes to output to stdout -- separate it from the path

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/main/diagnostics/rdBinInShell.ts [hunk 1]
```diff
@@ -18,43 +19,45 @@ mainEvents.on('settings-update', (cfg) => {
...
   async check() {
-    const { stdout } = await spawnFile(this.executable, this.args, { stdio: 'pipe' });
-    const dirs = stdout.trim().split(':');
-    const desiredDirs = dirs.filter(p => p === paths.integration);
-    const passed = desiredDirs.length > 0;
     const fixes: {description: string}[] = [];
-    const exe = path.basename(this.executable);
-    let description = `The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your ${ exe } shell.`;
+    let passed = false;
+    let description = '';
```
Comment (mook-as) [inline src/main/diagnostics/rdBinInShell.ts:39]:
```suggestion
    let description: string;
```
Let the TypeScript compiler ensure that we always assign to this before reading it.

File: src/main/diagnostics/rdBinInShell.ts [hunk 2]
```diff
@@ -18,43 +19,45 @@ mainEvents.on('settings-update', (cfg) => {
...
+        const description = `You have selected manual PATH configuration;
+            consider letting Rancher Desktop automatically configure it.`;
 
-      fixes.push({ description: description.replace(/\s+/gm, ' ') });
+        fixes.push({ description: description.replace(/\s+/gm, ' ') });
+      }
+    } catch (ex: any) {
+      description = ex.message ?? ex.toString();
+      passed = false;
+      fixes.push({ description: 'fix the exception' });
```
Comment (mook-as) [inline src/main/diagnostics/rdBinInShell.ts:60]: Let's not push anything instead of having something the user can't really do anything with (even if they can't see it).

File: src/backend/lima.ts [hunk 3]
```diff
@@ -759,7 +759,7 @@ export default class LimaBackend extends events.EventEmitter implements VMBacken
    * Get the current Lima VM status, or undefined if there was an error
    * (e.g. the machine is not registered).
    */
-  protected get status(): Promise<LimaListResult | undefined> {
+  get status(): Promise<LimaListResult | undefined> {
```
Comment (mook-as) [inline src/backend/lima.ts:762]: Wrong PR?

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/backend/lima.ts (hunk 3 above)
Comment (ericpromislow) [reply src/backend/lima.ts:762]: yup

File: src/main/diagnostics/rdBinInShell.ts (hunk 2 above)
Comment (ericpromislow) [reply src/main/diagnostics/rdBinInShell.ts:60]: ok

**Review by mook-as — APPROVED** [review]
