### PR TITLE
Path management: rename files in place where possible

### LINKED ISSUE #7154: Rancher Desktop 1.14.2 wiped my .zshrc file.
### Actual Behavior

Unfortunately it seems this recurring bug is still around. I just lost my .zhrc and .bashrc at a minimum.

Didn't have a recent backup handy, my bad, but I had been installing Rancher Desktop to test as a replacement for Docker Desktop and the fact that this appears to be something the devs aren't able to fix on a permanent basis has been enough to put me off using it in the future.

### Steps to Reproduce

N/A

### Result

N/A

### Expected Behavior

I shouldn't need to worry about losing my entire shell config when toying around with resets/etc using Rancher Desktop.

### Additional Information

_No response_

### Rancher Desktop Version

1.14.2

### Rancher Desktop K8s Version

1.30.2

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS Sonoma, M3 Pro

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by mook-as**
When we're dealing with normal files, write to a temporary file then rename it into place to avoid issues where we might end up partially writing to the file.  When we're writing through a symlink, make a backup first so that it would be easier for the user to recover if something goes wrong.

Note that this introduces scenarios where we now bail out instead of writing:
- If the file to write is neither a normal file nor a symlink.
- If the file is a normal file, but it has extended attributes.
- If the user is on Linux, the file is a normal file, and `/usr/bin/getfattr` is not available.

This should fix #7154 (and uses the algorithm described in https://github.com/rancher-sandbox/rancher-desktop/issues/7154#issuecomment-2231957512).  Note that in this instance, I wrote the test first in a separate commit, so if check out that commit the tests are expected to fail.

If we have the time for it, I'd like to do a follow-up so the diagnostics can tie into the errors from here and we can provide more information when things don't work correctly.

### CODE REVIEW

**Review by jandubois — CHANGES_REQUESTED** [review]
Still working on the review, but wanted to record my objection to

> If the user is on Linux, the file is a normal file, and /usr/bin/getfattr is not available.

We should try using the `fs-xattr` package instead. It needs `node-gyp`, but since we are already requiring `node-gyp` on Windows (for `native-reg`), maybe it is not a big deal?

`getfattr` is not normally installed by default, so requiring this to let Rancher Desktop manage the `PATH` seems excessive. Especially given that having extended attributes on shell profiles is probably really rare.

**Comment by jandubois** [comment]
I don't think that renaming a file preserves any of the attributes of the target file; they will all be overwritten by the source attributes:

```console
$ echo foo >foo
$ cp foo bar
$ chmod 700 bar
$ setfattr -n user.xyzzy -v plugh foo
$ ls -l
total 8
-rwx------ 1 jan jan 4 Jul 22 18:19 bar
-rw-rw-r-- 1 jan jan 4 Jul 22 18:19 foo
$ getfattr foo
# file: foo
user.xyzzy

$ getfattr bar
$ mv bar foo
$ ls -l
total 4
-rwx------ 1 jan jan 4 Jul 22 18:19 foo
$ getfattr foo
$
```

So after the rename (`mv`) `foo` takes the `700` file attributes from `bar` and also loses the extended attribute.

So I think the only way to do this properly would be to copy the file attributes from the profile to the swap (or backup) file.

This means that the attributes could also be restored the same way in the symlink case.

**Comment by mook-as** [comment]
That's why we do:
https://github.com/rancher-sandbox/rancher-desktop/blob/9898364b0240ccd4442b2cf35bc564e529584014/pkg/rancher-desktop/integrations/manageLinesInFile.ts#L47
That copies the (basic) file attributes:
https://github.com/libuv/libuv/blob/v1.48.0/src/unix/fs.c#L1205-L1206
```c
  if (fchmod(dstfd, src_statsbuf.st_mode) == -1) {
    err = UV__ERR(errno);
```

**Comment by jandubois** [comment]
Oh, I missed/forgot about

> If the file has xattrs (doing a platform-specific check), bail.

**Comment by mook-as** [comment]
Switched to `fs-xattr` as requested. There's some finicky bits around using the native module, but I think that's sorted now.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts [hunk 1]
```diff
@@ -1,80 +1,135 @@
...
 
-    await fs.promises.writeFile(path, newContent);
-  }
-  if (!desiredPresent) {
-    // Ignore the extra empty line that came from the managed block.
-    if (after.length === 1 && after[0] === '') {
-      after = [];
+    await fs.promises.copyFile(path, backupPath, copyFlags);
+
+    const currentContents = await fs.promises.readFile(path, 'utf-8');
```
Comment (jandubois) [inline pkg/rancher-desktop/integrations/manageLinesInFile.ts:77]: Should we read `backupPath` instead of `path`?

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts [hunk 2]
```diff
@@ -1,80 +1,135 @@
...
+  } else if (fileStats.isSymbolicLink()) {
+    const backupPath = `${ path }.rd-backup~`;
 
-    await fs.promises.writeFile(path, newContent);
-  }
-  if (!desiredPresent) {
-    // Ignore the extra empty line that came from the managed block.
-    if (after.length === 1 && after[0] === '') {
-      after = [];
+    await fs.promises.copyFile(path, backupPath, copyFlags);
```
Comment (jandubois) [inline pkg/rancher-desktop/integrations/manageLinesInFile.ts:75]: Should probably wrap any exception into something that is relevant/understandable by the user.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts [hunk 3]
```diff
@@ -1,80 +1,135 @@
...
+        await fs.promises.unlink(tempName);
+      } catch {
+        // Ignore errors unlinking the temporary file; if everything went well,
+        // it no longer exists anyway.
+      }
     }
-    const newLines = buildFileLines(before, desiredManagedLines, after);
-    const newContent = newLines.join(os.EOL);
+  } else if (fileStats.isSymbolicLink()) {
+    const backupPath = `${ path }.rd-backup~`;
```
Comment (jandubois) [inline pkg/rancher-desktop/integrations/manageLinesInFile.ts:73]: Don't we want to check if `backupPath` already exist, and refuse to overwrite it, if it does?

**Review by jandubois — CHANGES_REQUESTED** [review]
The only critical issue is that I think we should not overwrite the backup file if it already exists. Otherwise we will still destroy all copies of the original file if this function is called twice.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts [hunk 4]
```diff
@@ -1,80 +1,135 @@
...
 
-  try {
-    const currentLines = currentContent.split('\n');
+    const tempName = `${ path }.rd-temp`;
 
-    [before, currentManagedLines, after] = splitLinesByDelimiters(currentLines);
-  } catch (error) {
-    throw new Error(`could not split ${ path }: ${ error }`);
-  }
+    await fs.promises.copyFile(path, tempName, copyFlags);
```
[the remark this answers is not in the document]
Comment (mook-as) [reply pkg/rancher-desktop/integrations/manageLinesInFile.ts:44]: No, because we want to error out if the file already exists (indicating a race, or some leftover garbage from a previous crash).

The caller already needs to deal with this throwing.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts [hunk 5]
```diff
@@ -1,80 +1,135 @@
...
+
+    try {
+      const currentContents = await fs.promises.readFile(path, 'utf-8');
```
[the remark this answers is not in the document]
Comment (mook-as) [reply pkg/rancher-desktop/integrations/manageLinesInFile.ts:47]: I suppose that's a good thing, in case somebody else came in and clobbered `path` while we're modifying it.  Will change.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts (hunk 3 above)
Comment (mook-as) [reply pkg/rancher-desktop/integrations/manageLinesInFile.ts:73]: `copyFlags` includes `COPYFILE_EXCL`, so if it already exists, we throw.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts (hunk 2 above)
Comment (mook-as) [reply pkg/rancher-desktop/integrations/manageLinesInFile.ts:75]: I plan to do that as part of #7262.

File: pkg/rancher-desktop/integrations/manageLinesInFile.ts (hunk 1 above)
Comment (mook-as) [reply pkg/rancher-desktop/integrations/manageLinesInFile.ts:77]: I suppose we might as well do that.

**Review by mook-as — COMMENTED** [review]
I'll go make the changes to read from the { temporary | backup } file instead, plus the exception message tweak.

**Review by jandubois — APPROVED** [review]
Thanks, LGTM
