### PR TITLE
Find home directory consistently

### LINKED ISSUE #2527: Start using `kubernetes-client/javascript`/findHomeDir
### Delete `src/config/findHomeDir.ts`

Given this comment:
// TODO: Replace with the k8s version after kubernetes-client/javascript/pull/748 lands

That PR has landed, so we can delete the file and start using the upstream version of `findHomeDir`

### LINKED ISSUE #3344: Windows CI does a mismatch on the kubernetes config file
### Actual Behavior

When the Windows Github CI starts up, it has an empty kubernetes context and can't run

### Steps to Reproduce

See Isabela :)

### Result

Kubernetes fails to start up

### Expected Behavior

It should just work ^trademark

### Additional Information

The source code is all deployed at and run from

`C:/actions-runner/_work/rancher-desktop/rancher-desktop`

and there's a pseudo-home-directory at 

`C:/Windows/ServiceProfiles/NetworkService`

Contents of `C:\Windows\ServiceProfiles\NetworkService\.kube\config`: empty default, like `contexts: []`

but all the local files are at `C:/Windows/ServiceProfiles/NetworkService/AppData/{Local,Roaming}/rancher-desktop`

However, there is another populated `.kube/config` file at `c:/Users/chivo/.kube/config` , that defines the `rancher-desktop` cluster and context, and sets current-context to `rancher-desktop`

The problem seems to be that most of the time, the home-directory is accessed at `c:/Users/chivo` and sometimes it's at 
`C:/Windows/ServiceProfiles/NetworkService/AppData/{Local,Roaming}/rancher-desktop`.

I think the github runner is using `.../NetworkService` as the home directory, but at some point we populate the `.kube/config` file in a different directory.

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

No

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2527
Fixes #3344

Use the k8s/client library whenever looking for the home directory for kubernetes-related uses, namely the location of `.kube/config`

### CODE REVIEW

File: pkg/rancher-desktop/config/kubeconfig.js [hunk 1]
```diff
@@ -2,11 +2,8 @@
 
 const fs = require('fs');
 const pth = require('path');
-// TODO: Uncomment after PR https://github.com/kubernetes-client/javascript/pull/748 lands
-// const k8s = require('@kubernetes/client-node');
 
-// TODO: Stop using the next module (and delete) after kubernetes-client/javascript/pull/748 lands
-const findHomeDir = require('@/config/findHomeDir');
+const k8s = require('@kubernetes/client-node');
```
Comment (mook-as) [inline pkg/rancher-desktop/config/kubeconfig.js:6]: I wonder why we never translated this to TypeScript. (Please don't do that in this PR, though.)

**Review by mook-as — APPROVED** [review]
