### PR TITLE
RDX: Fix installation on Windows

### LINKED ISSUE #4349: RDX: Installing trivy extension with version tag fails
Installing trivy extension with version tag fails with below error message. This is on the branch https://github.com/mook-as/rd/tree/extensions/host-apis

```
>rdctl extension install aquasec/trivy-docker-extension:0.4.6
Internal Server Error
{"message":"500 Internal Server Error"}
```

### PR DESCRIPTION
**Pull request by mook-as**
This fixes issues with installing extensions on Windows.

- There's some differences with how `nerdctl compose up` needs to be handled (because we use `nerdctl-stub` there)
- There's also differences when copying files out on Windows (while Windows `tar.exe` supports symlinks, it requires administrator privileges).
- Fixes running commands in WSL at a specific (Linux) directory.
- When starting, wait for the containerd backend to finish starting, like we do for the moby socket.

This should fix #4349 — needs to re-check after.

### CODE REVIEW

File: pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts [hunk 1]
```diff
@@ -134,6 +134,26 @@ export class NerdctlClient implements ContainerEngineClient {
     }
   }
 
+  async waitForReady(): Promise<void> {
```
Comment (ericpromislow) [inline pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts:137]: I was expecting this function for nerdctl to have the same structure as the one in `pkg/rancher-desktop/backend/containerClient/mobyClient.ts`, although checking two commands instead of one. Probably could use a comment explaining why you don't need to do 10 successful checks before accepting it, like you do with moby (or it's a bug here).

File: pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts [hunk 2]
```diff
@@ -169,19 +190,31 @@ export class NerdctlClient implements ContainerEngineClient {
...
+        ')',
+        '-a',
+        '-exec', '/bin/sh', '-c', `echo '{}' >> ${ fileList }`, ';',
+        ')');
+
       const args = [
         '--create', '--gzip', '--file', archive, '--directory', sourceDir,
-        resolveSymlinks ? '--dereference' : undefined,
-        '--one-file-system', '--sparse', sourceName,
+        '--dereference', '--one-file-system', '--sparse', '--files-from', fileList,
```
Comment (ericpromislow) [inline pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts:208]: !!! Just when I thought I knew all the tar options...

File: pkg/rancher-desktop/main/extensions/extensions.ts [hunk 3]
```diff
@@ -244,16 +244,7 @@ export class ExtensionImpl implements Extension {
         composeDir,
```
Comment (ericpromislow) [inline pkg/rancher-desktop/main/extensions/extensions.ts:244]: Not part of this PR, but the locally-caught `throw` at lines 91 and 99 in this function mean that if there's no`result.icon` result, it looks like the generated error message will be:

`'Could not read extension metadata'`, (submessage: `'Invalid extension: missing icon'`) which I'm not sure you intended. Could be rewritten as:

```
    this._metadata ??= (async() => {
      const fallback = { vm: {} };

      try {
        const raw = await this.readFile('metadata.json');
        const result = _.merge({}, fallback, JSON.parse(raw));

        if (result.icon) {
          return result;
        }
      } catch (ex: any) {
        console.error(`Failed to read metadata for ${ this.id }: ${ ex }`);
        // Unset metadata so we can try again later
        this._metadata = undefined;
        throw new ExtensionErrorImpl(ExtensionErrorCode.INVALID_METADATA, 'Could not read extension metadata', ex);
      }
      throw new ExtensionErrorImpl(ExtensionErrorCode.INVALID_METADATA, 'Invalid extension: missing icon');
    })();
```

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Just a request for a comment and possible code changes. I've lost the abililty to run `bats` tests on Windows, so need someone else to check that both those test files pass.

File: pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts (hunk 1 above)
Comment (mook-as) [reply pkg/rancher-desktop/backend/containerClient/nerdctlClient.ts:137]: `mobyClient` needs the retry because (on Windows) the proxy process dies and restarts multiple times (causing flapping).  Here we're waiting on the `containerd`/`buildkitd` processes on the VM, which once they start working do not die by themselves.

If anything, the fix should be to change the proxy process to stop flapping. That would involve fixing #4551 instead.

**Comment by mook-as** [comment]
Addressed the issue with the error throwing, plus some issues found when testing this on macOS.

I opted not to add the comment in `waitForReady` because it's actually the moby backend that's being weird, and we should fix that separately.

**Review by ericpromislow — APPROVED** [review]
Code looks fine, tests pass, let's merge this
