### PR TITLE
Check for network updates on an interval while tray is shown

### LINKED ISSUE #4030: Network status does not update unless main window is shown
### Actual Behavior

Network status from the tray menu keeps displaying the status "connecting" even after the backend is loaded and kubernetes is running. It only updates if the main window is open.

### Steps to Reproduce

1. Launch Rancher Desktop
2. In Preferences > Application > Behavior, select the option to start in the background
3. Quit application
4. Relaunch it
5. Check the network status via the notification icon

### Result

Network status from the tray menu keeps displaying the status "connecting" even after the backend is loaded and kubernetes is running. It only updates if the main window is open.

network_status

### Expected Behavior

Network status must not rely on the main window and be read independently.

### Additional Information

_No response_

### Rancher Desktop Version

1.7.0-412-g64c00763

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by rak-phillip**
This checks for a change in the network state by invoking the `CONNECTED_TO_INTERNET` handler on a 5 second interval. 

I opted to use an interval in an attempt to keep the approach simple. I imagine that we might want to consider if it makes sense to reduce the frequency of checks after the state has settled, but that might require more discussion on the desired design. 

closes #4030

### CODE REVIEW

File: pkg/rancher-desktop/main/diagnostics/diagnostics.ts [hunk 1]
```diff
@@ -72,6 +72,16 @@ export class DiagnosticsManager {
         await this.runChecker(checker);
       }
     });
+
```
Comment (rak-phillip) [inline pkg/rancher-desktop/main/diagnostics/diagnostics.ts:75]: This is essentially repeated logic from the listener above. The only difference here is that we return our results after checking.

I'm considering if it makes sense to move the logic out into for the two listeners out to a separate function.

**Comment by rak-phillip** [comment]
Reviewing lint errors. My guess is that the inclusion of both `on` and `handle` will mark one as `deprecated`

```
/home/runner/work/rancher-desktop/rancher-desktop/pkg/rancher-desktop/integrations/pathManager.ts
Error:   127:16  error  'emit' is deprecated.   deprecation/deprecation
Error:   128:16  error  'emit' is deprecated.   deprecation/deprecation

/home/runner/work/rancher-desktop/rancher-desktop/pkg/rancher-desktop/main/diagnostics/diagnostics.ts
Error:   68:16  error  'on' is deprecated.   deprecation/deprecation

✖ 3 problems (3 errors, 0 warnings)

Error: Process completed with exit code 1.
```

File: pkg/rancher-desktop/main/mainEvents.ts [hunk 2]
```diff
@@ -104,6 +105,15 @@ interface MainEventNames {
...
   'diagnostics-trigger'(id: string): void;
 
+  /**
+   * Force trigger diagnostics with the given id.
+   * This is used when something has changed that might affect whether the given
+   * diagnostic needs to be re-run.
+   * @note This does not update the last run time (since it only runs a single
+   * checker).
+   */
+  'diagnostics-trigger'(id: string): DiagnosticsCheckerResult | undefined;
```
Comment (mook-as) [inline pkg/rancher-desktop/main/mainEvents.ts:115]: There's already an `diagnostics-trigger` event (just above); duplicating this appears to be confusing eslint. The net effect is that it shadows the previous method, and we _only_ have an even handler (instead of listener channel) instead.

File: pkg/rancher-desktop/main/diagnostics/diagnostics.ts (hunk 1 above)
Comment (mook-as) [reply pkg/rancher-desktop/main/diagnostics/diagnostics.ts:75]: Since it doesn't work anyway, it's probably better to just get rid of the `mainEvents.on('diagnostics-trigger')` and only keep this one. This means that even in places we don't care about the result we'd need to `/* (void) */ mainEvents.invoke('diagnostics-trigger')` (dropping the resulting `Promise<DiagnosticsCheckerResult>` on the floor) instead.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: pkg/rancher-desktop/main/mainEvents.ts (hunk 2 above)
Comment (rak-phillip) [reply pkg/rancher-desktop/main/mainEvents.ts:106]: I opted to remove the listener in favor of handler for this use case.

File: pkg/rancher-desktop/integrations/__tests__/pathManager.spec.ts [hunk 3]
```diff
@@ -4,6 +4,7 @@ import path from 'path';
 
 import { START_LINE, END_LINE } from '@pkg/integrations/manageLinesInFile';
 import { RcFilePathManager } from '@pkg/integrations/pathManager';
+jest.mock('../../main/mainEvents');
```
Comment (rak-phillip) [inline pkg/rancher-desktop/integrations/__tests__/pathManager.spec.ts:7]: I'm researching why using the `@pkg` alias for the jest mocks isn't working. The  relative path appears to be working just fine for now.

**Review by mook-as — APPROVED** [review]
