### PR TITLE
Handle case where set/start proposed changed field kubernetes.version is locked.

### LINKED ISSUE #5047: Kubernetes version can be editable when quitting RD with deployment profiles
### Actual Behavior

Given a locked deployment profile, the kubernetes version can be editable via `rdctl start` even if this field is locked in the profile

### Steps to Reproduce

1. Create a SYSTEM deployment profile (file under field Additional Information)
2. Start Rancher Desktop
3. Quit the application via tray menu/ run `rdctl shutdown`
4. Try to change the value of the locked field via `rdctl start`
5. Verify if the new settings is applied

### Result

Rancher Desktop starts with no errors and the locked kubernetes version is actually editable via `rdctl start`.
```

"kubernetes": {
    "version": "1.23.16",
    "port": 6443,
    "enabled": true,
    "options": {
      "traefik": true,
      "flannel": true
    }

iguimaraes@isasih ~ % rdctl shutdown 
Shutting down.
iguimaraes@isasih ~ % rdctl start --kubernetes.version 1.27.2                                      
INFO[0000] About to launch /usr/bin/open -a /Applications/Rancher Desktop.app --args --kubernetes.version 1.27.2 ... 
```

### Expected Behavior

Rancher Desktop should throw an error dialog and prevent the application to start with a value other than the specified in the locked profile.

### Additional Information

[profile.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11854405/profile.txt)

### Rancher Desktop Version

1.9.0-19-g6ccc9ccb

### Rancher Desktop K8s Version

1.23.16

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5047 

At startup we don't know yet which versions of kubernetes are available. This just verifies we aren't trying to change a locked field via startup or `rdctl set`

### CODE REVIEW

File: background.ts [hunk 1]
```diff
@@ -952,20 +952,39 @@ function validateEarlySettings(cfg: settings.Settings, newSettings: RecursivePar
...
+    let clearVersionsAfterTesting = false;
+
+    if (newSettings.kubernetes?.version && this.settingsValidator.k8sVersions.length === 0) {
+      // If we're starting up (by running `rdctl start...`) we probably haven't loaded all the k8s versions yet.
+      // We don't want to verify the proposed version makes sense (if it doesn't, we'll assign the default version later).
+      // Here we just want to make sure that if we're changing the version to a different value from the current one,
+      // the field isn't locked.
+      let currentK8sVersions = (await k8smanager.kubeBackend.availableVersions).map(entry => entry.version.version);
+
+      if (currentK8sVersions.length === 0 || (currentK8sVersions.length === 1 && currentK8sVersions[0] === '0.0.0')) {
```
Comment (mook-as) [inline background.ts:971]: I don't understand the second part with `0.0.0.0`; I understand that you mentioned in one of the standups but there wasn't enough detail here (needs a comment pinpointing the cause, or better, eliminate it and whatever caused it).

File: pkg/rancher-desktop/config/commandLineOptions.ts [hunk 2]
```diff
@@ -115,13 +115,21 @@ export function updateFromCommandLine(cfg: Settings, lockedFields: LockedSetting
...
-  // If it can't find this version, it will silently move to the closest version.
-  // We'd have to add more code to report that.
-  // It isn't worth adding that code yet. It might never be needed.
-  const newSettingsForValidation = _.omit(newSettings, 'kubernetes.version');
-  const [needToUpdate, errors] = (new SettingsValidator()).validateSettings(cfg, newSettingsForValidation, lockedFields);
+  if (_.has(newSettings, 'kubernetes.version')) {
+    // RD hasn't loaded the supported k8s versions yet, so fake the list.
+    // If the field is locked, we don't need to know what it's locked to,
+    // just that the proposed version is different from the current version.
+    /// The current version doesn't have to be the locked version, but will be after processing ends.
```
Comment (mook-as) [inline pkg/rancher-desktop/config/commandLineOptions.ts:124]:
```suggestion
    // The current version doesn't have to be the locked version, but will be after processing ends.
```

File: pkg/rancher-desktop/config/commandLineOptions.ts [hunk 3]
```diff
@@ -115,13 +115,21 @@ export function updateFromCommandLine(cfg: Settings, lockedFields: LockedSetting
...
+    const limitedK8sVersionList: Array<string> = [newSettings.kubernetes?.version ?? ''];
+
+    if (cfg.kubernetes.version) {
+      limitedK8sVersionList.push(cfg.kubernetes.version);
+    }
+    settingsValidator.k8sVersions = limitedK8sVersionList;
```
Comment (mook-as) [inline pkg/rancher-desktop/config/commandLineOptions.ts:130]: This list may end up with the empty string in it; that seems like it would break assumptions (because the list is supposed to only have valid version numbers in it).

**Review by mook-as — CHANGES_REQUESTED** [review]

File: pkg/rancher-desktop/config/commandLineOptions.ts (hunk 2 above)
Comment (ericpromislow) [reply pkg/rancher-desktop/config/commandLineOptions.ts:124]: yes

File: background.ts (hunk 1 above)
Comment (ericpromislow) [reply background.ts:971]: I can't repro it so I'll get rid of it.

File: pkg/rancher-desktop/config/commandLineOptions.ts (hunk 3 above)
Comment (ericpromislow) [reply pkg/rancher-desktop/config/commandLineOptions.ts:130]: Found a simplification that prevents an empty string from getting there.

File: background.ts (hunk 1 above)
Comment (ericpromislow) [reply background.ts]: The "0.0.0" fake version comes from the mock server. If I set its `availableVersions` field to `[]` tests pass, and I don't need to special-case for `[SemVer('0.0.0')]`

File: background.ts [hunk 4]
```diff
@@ -952,20 +952,41 @@ function validateEarlySettings(cfg: settings.Settings, newSettings: RecursivePar
...
    */
   protected async validateSettings(existingSettings: settings.Settings, newSettings: RecursivePartial<settings.Settings>) {
-    if (this.k8sVersions.length === 0) {
-      this.k8sVersions = (await k8smanager.kubeBackend.availableVersions).map(entry => entry.version.version);
-      this.settingsValidator.k8sVersions = this.k8sVersions;
+    let clearVersionsAfterTesting = false;
+
+    if (newSettings.kubernetes?.version && this.settingsValidator.k8sVersions.length === 0) {
+      // If we're starting up (by running `rdctl start...`) we probably haven't loaded all the k8s versions yet.
+      // We don't want to verify the proposed version makes sense (if it doesn't, we'll assign the default version later).
```
Comment (mook-as) [inline background.ts:966]:
```suggestion
      // We don't want to verify if the proposed version makes sense (if it doesn't, we'll assign the default version later).
```

File: background.ts [hunk 5]
```diff
@@ -952,20 +952,41 @@ function validateEarlySettings(cfg: settings.Settings, newSettings: RecursivePar
...
+      // Here we just want to make sure that if we're changing the version to a different value from the current one,
+      // the field isn't locked.
+      //
```
Comment (mook-as) [inline background.ts:969]:
```suggestion
```

**Review by mook-as — APPROVED** [review]

**Review by mook-as — APPROVED** [review]

**Review by mook-as — APPROVED** [review]
