### PR TITLE
WSL-Helper: Force stop process as needed.

### LINKED ISSUE #1059: Toggling the WSL integration checkbox for ubuntu has no effect
### Rancher Desktop Version

dev->0.7.0

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Home

### What CPU architecture are you using?

x64

### Windows User Only

n/a

### Actual Behavior

With moby containers selected, I can run `sudo resources/linux/bin/docker images` in the Ubuntu WSL container whether or not the ubuntu integration box is checked. Same for `nerdctl -n k8s.io images`

At first I would get an error message:
```
exec: "wsl.exe" : executable file not found in $PATH
```
(remember , this is in the ubuntu WSL), but after about 20 seconds the command ran normally.

Note that I needed to 

### Steps to Reproduce

Start up RD on Windows.  Select the docker container engine, and enable the WSL integration.

Go into either a new or existing Ubuntu shell and run `sudo .../docker images`.  It should work.

Disable the integration.

Repeat the `docker images` command.

### Result

The command succeeds regardless of the state of the WSL integration.

### Expected Behavior

I would expect docker/nerdctl not to work when the integration is off.

### Additional Information

The integration checkbox does effectively control whether `kubectl` works -- when it's unchecked, the `.kube/config` file is removed.

### PR DESCRIPTION
**Pull request by mook-as**
It seems like killing the `wsl.exe` process (and therefore the controlling terminal) does not always send `SIGTERM` (or even `SIGHUP`) to the Linux-side process.  This PR implements an extra command on `wsl-helper` to manually find the process and terminate it, instead.

Also includes some fixups to debug logging, which was used to figure out what was going wrong…

Fixes #1059.

### CODE REVIEW

File: src/go/wsl-helper/pkg/process/kill_others.go [hunk 1]
```diff
@@ -15,36 +15,67 @@ import (
...
+func KillOthers(args ...string) error {
 	selfPid := fmt.Sprintf("%d", os.Getpid())
-	selfCmd, err := ioutil.ReadFile("/proc/self/cmdline")
+	selfFile, err := os.Readlink("/proc/self/exe")
 	if err != nil {
-		logrus.WithError(err).Error("could not read /proc/self/cmdline")
+		logrus.WithError(err).Error("could not read /proc/self/exe")
 		return err
 	}
+	var argsBytes []byte
```
Comment (ericpromislow) [inline src/go/wsl-helper/pkg/process/kill_others.go:26]: Could use a comment that the words in `/proc/*/cmdline` are null-byte separated

File: src/k8s-engine/wsl.ts [hunk 2]
```diff
@@ -688,10 +717,11 @@ export default class WSLBackend extends events.EventEmitter implements K8s.Kuber
       options = optionsOrArg;
     }
     try {
-      const stream = await Logging['wsl.exec'].fdStream;
+      const stream = options.logStream ?? await Logging['wsl.exec'].fdStream;
 
       // We need two separate calls so TypeScript can resolve the return values.
       if (options.capture) {
+        console.debug(`Capturing output: wsl.exe ${ args.join(' ') }`);
```
Comment (ericpromislow) [inline src/k8s-engine/wsl.ts:724]: Ahh, nice, we have `console.debug` now and don't have to worry about managing them as much.

**Review by ericpromislow — CHANGES_REQUESTED** [review]

**Comment by ericpromislow** [comment]
Got an error running this branch. The integrations page checkbox was disabled, with a message that

**Comment by mook-as** [comment]
> Got an error running this branch. The integrations page checkbox was disabled, with a message `Error: wsl.exe exited with code 11`

Ugh. That's a segfault (signal 11).

With some experimenting, it looks like WSL has a caching problem: if you modify the executable, sometimes it'll get confused.  I could reproduce this in _one_ of my WSL2 distros, but not if I rebuild the `wsl-helper` binary.  It went away after `wsl --shutdown`.  Running it under gdb claims it's around [early startup](https://github.com/golang/go/blob/go1.17.4/src/runtime/runtime1.go#L431), outside of our code.

This shouldn't be a problem in the field, given that users aren't going to be recompiling executables all the time :)

**Review by ericpromislow — DISMISSED** [review]
Works fine.

**Review by ericpromislow — CHANGES_REQUESTED** [review]
1. I realize I need more context on what the `BackgroundProcess`  class is for.

2. Why are there both `resources/linux/wsl-helper` and `resources/linux/bin/wsl-helper`? They're different sizes, and probably need different names.

3. I'm observing `wsl-helper kill` getting called about every 50 seconds when integration is on. Is this expected? If yes, why (so needs a comment somewhere). If not, that would be a bug.

**Comment by mook-as** [comment]
1. It is used to run a persistent background process on the Window side.  We don't have OpenRC on Windows, essentially.  We have a rd agent, plus the various proxy processes.
2. `resources/linux/bin/wsl-helper` should no longer exist; that was from a previous run.  This changed in #1080.  Please delete it and try again (it will no longer get built).
3. I'll go take a look and answer later; that's not expected at all — `wsl-helper kill` should get run when the proper Linux-side process disconnects, to ensure that things are properly dead (because sometimes when we kill the Windows side WSL-internal proxy process, the Linux side process stays alive).

**Comment by ericpromislow** [comment]
And in answer top https://github.com/rancher-sandbox/rancher-desktop/pull/1068#issuecomment-993878548, points 2 and 3 are both due to the presence of an older `wsl-helper` process running in the Ubuntu WSL that couldn't be deleted by the new branch because the path had changed.

**Review by ericpromislow — APPROVED** [review]
All issues I identified earlier today (2021-12-14) have been addressed.
