### PR TITLE
Close all sockets when closing the server

### LINKED ISSUE #469: The button state doesn't consistently change between "Forward" and "Cancel" in the Port Forwarding tab
Steps to reproduce: (This behavior is not consistent though. Sometimes the button state change happens without below issue)

On Windows machine, When I click on `Forward ` button under `Port Forwarding`, the port forwarding generally works.
At this state, If i press on `Cancel` button the button state doesn't change to `Forward` again. I have to switch to a different tab, say `Images` and come back to `Port Forwarding` tab to see the state change.

### PR DESCRIPTION
**Pull request by rak-phillip**
This resolves an issue where the Forward button under the Port Forwarding page would seemingly not switch between `Close` and `Forward` when attempting to close a port. 

### Background

The button would toggle back to `Forward`, it would just take upwards to 3 minutes when there was an active connection. `server.close()` is designed to behave this way and only ever closes after all connections are closed.

### Solution

We keep track of all sockets when creating a connection and destroy each socket after `server.close()` is invoked.  

closes #469 

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>

### CODE REVIEW

**Comment by rak-phillip** [comment]
Steps to reproduce are left in a comment for #469

1. Start the code on this branch with npm run dev and wait until everything is up.
2. Navigate to "Port Forwarding" tab.
3. Show kubernetes services by enabling the checkbox at the top.
4. Click the Forward button for traefik's web port.
5. Navigate to http://localhost:<port> in a browser.
6. Click the Cancel button on the same row.
7. Note how it does not change back to a Forward button.

**Comment by rak-phillip** [comment]
@mook-as @ericpromislow ready for review again after some testing and rework 🙂

Made an update so that we only destroy sockets for the given server that we're attempting to close. I considered working the sockets map into `ForwardingMap`, but I didn't feel that it conceptually fit..

**Review by ericpromislow — DISMISSED** [review]
LGTM

File: src/k8s-engine/client.ts [hunk 1]
```diff
@@ -199,6 +199,7 @@ export class KubeClient extends events.EventEmitter {
    * entry exists, then we want to set up port forwarding for it.
    */
   protected servers = new ForwardingMap();
+  protected sockets = new Map<string, net.Socket[]>();
```
Comment (mook-as) [inline src/k8s-engine/client.ts:202]: Please add a doc comment describing this (what is the format of the key?)

File: src/k8s-engine/client.ts [hunk 2]
```diff
@@ -378,6 +379,9 @@ export class KubeClient extends events.EventEmitter {
     return pod?.status?.phase === 'Running';
   }
 
+  private targetName =
+    (namespace: string, endpoint: string, port: number | string) => `${ namespace }/${ endpoint }:${ port }`
```
Comment (mook-as) [inline src/k8s-engine/client.ts:383]: Should have a doc comment for this too.

File: src/k8s-engine/client.ts [hunk 3]
```diff
@@ -518,11 +530,19 @@ export class KubeClient extends events.EventEmitter {
...
    */
   async cancelForwardPort(namespace: string, endpoint: string, port: number | string) {
+    const targetName = this.targetName(namespace, endpoint, port);
     const server = this.servers.get(namespace, endpoint, port);
 
     this.servers.delete(namespace, endpoint, port);
     if (server) {
-      await new Promise(resolve => server.close(resolve));
+      await new Promise((resolve) => {
+        server.close(resolve);
```
Comment (mook-as) [inline src/k8s-engine/client.ts:539]: Shouldn't this be at the end of the callback (so that we don't call `resolve` too early)?

Comment (rak-phillip) [reply src/k8s-engine/client.ts:539]: `server.close()` won't invoke the callback until all connections are closed, so we won't resolve early here. 

It's a common pattern pattern first call `server.close()` because this will stop accepting new connections before cleaning up sockets. In other words, there's the possibility that we would receive new connections after destroying sockets if we swapped the order.

**Review by mook-as — APPROVED** [review]
