### PR TITLE
Don't try to close k3s if k8s is disabled.

### LINKED ISSUE #2939: Can't shut down k3s when the lima instance is not running
I get a error when trying to shut down RD when kubernetes is disabled:
```
2022-09-19T20:51:40.222Z: > limactl shell --workdir=. 0 sudo /sbin/rc-service --ifstarted k3s stop
$ Error: /Users/ericp/workspace/rancher/desktop/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Users/ericp/workspace/rancher/desktop/dist/app/background.js:48125:27)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  stderr: 'time="2022-09-19T13:51:40-07:00" level=fatal msg="instance \\"0\\" is stopped, run `limactl start 0` to start the instance"\n',
  code: 1,
  command: [
    '/Users/ericp/workspace/rancher/desktop/resources/darwin/lima/bin/limactl',
    'shell',
    '--workdir=.',
    '0',
```

I was getting fatal errors that prevented the UI from closing when shutting down, but I can't repro that. The log message is reproducible, and there's no need for it.

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2939

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/backend/lima.ts [hunk 1]
```diff
@@ -1659,7 +1659,9 @@ CREDFWD_URL='http://${ hostIPAddr }:${ stateInfo.port }'
         const status = await this.status;
 
         if (defined(status) && status.status === 'Running') {
-          await this.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+          if (this.cfg?.enabled) {
+            await this.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+          }
```
Comment (mook-as) [inline src/backend/lima.ts:1664]: This part should be reverted — we always have the k3s service written to disk, just not always running.

File: src/backend/lima.ts [hunk 2]
```diff
@@ -2021,7 +2023,9 @@ class LimaKubernetesBackend extends events.EventEmitter implements K8s.Kubernete
   }
 
   async stop() {
-    await this.vm.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+    if (this.cfg?.enabled) {
+      await this.vm.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+    }
```
Comment (mook-as) [inline src/backend/lima.ts:2028]: Rather than checking if it's enabled, we should instead check if the VM is _running_, and only do this if it is.  If the VM is off, we should skip this even if we wanted k3s to be running.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/backend/lima.ts (hunk 1 above)
Comment (ericpromislow) [reply src/backend/lima.ts]: done

**Review by mook-as — APPROVED** [review]

File: src/backend/lima.ts [hunk 3]
```diff
@@ -2021,7 +2021,11 @@ class LimaKubernetesBackend extends events.EventEmitter implements K8s.Kubernete
   }
 
   async stop() {
-    await this.vm.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+    try {
+      await this.vm.execCommand({ root: true }, '/sbin/rc-service', '--ifstarted', 'k3s', 'stop');
+    } catch (ex) {
+      console.debug('k3s stop failed: ', ex);
```
Comment (mook-as) [inline src/backend/lima.ts:2027]: Surely this warrants a `console.error`?

**Review by mook-as — CHANGES_REQUESTED** [review]
We should still guard it based on VM state.

File: src/backend/lima.ts (hunk 3 above)
Comment (ericpromislow) [reply src/backend/lima.ts:2027]: I left it as a debug statement because the user probably won't even notice anything went wrong. But now that I know why this was failing CI, sure...

Comment (ericpromislow) [reply src/backend/lima.ts]: ok

**Review by mook-as — APPROVED** [review]
Eric convinced me that (for now at least) not trying to thread the VM state down here is the better option.
