### PR TITLE
Restart the backend after creating snapshot produces error

### LINKED ISSUE #5764: Rancher Desktop remains in stopped status
### Actual Behavior

The application remains in stopped status in case of errors from `snapshots` commands

### Steps to Reproduce

- close the main window
- create a snapshot using the CLI, use a name that already exists
- while the command is running and the VM is shutting down, open the main window
- once the VM is fully stopped, the command fails because of the duplicated name
- the app remains in a not consistent state

### Result

- logs folder is empty
- app status is stopped

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

OpenSUSE 15

### PR DESCRIPTION
**Pull request by adamkpickering**
Closes #5764.

Note that #5764 refers to an older version of the code. It is now impossible to reproduce the problem in the manner described, because we check the passed snapshot name before creating or restoring a snapshot. `main` now behaves as @torchiaf seems to expect in the description, except:
- The backend is not restarted when `manager.Create()` fails. This PR corrects this.
- The backend is not restarted when `manager.Restore()` fails. This would be impossible anyways, since we do a factory reset in this case. #5809 seems to be about this, so I've left this part as it is.

We may not want to make this change, but I'm going to create this PR in case we do.

### CODE REVIEW

File: src/go/rdctl/cmd/snapshot.go [hunk 1]
```diff
@@ -72,6 +72,10 @@ func wrapSnapshotOperation(cmd *cobra.Command, appPaths paths.Paths, resetOnFail
 	if err := wrappedFunction(); err != nil {
 		if resetOnFailure {
 			factoryreset.DeleteData(appPaths, true)
+		} else {
+			if err := ensureBackendStarted(); err != nil {
+				snapshotErrors = append(snapshotErrors, err)
```
Comment (ericpromislow) [inline src/go/rdctl/cmd/snapshot.go:77]: It looks straightforward, but you're losing the error from the call to `wrappedFunction()`. If we want to report all the errors (and why would we not), the code needs to be more like this:

```
	if err := wrappedFunction(); err != nil {
		if resetOnFailure {
			factoryreset.DeleteData(appPaths, true)
		} else {
			snapshotErrors = append(snapshotErrors, err)
			err = ensureBackendStarted()
		}
		return err
	}
```

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Approach looks correct, but this code is potentially losing an error if both the wrappedFunction and `ensureBackendStarted` fail.

File: src/go/rdctl/cmd/snapshot.go (hunk 1 above)
Comment (jandubois) [reply src/go/rdctl/cmd/snapshot.go:77]: Do you really want to return `nil` if `ensureBackendStarted()` returned nil?

Or should the code be:

```golang
	if err := wrappedFunction(); err != nil {
		if resetOnFailure {
			factoryreset.DeleteData(appPaths, true)
		} else {
			err2 := ensureBackendStarted()
			if err2 != nil {
				snapshotErrors = append(snapshotErrors, err)
				err = err2
			}
		}
		return err
	}
```

This awkwardness comes from the fact that you are returning the last error separately from all the other errors instead of returning an `[]error` list.


I'm still confused why you are not restarting the app after the factory reset?

Comment (adamkpickering) [reply src/go/rdctl/cmd/snapshot.go:77]: > but you're losing the error from the call to `wrappedFunction()`

Comment (jandubois) [reply src/go/rdctl/cmd/snapshot.go:77]: > > but you're losing the error from the call to `wrappedFunction()`

Who is? That is the point of my version: I save the error from `wrappedFunction` in `snapshotErrors`, but only when `ensureBackendStarted()` returns non-nil. Otherwise the error from the wrapped function remains in `err`.

Comment (jandubois) [reply src/go/rdctl/cmd/snapshot.go:77]: > Or am I deluded???

No, I think you are right. I just assumed that the return value was the last error that occurred, while you always return the error from the wrapped function.

Which might actually make more sense; idk. As I wrote, the error handling in this function feels rather unconventional to me.

Comment (ericpromislow) [reply src/go/rdctl/cmd/snapshot.go:77]: The weird part is that there's a global `snapshotErrors` array that tracks encountered errors and reports them at the very end. If `wrapSnapshotOperation` returns `nil` but `len(snapshotErrors) > 0` we'll still finish in an error state

**Review by ericpromislow — APPROVED** [review]
LGTM (but it was partly my suggestion...)

**Review by jandubois — APPROVED** [review]
LGTM
