### PR TITLE
Capture and report any failure attempting to stop k3s in main backend class.

### LINKED ISSUE #2939: Can't shut down k3s when the lima instance is not running
I get a error when trying to shut down RD when kubernetes is disabled:
```
2022-09-19T20:51:40.222Z: > limactl shell --workdir=. 0 sudo /sbin/rc-service --ifstarted k3s stop
$ Error: /Users/ericp/workspace/rancher/desktop/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Users/ericp/workspace/rancher/desktop/dist/app/background.js:48125:27)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  stderr: 'time="2022-09-19T13:51:40-07:00" level=fatal msg="instance \\"0\\" is stopped, run `limactl start 0` to start the instance"\n',
  code: 1,
  command: [
    '/Users/ericp/workspace/rancher/desktop/resources/darwin/lima/bin/limactl',
    'shell',
    '--workdir=.',
    '0',
```

I was getting fatal errors that prevented the UI from closing when shutting down, but I can't repro that. The log message is reproducible, and there's no need for it.

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2939

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
Surely if the machine is not running, the _other_ commands would also throw?

(Also, this has a guard for the machine being running already… )

File: src/backend/lima.ts [hunk 1]
```diff
@@ -290,7 +290,7 @@ export default class LimaBackend extends events.EventEmitter implements VMBacken
     case State.STOPPED:
     case State.ERROR:
     case State.DISABLED:
-      this.kubeBackend.stop();
+      await this.kubeBackend.stop();
```
Comment (mook-as) [inline src/backend/lima.ts:293]: This is not an `async` function.

**Review by mook-as — CHANGES_REQUESTED** [review]

**Review by mook-as — APPROVED** [review]
