### PR TITLE
Emit event when an unsupported extension is uninstalled

### LINKED ISSUE #5428: UI of incompatible extension remains interactive
### Actual Behavior

Once an extension is installed through a compatible container engine and the user switches it to an incompatible one, despite the extension is uninstalled, its UI remains interactive in the application main window.

### Steps to Reproduce

1. Start Rancher Desktop with `containerd`
2. Install the following extensions: Harpoon, Intersystems, Kubescape and Excalidraw
3. Open the Excalidraw 
4. Interact with the UI
5. Go to `Preferences > Container Engine` and switch to `dockerd`
6. Run `rdctl extension ls` to verify the incompatible extension Excalidraw is uninstalled
7. Interact with the UI of the incompatible extension in the main window

### Result

The UI of the incompatible extension remains interactive in the application main window.

excalidraw-dockerd

### Expected Behavior

The UI of an incompatible extension must disappear right after switching to an incompatible container engine

### Additional Information

_No response_

### Rancher Desktop Version

1.9.1-623-g313754b3

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by rak-phillip**
This introduces a new main event that can be used to relay to the UI that an extension has been uninstalled because it is unsupported after changing container engines.

closes #5428

### CODE REVIEW

File: pkg/rancher-desktop/main/mainEvents.ts [hunk 1]
```diff
@@ -100,6 +100,12 @@ interface MainEventNames {
    */
   'diagnostics-trigger'(id: string): DiagnosticsCheckerResult | undefined;
 
+  /**
+   * Emitted when an extension is uninstalled via the extension manager.
+   * @param id The ID of the extension that was uninstalled.
+   */
+  'extensions/ui/uninstall'(id: string): void;
```
Comment (rak-phillip) [inline pkg/rancher-desktop/main/mainEvents.ts:107]: I attempted to keep this in line with other ipc events from `electron-ipc.d.ts`, but I'm open to renaming if we think there's something better.

**Review by mook-as — APPROVED** [review]
