### PR TITLE
Ensure main window isn't opened while processing first-run dialog.

### LINKED ISSUE #2772: clicking on app icon during first run, opens main window
### Actual Behavior

clicking on RD  icon during first run, opens main window along with first run settings pop up window

### Steps to Reproduce

1. Factory reset
2. Open app
3. click on App Icon 

### Result

Screen Shot 2022-08-17 at 3 42 03 PM

### Expected Behavior

1.  Only first run options window should open up
2. Main window should not open up until a selection has been made by the user

### Additional Information

_No response_

### Rancher Desktop Version

1.5.0-13-g3072e87d

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2772

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: background.ts [hunk 1]
```diff
@@ -49,6 +49,7 @@ const k8smanager = newK8sManager();
 const diagnostics: DiagnosticsManager = new DiagnosticsManager();
 
 let cfg: settings.Settings;
+let inFirstRun = false;
```
Comment (jandubois) [inline background.ts:52]: Shouldn't this default to `true` on a first-run so you don't have a race condition?

```suggestion
let inFirstRun = settings.isFirstRun();
```

File: background.ts [hunk 2]
```diff
@@ -219,7 +220,12 @@ async function doFirstRun() {
   if (!settings.isFirstRun()) {
```
Comment (jandubois) [inline background.ts:220]: This then becomes

```suggestion
  if (!inFirstRun) {
```

File: background.ts [hunk 3]
```diff
@@ -219,7 +220,12 @@ async function doFirstRun() {
...
     return;
   }
-  await window.openFirstRun();
+  try {
+    inFirstRun = true;
```
Comment (jandubois) [inline background.ts:224]: And this line can be removed:
```suggestion
```

**Review by jandubois — CHANGES_REQUESTED** [review]
I think there is a race condition

File: background.ts (hunk 1 above)
Comment (ericpromislow) [reply background.ts:52]: Disagree. Those are two different things. `settings.isFirstRun()` means that we need to put up the first-run dialog. `inFirstRun` is true when the first-run window is up.

File: background.ts (hunk 3 above)
Comment (ericpromislow) [reply background.ts:224]: I renamed a method to clarify the two concepts.

File: background.ts (hunk 1 above)
Comment (jandubois) [reply background.ts:52]: So how do you prevent the main window from being raised in the time after the app is launched, but before the first-run dialog is displayed? E.g. if somebody tripple-clicks on the dock icon to start the app.

File: background.ts (hunk 3 above)
Comment (jandubois) [reply background.ts:224]: Yes, but it doesn't address the race condition: `inFirstRun` is still `false` until `doFirstRun()` is called. When you get the "Activate" request before you have a chance to start `doFirstRun` you will still raise the main window.

Comment (ericpromislow) [reply background.ts:224]: That's a good point.

File: background.ts [hunk 4]
```diff
@@ -216,10 +217,16 @@ function installDevtools() {
...
+
     return;
   }
-  await window.openFirstRun();
+  try {
+    await window.openFirstRun();
+  } finally {
+    waitForFirstRunCompletion = false;
+  }
 }
```
Comment (jandubois) [inline background.ts:230]: Simpler version:

```
async function doFirstRun() {
  if (settings.firstRunNeeded()) {
    try {
      await window.openFirstRun();
    }
  }
  waitForFirstRunCompletion = false;
}

Comment (jandubois) [reply background.ts:224]: FWIW, I would `s/FirstRun/FirstRunDialog`:

```ts
async function doFirstRunDialog() {
  if (settings.firstRunDialogNeeded()) {
    try {
      await window.openFirstRunDialog();
    }
  }
  waitForFirstRunDialogCompletion = false;
}
```

Because to me the "first run" refers to the app as a while, and not just the initial dialog.

File: background.ts [hunk 5]
```diff
@@ -337,14 +338,19 @@ Electron.app.on('window-all-closed', () => {
...
+  if (os.platform() === 'linux' && !settings.firstRunDialogNeeded()) {
     Electron.app.quit();
   }
 });
 
 Electron.app.on('activate', async() => {
   // On macOS it's common to re-create a window in the app when the
   // dock icon is clicked and there are no other windows open.
+  if (waitForFirstRunDialogCompletion) {
+    console.log('Still processing the first-run dialog: not opening main window');
```
Comment (mook-as) [inline background.ts:350]: It make be a good idea to call `window.restoreWindow` here, in case the user lost it?

**Review by jandubois — APPROVED** [review]
Thanks, LGTM and works as expected (tested via `npm run dev`).

**Comment by jandubois** [comment]
There is still one weird behaviour left; not sure if it is intentional: you can just close the first-run dialog (via the little red dot in the top left corner on macOS), and then the main Window appears with a modal dialog:

Screen Shot 2022-09-15 at 5 23 06 PM

So I guess it accepted the default settings for Kubernetes, but not for `PATH` configuration. Does this make sense?

If it doesn't, then it should probably a separate issue though.

**Comment by jandubois** [comment]
Adding to the weirdness is that the first-run dialog does not disable the "Close" button on the top left, but doesn't have a "Cancel" button.

Screen Shot 2022-09-15 at 5 29 31 PM

I'll create a new issue for sorting this out; I don't think it should affect merging this PR.

File: background.ts (hunk 5 above)
Comment (jandubois) [reply background.ts:350]: Not sure what situation you are talking about here; clicking on the dock icon will restore the first-run dialog if it had been hidden behind other windows, or using either the yellow dot, or ⌥-Click on the dock icon.

Comment (ericpromislow) [reply background.ts:350]: This is getting to be too extreme an edge case. If the user lost the first-run dialog, they can rerun RD and change the default settings.
