### PR TITLE
Address two particular e2e failures

### LINKED ISSUE #4988: Fix E2E flakiness
### Actual Behavior

Our current E2E tests still fail quite regularly but a rerun seems to work. We should take a look again at our tests; we have a series of waits and other timing parameters to help allow for various components to come up in a timely fashion but maybe we need to fix problems before extending timeouts.

### Steps to Reproduce

Run a build

### Result

Fails usually on the E2E upon first run; second run usually works fine.

### Expected Behavior

E2E passes on first run.

### Additional Information

_No response_

### Rancher Desktop Version

1.9

### Rancher Desktop K8s Version

any

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Github runner

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #4988

The first is sometimes the postinstall process times out. Increased from 45 to 60 minutes in `.cirrus.yml`

The other problem is that when an `rdctl` command causes a VM-reset in the UI, the test code needs to be in sync
with the state of the UI. The solution here is to realize that it needs to spend a few seconds actually shutting down 
the current services and VM, giving the e2e code enough time to wait for when the VM is restarted. Yes, technically it's still a race condition, but this means a delay of many seconds between two synchronous lines of JS code, which seems unlikely.

### CODE REVIEW

File: e2e/utils/TestUtils.ts [hunk 1]
```diff
@@ -254,6 +254,28 @@ export async function tool(tool: string, ...args: string[]): Promise<string> {
...
+    const caption: string = await progressBar.textContent() ?? '';
+
+    if (caption.startsWith('Starting virtual machine')) {
+      console.log(`Restart detected.`);
+      break;
+    }
+    const nowTime = new Date().valueOf();
+
+    if (nowTime > endTime) {
+      break;
```
Comment (adamkpickering) [inline e2e/utils/TestUtils.ts:273]: IMO we should throw an error here saying something like "timed out waiting for VM startup to start".

**Review by adamkpickering — CHANGES_REQUESTED** [review]
Looks good, just one comment.

File: e2e/utils/TestUtils.ts (hunk 1 above)
Comment (ericpromislow) [reply e2e/utils/TestUtils.ts:273]: good idea

**Review by adamkpickering — APPROVED** [review]
