### PR TITLE
Start the diagnostics backend.

### LINKED ISSUE #2655: Define the `diagnostics` object and create a couple sample checks (without fix actions for now)
When Rancher Desktop starts up, it will create a `diagnostics` object that contains all the checks defined in the app.

The set of diagnostics will depend on the current configuration. E.g. Kubernetes diagnostics will/can not be run if Kubernetes has been disabled. Therefore diagnostics must be refreshed whenever new preference settings have been applied.

Some checks will only be performed when other checks have passed. E.g. we will only check if the bundled `kubectl` is first on the `PATH` if the `~/.rd/bin` directory is included. So if this pass fails, then fixing it (adding `~/.rd/bin` to the end of the `PATH`) may enable a bunch of additional checks that now may show as failed.

Some checks will still be executed, even when it is known that they will fail with the current configuration. E.g. when administrative access has been denied, the VM will not have a routable IP address. We want to still display a failed check, just in case the user was not aware of this connection. They can then mute the check, if this matches their expectation.

The diagnostics object will only include checks that have been executed, so have a "pass" or "fail" state.

The user can "mute" specific checks, so they will not generate notifications and not be shown by default.

Checks are grouped in categories. These are simply headlines in the diagnostics panel and have no further importance.

Each check has a unique and persistent id. It is used to "mute" a check, and it will not change if the check is moved around, or if strings are localized.

We may have many variants of the same check, e.g. `BASH_KUBECTL_FOUND`, `ZSH_KUBECTL_FOUND`, etc. which will check if the bundled `kubectl` binary is found on the `PATH` in the respective shell. So even if the user mutes the check for one shell, and then switches shells, they will see the alert again for the new shell.

```yaml
diagnostics:
  last_update: timestamp
  categories:
  - title: "PATH settings"
    checks:
    - id: BASH_RDBIN_ON_PATH
      documentation: https://rancherdesktop.io/diagnostics/path#rdbin
      description: "The ~/.rd/bin directory has not been added to the PATH, so commandline utilities are not configured in your bash shell"
      passed: false
      muted: false
      fixes:
      - description: "You have selected manual PATH configuration, you can let Rancher Desktop automatically configure it."
        action: ...  # A callback that would turn on automatic configuration
```

The description for each check will be different for pass/fail state, and should be as specific as possible. So don't use:

> Pass: The RD helm command was found on the PATH.
> Fail: The RD helm command was not found on the PATH.

Instead use:

> Pass: The ~/.rd/bin/helm command was found first on the PATH of the bash shell.
> Fail: The /usr/local/bin/helm file is hiding the RD ~/.rd/bin/helm file on the PATH of the bash shell.

Include as much detail as possible. E.g. the user may have configured `/bin/bash` inside `/etc/passwd`, but is actually using the `fish` shell. So reading the message may remind them about this.

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #2655

Includes spec and rdctl tests for the HTTP API.

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/main/commandServer/httpCommandServer.ts [hunk 1]
```diff
@@ -176,6 +181,88 @@ export class HttpCommandServer {
     return undefined;
   }
 
+  protected diagnosticCategories(request: http.IncomingMessage, response: http.ServerResponse, context: commandContext): Promise<void> {
+    const settings = this.commandWorker.getDiagnosticCategories(context);
+
+    if (settings) {
+      console.debug('diagnosticCategories: succeeded 200');
+      response.writeHead(200, { 'Content-Type': 'text/plain' });
```
Comment (mook-as) [inline src/main/commandServer/httpCommandServer.ts:189]: Since this mainly for API use, shouldn't this return `application/json` of some sort? Or depend on the `Accept:` header?

Actually, I think the OpenAPI spec specifies `application/json`…

File: src/assets/specs/command-api.yaml [hunk 2]
```diff
@@ -112,6 +112,58 @@ paths:
             "text/plain":
               schema:
                 type: string
+
+  /v0/diagnostic_categories:
```
Comment (mook-as) [inline src/assets/specs/command-api.yaml:116]: Do we need separate endpoints here?

My understand is that we basically need three things:
1. A thing to list all diagnostics (and their categories), possibly in a fixed order.
2. A thing to run (possibly a subset of) the diagnostics, returning results which can include more detailed textual descriptions.
3. Possibly a thing to configure diagnostics (mute some of them, etc.)

Given that, have a separate endpoint for categories and ids seems unnecessary?

File: src/main/commandServer/httpCommandServer.ts [hunk 3]
```diff
@@ -176,6 +181,88 @@ export class HttpCommandServer {
...
+
+  protected diagnosticIDsForCategory(request: http.IncomingMessage, response: http.ServerResponse, context: commandContext): Promise<void> {
+    const url = new URL(`http://${ request.url }`);
+    const searchParams = url.searchParams;
+    const category = searchParams.get('category');
+
+    if (!category) {
+      console.debug('diagnostic_ids: failed 400');
+      response.writeHead(400, { 'Content-Type': 'text/plain' });
+      response.write('diagnostic_ids: no  category specified');
```
Comment (mook-as) [inline src/main/commandServer/httpCommandServer.ts:208]:
```suggestion
      response.write('diagnostic_ids: no category specified');
```
Should this be returned in JSON?

File: src/main/commandServer/httpCommandServer.ts [hunk 4]
```diff
@@ -176,6 +181,88 @@ export class HttpCommandServer {
...
+
+      return Promise.resolve();
+    }
+    const categories = this.commandWorker.getDiagnosticIdsByCategory(category, context);
+
+    if (categories) {
+      console.debug('diagnostic_ids: succeeded 200');
+      response.writeHead(200, { 'Content-Type': 'text/plain' });
```
Comment (mook-as) [inline src/main/commandServer/httpCommandServer.ts:216]: This should be `application/json` of some sort.

File: src/assets/specs/command-api.yaml [hunk 5]
```diff
@@ -112,6 +112,58 @@ paths:
...
+                type: array
+
+  /v0/diagnostic_check:
+    get:
+      operationId: diagnosticForCategoryAndID
+      summary: >-
+        Return the check for the given category and checkID, or 404.
+      parameters:
+        - in: query
+          name: category
```
Comment (mook-as) [inline src/assets/specs/command-api.yaml:155]: Is the category necessary? Presumably the id would be unique across all categories?

File: src/assets/specs/command-api.yaml [hunk 6]
```diff
@@ -112,6 +112,58 @@ paths:
...
+        - in: query
+          name: checkID
```
Comment (mook-as) [inline src/assets/specs/command-api.yaml:157]: Would it make sense to take a collection of diagnostic IDs (to run multiple at once)? Or some way to run all of them?

File: src/main/diagnostics/__tests__/diagnostics.spec.ts [hunk 7]
```diff
@@ -0,0 +1,67 @@
+import yaml from 'yaml';
+
+import { Diagnostics } from '../diagnostics';
+
+describe(Diagnostics, () => {
+  const diagnosticsTable = `
```
Comment (mook-as) [inline src/main/diagnostics/__tests__/diagnostics.spec.ts:6]: This is so going to be out of date soon. Can we just read the file out of `assets/` instead?
(Otherwise, Jest has support for [snapshot testing](https://jestjs.io/docs/snapshot-testing).)

File: src/main/diagnostics/__tests__/diagnostics.spec.ts [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+      checks:
+        - id: CONNECTED_TO_INTERNET
+          documentation: path#connected_to_internet
+          description: "The application cannot reach the general internet for updated kubernetes versions and other components, but can still operate."
+          mute: false
+`;
+  const diagnostics = new Diagnostics(yaml.parse(diagnosticsTable).diagnostics);
+
+  test('it finds the categories', () => {
+    expect(diagnostics.getCategoryNames()).toMatchObject(['Utilities', 'Networking']);
```
Comment (mook-as) [inline src/main/diagnostics/__tests__/diagnostics.spec.ts:34]: Using `toMatchObject` here seems odd (it checks that each item matches the given one, _in order_); did you intend to use [`expect.arrayContaining`](https://jestjs.io/docs/expect#expectarraycontainingarray)? Or pull in `jest-extended` and use [`toIncludeSameMemebers`](https://www.npmjs.com/package/jest-extended#toincludesamemembersmembers)?

This applies to other uses of `toMatchObject` as well.

File: src/main/diagnostics/__tests__/diagnostics.spec.ts [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+  test('it finds the IDs', () => {
+    expect(diagnostics.getIdsForCategory('Utilities')).toMatchObject(['RD_BIN_IN_BASH_PATH', 'RD_BIN_SYMLINKS']);
+    expect(diagnostics.getIdsForCategory('Networking')).toMatchObject(['CONNECTED_TO_INTERNET']);
+    expect(diagnostics.getIdsForCategory('Tennessee Tuxedo')).toBeUndefined();
+  });
+
+  test('it finds the checks', () => {
+    expect(diagnostics.getCheckByID('Chummily', 'CONNECTED_TO_INTERNET')).toBeUndefined();
+    expect(diagnostics.getCheckByID('Utilities', 'gallop the friendly purple')).toBeUndefined();
+    expect(diagnostics.getCheckByID('Utilities', 'RD_BIN_IN_BASH_PATH')).toMatchObject({
```
Comment (mook-as) [inline src/main/diagnostics/__tests__/diagnostics.spec.ts:46]: Rather than hard coding it, would pulling it from `diagnostics` (the result of parsing that blob of YAML) work?

File: src/main/diagnostics/diagnostics.ts [hunk 10]
```diff
@@ -0,0 +1,48 @@
+import yaml from 'yaml';
+
+import DIAGNOSTICS_TABLE from '@/assets/diagnostics.yaml';
+
+type DiagnosticsFix = {
+  fixes: Record<'description', string>
```
Comment (mook-as) [inline src/main/diagnostics/diagnostics.ts:6]:
```suggestion
  fixes: { description: string }
```

File: src/main/diagnostics/diagnostics.ts [hunk 11]
```diff
@@ -0,0 +1,48 @@
...
+
+type DiagnosticsCheck = {
+  id: string,
+  documentation: string,
+  description: string,
+  mute: boolean,
+  fixes: DiagnosticsFix,
+};
+
+type DiagnosticsCategories = {
```
Comment (mook-as) [inline src/main/diagnostics/diagnostics.ts:17]: Does this need to be an independent type? It's only used once, and can easily be defined inline instead.

(I find inline to be slightly easier to read, given that the structures involved are so small.)

File: src/main/diagnostics/diagnostics.ts [hunk 12]
```diff
@@ -0,0 +1,48 @@
+import yaml from 'yaml';
+
+import DIAGNOSTICS_TABLE from '@/assets/diagnostics.yaml';
+
+type DiagnosticsFix = {
```
Comment (mook-as) [inline src/main/diagnostics/diagnostics.ts:5]: Does `DiagnosticsFix` need to be its own type?

File: src/main/diagnostics/diagnostics.ts [hunk 13]
```diff
@@ -0,0 +1,48 @@
+import yaml from 'yaml';
```
Comment (mook-as) [inline src/main/diagnostics/diagnostics.ts:1]: This import appears to be unused. That would actually be caught by lint now (pending rebase) :)

File: src/main/diagnostics/diagnostics.ts [hunk 14]
```diff
@@ -0,0 +1,48 @@
...
+  checksByCategory: Record<string, Array<DiagnosticsCheck>> = {};
+  constructor(diagnosticsTable: DiagnosticsType|undefined = undefined) {
+    this.diagnostics = diagnosticsTable || DIAGNOSTICS_TABLE.diagnostics;
+    for (const category of this.diagnostics.categories) {
+      this.checksByCategory[category.title] = category.checks;
+    }
+  }
+
+  getCategoryNames() {
+    return Object.keys(this.checksByCategory);
```
Comment (mook-as) [inline src/main/diagnostics/diagnostics.ts:38]: This means that the category names are not actually sorted, right? Should that be documented? (A JSDoc for all the public methods would be nice for details like this.)

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/assets/diagnostics.yaml [hunk 15]
```diff
@@ -0,0 +1,28 @@
...
+  # Format: output from `date -u -Iminutes`
+  # or in JS:  new Date().toISOString()
+  # these differ, but are both parsable
+  last_update: 2022-08-15T16:00+00:00
+  categories:
+    - title: Utilities
+      checks:
+        - id: RD_BIN_IN_BASH_PATH
+          documentation: path#rd_bin_bash
+          description: "The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your bash shell."
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/diagnostics.yaml:11]: From the description of issue #2655: 
```
We may have many variants of the same check, e.g. BASH_KUBECTL_FOUND, ZSH_KUBECTL_FOUND, etc. which will check if the bundled kubectl binary is found on the PATH in the respective shell. So even if the user mutes the check for one shell, and then switches shells, they will see the alert again for the new shell.
```

File: src/assets/diagnostics.yaml [hunk 16]
```diff
@@ -0,0 +1,28 @@
...
+          mute: false
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/diagnostics.yaml:12]: > The user can "mute" specific checks, so they will not generate notifications and not be shown by default.

Initially, nothing is muted. But we'll need a separate store, similar to `settings.json` that tracks the actual user's preferences. Not worked out yet.

File: src/assets/diagnostics.yaml [hunk 17]
```diff
@@ -0,0 +1,28 @@
...
+          fixes:
+            description: "You have selected manual PATH configuration, you can let Rancher Desktop automatically configure it."
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/diagnostics.yaml:14]: Seems like overkill. When there's more than one way to fix a problem, we can rely on the text to convey that.

File: src/assets/specs/command-api.yaml [hunk 18]
```diff
@@ -112,6 +112,58 @@ paths:
             "text/plain":
               schema:
                 type: string
+
+  /v0/diagnostic_categories:
+    get:
+      operationId: diagnosticCategories
+      summary: >-
+        Return a list of the category names for the Diagnostics component. Takes no parameters
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:120]: ok

File: src/main/diagnostics/diagnostics.ts (hunk 11 above)
Comment (ericpromislow) [reply src/main/diagnostics/diagnostics.ts:17]: I prefer naming things when defining a non-trivial taxonomy, even the small ones. And this thing is in flux anyway.

File: src/main/diagnostics/diagnostics.ts (hunk 12 above)
Comment (ericpromislow) [reply src/main/diagnostics/diagnostics.ts:5]: Yes, because more fields are likely to appear. For example, and ID that can be used to execute a function to try to fix the problem.

File: src/main/diagnostics/diagnostics.ts (hunk 13 above)
Comment (ericpromislow) [reply src/main/diagnostics/diagnostics.ts:1]: Yes, for some reason I forgot how to use yaml in node.js.

File: src/main/diagnostics/diagnostics.ts (hunk 14 above)
Comment (ericpromislow) [reply src/main/diagnostics/diagnostics.ts:38]: jsdoc added. I'm not sure whether this function should sort the names, or leave that to the caller. So putting that off for now (remember there's more work to do, this item is to get the stakes in the ground, although we do need to get the right stakes in the right spots).

File: src/assets/specs/command-api.yaml [hunk 19]
```diff
@@ -112,6 +112,58 @@ paths:
...
+          content:
+            "application/json":
+              schema:
+                type: array
+
+  /v0/diagnostic_ids:
+    get:
+      operationId: diagnosticIDsForCategory
+      summary: >-
+        Return a list of the check IDs for the Diagnostics category, or 404 if there is no such `category`. Specifying an
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:134]: done

File: src/assets/specs/command-api.yaml [hunk 20]
```diff
@@ -112,6 +112,58 @@ paths:
...
+        exiting category with no checks will return status code 200 and an empty array.
+      parameters:
+        - in: query
+          name: category
+      responses:
+        '200':
+          description: >-
+            A list of the check IDs for the specified category, or 404.
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:142]: Right... Added.

File: src/assets/specs/command-api.yaml [hunk 21]
```diff
@@ -112,6 +112,58 @@ paths:
...
+          content:
+            "application/json":
+              schema:
+                type: array
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:146]: ok

File: src/main/commandServer/httpCommandServer.ts [hunk 22]
```diff
@@ -47,7 +47,12 @@ export class HttpCommandServer {
 
   protected dispatchTable: Record<string, Record<string, Record<string, DispatchFunctionType>>> = {
     v0: {
-      GET: { settings: this.listSettings },
+      GET: {
+        settings:              this.listSettings,
+        diagnostic_categories: this.diagnosticCategories,
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/main/commandServer/httpCommandServer.ts:52]: Not right now -- for now it's single-level under a version string.

File: src/main/commandServer/httpCommandServer.ts (hunk 1 above)
Comment (ericpromislow) [reply src/main/commandServer/httpCommandServer.ts:189]: I believe we had this discussion earlier, and `text/plain` is ok. So far, none of the clients seem to be depending on it.

File: src/assets/specs/command-api.yaml (hunk 2 above)
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:116]: Right now I'm thinking about the needs of the UI just to get started. If the UI is going to display diags by category first, it would be helpful to get the categories.

And I rules out an endpoint to get all the diagnostics in one call because we might end up with a lot of them and then we have pagination issues.

This might change later, but for now I think it solves the current problem.

File: src/main/commandServer/httpCommandServer.ts (hunk 3 above)
Comment (ericpromislow) [reply src/main/commandServer/httpCommandServer.ts:208]: Extra space removed.

You get the string `diagnostic_ids: no category specified` written to stderr and a JSON payload of `{ "message": "400 Bad Request" }' written to stdout.

File: src/assets/specs/command-api.yaml (hunk 5 above)
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:155]: It probably can be dropped, and I'd have to verify that all IDs are unique, but for now I still want the hierarchy (for ease of use from the UI, as explained above).

File: src/assets/specs/command-api.yaml (hunk 6 above)
Comment (ericpromislow) [reply src/assets/specs/command-api.yaml:157]: Later optimization. The `url.searchParams` API supports that.

File: src/main/diagnostics/__tests__/diagnostics.spec.ts (hunk 7 above)
Comment (ericpromislow) [reply src/main/diagnostics/__tests__/diagnostics.spec.ts:6]: No, I copied the YAML file into the test with the idea that we don't have to update the sample code in the test. Comment added.

File: src/main/diagnostics/__tests__/diagnostics.spec.ts (hunk 8 above)
Comment (ericpromislow) [reply src/main/diagnostics/__tests__/diagnostics.spec.ts:34]: Done

File: src/main/diagnostics/__tests__/diagnostics.spec.ts (hunk 9 above)
Comment (ericpromislow) [reply src/main/diagnostics/__tests__/diagnostics.spec.ts:46]: See above -- I just wanted to have a small bit of YAML I can rely on to test the code. If we add different kinds of data to the main YAML file, I'll update the test table here.

File: src/main/diagnostics/diagnostics.ts (hunk 10 above)
Comment (ericpromislow) [reply src/main/diagnostics/diagnostics.ts:6]: thx

File: src/main/commandServer/httpCommandServer.ts (hunk 4 above)
Comment (ericpromislow) [reply src/main/commandServer/httpCommandServer.ts:216]: Again, I haven't seen a need for this yet

File: src/assets/diagnostics.yaml [hunk 23]
```diff
@@ -0,0 +1,28 @@
+diagnostics:
```
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/diagnostics.yaml:1]: It's simple enough, and I'm not planning on generating code with it, that I don't think we need one. At least not now.

File: src/assets/diagnostics.yaml (hunk 16 above)
[the remark this answers is not in the document]
Comment (mook-as) [reply src/assets/diagnostics.yaml:12]: Yes, the user can mute things, but it would never be relevant for the hard-coded initial state. (We'll need to store the mute-ness elsewhere somehow, but we can't write into the bundled YAML file.)

File: src/assets/diagnostics.yaml (hunk 17 above)
[the remark this answers is not in the document]
Comment (mook-as) [reply src/assets/diagnostics.yaml:14]: I thought we were going to have buttons for alternatives?

Also, if we're _not_ having multiple items, then the `description` key shouldn't exist… (and `fixes` shouldn't be plural)

File: src/main/commandServer/httpCommandServer.ts (hunk 1 above)
Comment (mook-as) [reply src/main/commandServer/httpCommandServer.ts:189]: Then please fix the OpenAPI spec to align the two.
(I believe we have no clients because the API isn't available — for example see https://github.com/rancher-sandbox/rancher-desktop/pull/2688#discussion_r941785853)

File: src/assets/specs/command-api.yaml (hunk 2 above)
Comment (mook-as) [reply src/assets/specs/command-api.yaml:116]: While the UI will be group by categories, it still needs all the diagnostics in one go (since it's not going to render it as collapsed categories, and only fetch the full list on expanding), right?

I think designing for pagination is overkill (because the _user_ still needs to be able to look at the list), but we'll see how the UI ends up looking before changing this I guess.

File: src/main/commandServer/httpCommandServer.ts (hunk 3 above)
Comment (mook-as) [reply src/main/commandServer/httpCommandServer.ts]: I'm confused: it says `response.write(<non-JSON string>);`, so the other end of the HTTP connection sees plain text?

(Leaving this one resolved, but please still update either this or the OpenAPI spec — the spec claims JSON, but this implements `text/plain`)

File: src/main/diagnostics/__tests__/diagnostics.spec.ts (hunk 7 above)
Comment (mook-as) [reply src/main/diagnostics/__tests__/diagnostics.spec.ts:9]: In that case, it might have been better to use obviously-testing data, instead of copying production data.

Probably not making extra commits just for this, but please remember for similar situations in the future.

File: src/main/diagnostics/diagnostics.ts (hunk 13 above)
Comment (mook-as) [reply src/main/diagnostics/diagnostics.ts]: Because the test calls `yaml.parse()` for your fake data :)

File: src/main/diagnostics/diagnostics.ts (hunk 14 above)
Comment (mook-as) [reply src/main/diagnostics/diagnostics.ts:39]: Note that the original YAML has a defined order (it's a sequence, not a mapping); however, when we read it we discard the ordering.

At a minimum, we should at least document that the order is undefined.

File: e2e/rdctl.e2e.spec.ts [hunk 24]
```diff
@@ -787,13 +790,74 @@ test.describe('Command server', () => {
...
+
+        test.describe('diagnostics', () => {
+          let categories: string[];
+
+          test('categories', async() => {
+            const { stdout, stderr } = await rdctl(['api', '/v0/diagnostic_categories']);
+
+            expect(stderr).toEqual('');
+            categories = JSON.parse(stdout);
+            expect(categories).toMatchObject(['Utilities', 'Networking']);
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:817]: Same as the other test — `toMatchObject` doesn't do order-insensitive list comparison.

(I'll skip mentioning the other instances of the same issue.)

File: e2e/rdctl.e2e.spec.ts [hunk 25]
```diff
@@ -787,13 +790,74 @@ test.describe('Command server', () => {
...
+          });
+          test('it finds the IDs for Utilities', async() => {
+            const { stdout, stderr } = await rdctl(['api', '/v0/diagnostic_ids?category=Utilities']);
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:820]: Looking at the actual API call, I suspect we should have category IDs instead of using the label directly. We can deal with that later, though, I think — we're not guaranteeing API compatibility yet.

File: e2e/rdctl.e2e.spec.ts [hunk 26]
```diff
@@ -787,13 +790,74 @@ test.describe('Command server', () => {
...
             'PUT /v0/shutdown',
           ]);
         });
+        test('/v1 should fail', async() => {
+          const { stdout, stderr } = await rdctl(['api', '/v1']);
+
+          expect({ stdout: JSON.parse(stdout), stderr: stderr.trim() }).toMatchObject({ stdout: { message: '404 Not Found' }, stderr: 'Unknown command: GET /v1' });
+        });
+
+        test.describe('diagnostics', () => {
```
Comment (mook-as) [inline e2e/rdctl.e2e.spec.ts:809]: Why is this grouped under `getting endpoints`?

File: background.ts [hunk 27]
```diff
@@ -846,6 +848,24 @@ class BackgroundCommandWorker implements CommandWorkerInterface {
     return jsonStringifyWithWhiteSpace(cfg);
   }
 
+  getDiagnosticCategories(): string|undefined {
+    const categories = diagnostics.getCategoryNames();
+
+    return categories && JSON.stringify(categories);
```
Comment (mook-as) [inline background.ts:854]: This shouldn't return a string; it should return the raw object, and have the HTTP layer convert it to JSON instead.  As it is, the API doesn't make much sense (and this is why we had the `text/plain` vs `application/json` confusion).

This also applies to the other new methods.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/assets/diagnostics.yaml (hunk 16 above)
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/diagnostics.yaml]: done

File: src/assets/diagnostics.yaml (hunk 17 above)
[the remark this answers is not in the document]
Comment (ericpromislow) [reply src/assets/diagnostics.yaml]: Right, it's in the spec -- could be multiple ways to fix a problem

File: e2e/rdctl.e2e.spec.ts (hunk 24 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:817]: Right, I forgot about these tests.

File: e2e/rdctl.e2e.spec.ts (hunk 25 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:820]: I figured the labels can act as IDs for now, until we localize them.

File: e2e/rdctl.e2e.spec.ts (hunk 26 above)
Comment (ericpromislow) [reply e2e/rdctl.e2e.spec.ts:809]: I meant to put it under API and inserted it at the wrong level

File: background.ts (hunk 27 above)
Comment (ericpromislow) [reply background.ts]: done, although this is the opposite of what the preferences/settings methods are doing

File: src/main/diagnostics/diagnostics.ts [hunk 28]
```diff
@@ -0,0 +1,66 @@
...
+  constructor(diagnosticsTable: DiagnosticsType|undefined = undefined) {
+    this.diagnostics = diagnosticsTable || DIAGNOSTICS_TABLE.diagnostics;
+    for (const category of this.diagnostics.categories) {
+      for (const check of category.checks) {
+        if (!('mute' in check)) {
+          check.mute = false;
+        }
+        if (!('fixes' in check)) {
+          check.fixes = [];
+        }
```
Comment (mook-as) [inline src/main/diagnostics/diagnostics.ts:37]:
```suggestion
        check.mute ??= false;
        check.fixes ??= [];
```

File: background.ts [hunk 29]
```diff
@@ -18,6 +18,8 @@ import { getPathManagerFor, PathManagementStrategy, PathManager } from '@/integr
 import { CommandWorkerInterface, HttpCommandServer } from '@/main/commandServer/httpCommandServer';
 import SettingsValidator from '@/main/commandServer/settingsValidator';
 import { HttpCredentialHelperServer } from '@/main/credentialServer/httpCredentialHelperServer';
+import { Diagnostics } from '@/main/diagnostics/diagnostics';
+import type { DiagnosticsCheck } from '@/main/diagnostics/diagnostics';
```
Comment (mook-as) [inline background.ts:22]:
```suggestion
import { Diagnostics, DiagnosticsCheck } from '@/main/diagnostics/diagnostics';
```
Given that you're already pulling in the whole anyway, there's no reason to use `import type`.

**Review by mook-as — APPROVED** [review]
Just a couple trivial things

File: src/main/commandServer/httpCommandServer.ts (hunk 1 above)
Comment (ericpromislow) [reply src/main/commandServer/httpCommandServer.ts]: They look like the're in sync now -- the 200-returning flows for the diagnostics all return `'Content-Type': 'text/plain'`, and that's what command-api.yaml specifies. Other endpoints in the two files aren't in sync, but that should be a separate issue.

File: src/main/diagnostics/diagnostics.ts (hunk 28 above)
Comment (ericpromislow) [reply src/main/diagnostics/diagnostics.ts:37]: done

File: background.ts (hunk 29 above)
Comment (ericpromislow) [reply background.ts:22]: Could you explain what the difference is?

Comment (ericpromislow) [reply background.ts:22]: ok

**Review by mook-as — APPROVED** [review]
