### PR TITLE
Prevent non‑semver “unknown” app versions during local packaging

### LINKED ISSUE #9825: The locally compiled rancher desktop will crash upon launch after the first launch
### Actual Behavior

- The locally compiled rancher desktop will crash upon launch after the first launch.

### Steps to Reproduce

- Perform the following operations on a fresh installation of Ubuntu 24.04 WSL:
```bash
sudo apt update && sudo apt upgrade --assume-yes

sudo tee /etc/profile.d/myenvvars.sh <<'EOF'
export GALLIUM_DRIVER="d3d12"
EOF

# In PowerShell 7, execute `wsl --terminate Ubuntu-24.04`
sudo usermod -a -G kvm "$USER"
sudo apt install --assume-yes pass libnspr4 libnss3 libasound2t64 build-essential zlib1g-dev unzip imagemagick libcairo2

tee /tmp/foo.txt <<EOF
Key-Type: DSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: Joe Tester
Name-Comment: with stupid passphrase
Name-Email: joe@foo.bar
Expire-Date: 0
Passphrase: abc
%commit
EOF

gpg --batch --generate-key /tmp/foo.txt
pass init $(gpg --list-secret-keys --with-colons "joe@foo.bar" | awk -F: '$1 == "fpr" {print $10; exit}')

sudo tee --append /etc/sysctl.conf <<EOF
net.ipv4.ip_unprivileged_port_start=80
EOF

sudo sysctl --load
echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
sudo apt update
sudo apt install --assume-yes vfox
echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
source ~/.bashrc
vfox add golang nodejs
vfox install golang@1.25.6 nodejs@22.22.0
vfox use --global golang@1.25.6
vfox use --global nodejs@22.22.0
npm uninstall -g yarn pnpm
npm install -g corepack

git clone --depth 1 -b main https://github.com/rancher-sandbox/rancher-desktop.git
cd ./rancher-desktop/
yarn install
yarn build
yarn package
./dist/linux-unpacked/rancher-desktop
```
- Then, I saw the GUI interface appear, and I clicked the `×` to close the GUI.
- Image
-  The second time `./dist/linux-unpacked/rancher-desktop` was executed, the GUI appeared briefly, and then rancher desktop crashed.
- Image

### Result

- I have already executed commands similar to the following. 
```bash
rdctl shutdown
./resources/linux/bin/rdctl shutdown
./dist/linux-unpacked/resources/resources/linux/bin/rdctl shutdown
pkill -f rancher-desktop
pkill -f "dist/linux-unpacked/rancher-desktop"
pkill -f "Rancher Desktop"
```
- Executing `rdctl shutdown` yields the following log.
```bash
Command 'rdctl' not found, did you mean:
  command 'ndctl' from deb ndctl (76-1ubuntu1)
  command 'grdctl' from deb gnome-remote-desktop (46.3-0ubuntu1.2)
  command 'wdctl' from deb util-linux (2.39.3-9ubuntu6.4)
Try: sudo apt install <deb name>
```
- Executing `./resources/linux/bin/rdctl shutdown` or `./dist/linux-unpacked/resources/resources/linux/bin/rdctl shutdown` will produce the following log: `ERRO[0000] Ignoring error trying to get lima directory: can't find the lima-home directory at "/home/lingh/.local/share/rancher-desktop/lima": stat /home/lingh/.local/share/rancher-desktop/lima: no such file or directory`.
- Executing `pkill -f rancher-desktop`, `pkill -f "dist/linux-unpacked/rancher-desktop"`, or `pkill -f "Rancher Desktop"` yields no logs.
- However, when I execute `./dist/linux-unpacked/rancher-desktop`, the GUI appears briefly, and then the rancher desktop still crashes.
```bash
[12070:0131/180805.723119:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.freedesktop.systemd1.Manager.StartTransientUnit: object_path= /org/freedesktop/systemd1: org.freedesktop.systemd1.UnitExists: Unit app-org.chromium.Chromium-12070.scope was already loaded or has a fragment file.
[12070:0131/180805.919499:ERROR:ui/gfx/x/connection.cc:763] Cannot send request of length 18215856
```
- So I tried some other commands to capture the logs.
```bash
./dist/linux-unpacked/resources/resources/linux/bin/rdctl start --path ./dist/linux-unpacked/rancher-desktop --no-modal-dialogs
ls -la ~/.local/share/rancher-desktop/logs
tail -n 200 ~/.local/share/rancher-desktop/logs/* 2>/dev/null
ps -ef | grep -iE "(rancher-desktop|rancher desktop)" | grep -v grep
```
- The logs from `./dist/linux-unpacked/resources/resources/linux/bin/rdctl start --path ./dist/linux-unpacked/rancher-desktop --no-modal-dialogs` are as follows:
```bash
[12222:0131/181124.123077:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.freedesktop.systemd1.Manager.StartTransientUnit: object_path= /org/freedesktop/systemd1: org.freedesktop.systemd1.UnitExists: Unit app-org.chromium.Chromium-12222.scope was already loaded or has a fragment file.
Dropped Escape call with ulEscapeCode : 0x03007703
[12222:0131/181124.311828:ERROR:ui/gfx/x/connection.cc:763] Cannot send request of length 18215856
```
- The logs from `ls -la ~/.local/share/rancher-desktop/logs` are as follows:
```bash
total 44
drwxr-xr-x 2 lingh lingh 4096 Jan 31 17:57 .
drwxr-xr-x 4 lingh lingh 4096 Jan 31 17:58 ..
-rw------- 1 lingh lingh 4178 Jan 31 18:11 background.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 commandLine.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 dashboardServer.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 deploymentProfile.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 diagnostics.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 images.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 integrations.log
-rw------- 1 lingh lingh   81 Jan 31 18:11 k8s.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 kube.log
-rw------- 1 lingh lingh  929 Jan 31 18:11 lima.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 moby.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 mock.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 nerdctl.log
-rw------- 1 lingh lingh  105 Jan 31 18:11 networking.log
-rw------- 1 lingh lingh  128 Jan 31 18:11 path-management.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 protocol-handler.log
-rw------- 1 lingh lingh  110 Jan 31 18:11 server.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 settings.log
-rw------- 1 lingh lingh 1656 Jan 31 18:11 shortcuts.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 snapshots.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 steve.log
-rw------- 1 lingh lingh   86 Jan 31 18:11 update.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 window_browser.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 wsl-version.log
-rw------- 1 lingh lingh    0 Jan 31 18:11 wsl.log
```
- The logs from `tail -n 200 ~/.local/share/rancher-desktop/logs/* 2>/dev/null` are as follows:
```bash
==> /home/lingh/.local/share/rancher-desktop/logs/background.log <==
2026-01-31T10:11:24.344Z: UnhandledRejectionWarning: Error: ENOENT: no such file or directory, watch '/home/lingh/.kube/config'
    at FSWatcher.<computed> (node:internal/fs/watchers:254:19)
    at Object.watch (node:fs:2539:36)
    at file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:41:94938
    at Array.map (<anonymous>)
    at yi.watchForChanges (file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:41:94926) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/home/lingh/.kube/config',
  filename: '/home/lingh/.kube/config'
}
2026-01-31T10:11:24.382Z: mainEvents settings-update: {"version":17,"application":{"adminAccess":false,"debug":false,"extensions":{"allowed":{"enabled":false,"list":[]},"installed":{}},"pathManagementStrategy":"rcfiles","telemetry":{"enabled":true},"updater":{"enabled":false},"autoStart":false,"startInBackground":false,"hideNotificationIcon":false,"window":{"quitOnClose":false}},"containerEngine":{"allowedImages":{"enabled":false,"patterns":[]},"mobyStorageDriver":"auto","name":"moby"},"virtualMachine":{"memoryInGB":5,"numberCPUs":2,"type":"qemu","useRosetta":false,"mount":{"type":"reverse-sshfs"}},"WSL":{"integrations":{}},"kubernetes":{"version":"1.34.3","port":6443,"enabled":true,"options":{"traefik":true,"flannel":true},"ingress":{"localhostOnly":false}},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"default"},"containers":{"showAll":true,"namespace":"default"},"diagnostics":{"showMuted":false,"mutedChecks":{},"connectivity":{"interval":5000,"timeout":5000}},"experimental":{"containerEngine":{"webAssembly":{"enabled":false}},"kubernetes":{"options":{"spinkube":false}},"virtualMachine":{"diskSize":"100GiB","mount":{"9p":{"securityModel":"none","protocolVersion":"9p2000.L","msizeInKib":128,"cacheMode":"mmap"}},"proxy":{"enabled":false,"address":"","password":"","port":3128,"username":"","noproxy":["0.0.0.0/8","10.0.0.0/8","127.0.0.0/8","169.254.0.0/16","172.16.0.0/12","192.168.0.0/16","224.0.0.0/4","240.0.0.0/4"]},"sshPortForwarder":true}}}
2026-01-31T10:11:24.394Z: Error starting up: Error: App version is not a valid semver version: "unknown" Error: App version is not a valid semver version: "unknown"
    at newError (/home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/node_modules/builder-util-runtime/out/error.js:5:19)
    at new AppUpdater (/home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:215:55)
    at new BaseUpdater (/home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:8:9)
    at new AppImageUpdater (/home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:15:9)
    at file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:41:130586
    at async file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:41:130020
    at async file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:41:129893
2026-01-31T10:11:24.445Z: UnhandledRejectionWarning: l [Error]: /home/lingh/rancher-desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:2:68266)
    at ChildProcess.emit (node:events:508:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  command: [
    '/home/lingh/rancher-desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl',
    'stop',
    '--force',
    '0'
  ],
  stdout: '',
  stderr: 'time="2026-01-31T18:11:24+08:00" level=fatal msg="open /home/lingh/.local/share/rancher-desktop/lima/0/lima.yaml: no such file or directory"\n',
  code: 1,
  signal: undefined,
  Symbol(child-process.command): '/home/lingh/rancher-desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl stop --force 0'
}

==> /home/lingh/.local/share/rancher-desktop/logs/commandLine.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/dashboardServer.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/deploymentProfile.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/diagnostics.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/images.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/integrations.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/k8s.log <==
2026-01-31T10:11:24.173Z: Updating release version cache with 131 items in cache

==> /home/lingh/.local/share/rancher-desktop/logs/kube.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/lima.log <==
2026-01-31T10:11:24.444Z: > limactl stop --force 0
$ l [Error]: /home/lingh/rancher-desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (file:///home/lingh/rancher-desktop/dist/linux-unpacked/resources/app.asar/dist/app/background.js:2:68266)
    at ChildProcess.emit (node:events:508:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  command: [
    '/home/lingh/rancher-desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl',
    'stop',
    '--force',
    '0'
  ],
  stdout: '',
  stderr: 'time="2026-01-31T18:11:24+08:00" level=fatal msg="open /home/lingh/.local/share/rancher-desktop/lima/0/lima.yaml: no such file or directory"\n',
  code: 1,
  signal: undefined,
  Symbol(child-process.command): '/home/lingh/rancher-desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl stop --force 0'
}

==> /home/lingh/.local/share/rancher-desktop/logs/moby.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/mock.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/nerdctl.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/networking.log <==
2026-01-31T10:11:24.161Z: Error listing system certificate tokens, ignoring: Error: spawn p11tool ENOENT

==> /home/lingh/.local/share/rancher-desktop/logs/path-management.log <==
2026-01-31T10:11:24.409Z: Error: EEXIST: file already exists, copyfile '/home/lingh/.profile' -> '/home/lingh/.profile.rd-temp'

==> /home/lingh/.local/share/rancher-desktop/logs/protocol-handler.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/server.log <==
2026-01-31T10:11:24.171Z: CLI server is now ready.
2026-01-31T10:11:24.178Z: Credentials server is now ready.

==> /home/lingh/.local/share/rancher-desktop/logs/settings.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/shortcuts.log <==
2026-01-31T10:11:24.342Z: register: window [1] - [open preferences]
2026-01-31T10:11:24.342Z: add: window [1] - key [Ctrl+,]
2026-01-31T10:11:24.342Z: register: window [1] - [switch main tabs /General]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+1]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Containers]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+2]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Volumes]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+3]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /PortForwarding]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+4]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Images]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+5]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Snapshots]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+6]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Troubleshooting]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+7]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Diagnostics]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+8]
2026-01-31T10:11:24.343Z: register: window [1] - [switch main tabs /Extensions]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+9]
2026-01-31T10:11:24.343Z: register: window [1] - [switch preferences tabs by cycle [forward]]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+]]
2026-01-31T10:11:24.343Z: register: window [1] - [switch preferences tabs by cycle [back]]
2026-01-31T10:11:24.343Z: add: window [1] - key [Ctrl+[]

==> /home/lingh/.local/share/rancher-desktop/logs/snapshots.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/steve.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/update.log <==
2026-01-31T10:11:24.394Z: Error: App version is not a valid semver version: "unknown"

==> /home/lingh/.local/share/rancher-desktop/logs/window_browser.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/wsl-version.log <==

==> /home/lingh/.local/share/rancher-desktop/logs/wsl.log <==
```
- `ps -ef | grep -iE "(rancher-desktop|rancher desktop)" | grep -v grep` outputs no logs.

### Expected Behavior

- The locally compiled Rancher desktop does not experience GUI crashes upon initial launch or subsequent launches.

### Additional Information

- The logs for `yarn package` are as follows. Note that `fatal: No names found, cannot describe anything.`.
```bash
/home/lingh/.vfox/cache/nodejs/v-22.22.0/nodejs-22.22.0/bin/node node_modules/tsx/dist/cli.mjs --trace-warnings --trace-deprecation --max_old_space_size=4096 --stack-size=16384 scripts/package.ts
  • Packaging...
fatal: No names found, cannot describe anything.
  • electron-builder  version=26.4.0 os=6.6.87.2-microsoft-standard-WSL2
  • description is missed in the package.json  appPackageFile=/home/lingh/rancher-desktop/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=40.0.0 arch=x64 buildFromSource=false workspaceRoot=/home/lingh/rancher-desktop projectDir=./ appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=native-reg arch=x64
  • finished        moduleName=native-reg arch=x64
  • completed installing native dependencies
  • packaging       platform=linux arch=x64 electron=40.0.0 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v40.0.0/electron-v40.0.0-linux-x64.zip size=115 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v40.0.0/electron-v40.0.0-linux-x64.zip duration=6.737s
  • cannot find path for dependency  name=undefined reference=undefined
  • building        target=zip arch=x64 file=dist/rancher-desktop-unknown-linux.zip
```
- The log for the first execution of `./dist/linux-unpacked/rancher-desktop` is as follows:
```bash
Dropped Escape call with ulEscapeCode : 0x03007703
[11420:0131/175800.493137:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.freedesktop.systemd1.Manager.StartTransientUnit: object_path= /org/freedesktop/systemd1: org.freedesktop.systemd1.UnitExists: Unit app-org.chromium.Chromium-11420.scope was already loaded or has a fragment file.
Dropped Escape call with ulEscapeCode : 0x03007703
[11420:0131/175846.900319:ERROR:ui/gfx/x/connection.cc:763] Cannot send request of length 18215856
```
- The log for the second execution of `./dist/linux-unpacked/rancher-desktop` is as follows:
```bash
[11618:0131/175906.848306:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.freedesktop.systemd1.Manager.StartTransientUnit: object_path= /org/freedesktop/systemd1: org.freedesktop.systemd1.UnitExists: Unit app-org.chromium.Chromium-11618.scope was already loaded or has a fragment file.
Dropped Escape call with ulEscapeCode : 0x03007703
[11618:0131/175907.033155:ERROR:ui/gfx/x/connection.cc:763] Cannot send request of length 18215856
```
- Restarting the current WSL distribution will not resolve this bug. I must reset the current WSL distribution.

### Rancher Desktop Version

https://github.com/rancher-sandbox/rancher-desktop/commit/ee1134f45de63965b9970ae0d3deb9c961c09d86

### Rancher Desktop K8s Version

No Kubernetes version selected.

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 24.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

- Null.

### PR DESCRIPTION
**Pull request by linghengqian**
- Fixes #9825 .
- Prevent non‑semver “unknown” app versions during local packaging. 
- Local packaging on repos without tags should preserve the existing `git describe` flow and only fall back to `package.json` version when that call fails. This avoids injecting non‑semver versions while keeping the original intent intact. Without this change, `yarn package` would return `dist/rancher-desktop-unknown-linux.zip` instead of `dist/rancher-desktop-1.22.0-fallback-linux.zip`. This prevents access to the main interface of `./dist/linux-unpacked/rancher-desktop`.
- It's hard to say what kind of unit tests are easy to write here, so the actual verification process is as follows:
```bash
sudo apt update && sudo apt upgrade --assume-yes

sudo tee /etc/profile.d/myenvvars.sh <<'EOF'
export GALLIUM_DRIVER="d3d12"
EOF

# In PowerShell 7, execute `wsl --terminate Ubuntu-24.04`
sudo usermod -a -G kvm "$USER"
sudo apt install --assume-yes pass libnspr4 libnss3 libasound2t64 build-essential zlib1g-dev unzip imagemagick libcairo2

tee /tmp/foo.txt <<EOF
Key-Type: DSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: Joe Tester
Name-Comment: with stupid passphrase
Name-Email: joe@foo.bar
Expire-Date: 0
Passphrase: abc
%commit
EOF

gpg --batch --generate-key /tmp/foo.txt
pass init $(gpg --list-secret-keys --with-colons "joe@foo.bar" | awk -F: '$1 == "fpr" {print $10; exit}')

sudo tee --append /etc/sysctl.conf <<EOF
net.ipv4.ip_unprivileged_port_start=80
EOF

sudo sysctl --load
echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
sudo apt update
sudo apt install --assume-yes vfox
echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
source ~/.bashrc
vfox add golang nodejs
vfox install golang@1.25.6 nodejs@22.22.0
vfox use --global golang@1.25.6
vfox use --global nodejs@22.22.0
npm uninstall -g yarn pnpm
npm install -g corepack

git clone --depth 1 -b fix-package https://github.com/linghengqian/rancher-desktop.git
cd ./rancher-desktop/
corepack install
yarn install
yarn build
yarn package
./dist/linux-unpacked/rancher-desktop
./dist/linux-unpacked/rancher-desktop
```
- image

### CODE REVIEW

File: scripts/package.ts [hunk 1]
```diff
@@ -151,13 +154,18 @@ class Builder {
...
     try {
       fullBuildVersion = childProcess.execFileSync('git', ['describe', '--tags']).toString().trim();
     } catch {
-      fullBuildVersion = 'unknown';
+      fullBuildVersion = fallbackVersion;
+    }
+    let finalBuildVersion = fullBuildVersion.replace(/^v/, '');
+    if (!semver.valid(finalBuildVersion)) {
+      console.warn(`Invalid build version ${ finalBuildVersion }; falling back to ${ fallbackVersion }`);
+      finalBuildVersion = semver.valid(fallbackVersion) ? fallbackVersion : Builder.DEFAULT_VERSION;
```
Comment (mook-as) [inline scripts/package.ts]: This is more complicated than it needs to be, largely because  `semver.valid()` returns the parsed string:
```suggestion
      fullBuildVersion = semver.valid(childProcess.execFileSync('git', ['describe', '--tags']).toString());
    } catch {
      fullBuildVersion = semver.valid(fallbackVersion) ?? Builder.DEFAULT_VERSION;
    }
```

File: scripts/package.ts [hunk 2]
```diff
@@ -151,13 +154,18 @@ class Builder {
     // Build the electron builder configuration to include the version data
     const config: ReadWrite<Configuration> = yaml.parse(await fs.promises.readFile('packaging/electron-builder.yml', 'utf-8'));
     const configPath = path.join(buildUtils.distDir, 'electron-builder.yaml');
+    const fallbackVersion = buildUtils.packageMeta.version ?? Builder.DEFAULT_VERSION;
```
Comment (mook-as) [inline scripts/package.ts:157]: I think it would be good to add `-fallback` to the version string, so that we know that something went wrong (and don't accidentally think we're running the release build).

**Review by mook-as — CHANGES_REQUESTED** [review]
It makes sense to make up a version string if we can't get a version, largely because things fail to work otherwise, as long as the version still looks reasonable.  But we should make sure that still ends up marked as not an actual release, so we don't get confuse running tests if we run a development build (and think we're running the release build).

File: scripts/package.ts (hunk 2 above)
Comment (linghengqian) [reply scripts/package.ts:157]: I've changed the logic, and now I'll get `dist/rancher-desktop-1.22.0-fallback-linux.zip`.
image

File: scripts/package.ts (hunk 1 above)
Comment (linghengqian) [reply scripts/package.ts]: Do you mean that `const finalBuildVersion = fullBuildVersion.replace(/^v/, '');` doesn't need to be retained?

Comment (mook-as) [reply scripts/package.ts]: `semver.valid` / `semver.parse` strips the `v`, so if we only display semver-valid strings it's unneeded.
