### PR TITLE
fix image allow list alert reactivity

### LINKED ISSUE #3534: Message of Image Allow list should disappear if Image Allow List is disabled
### Problem Description

 The message `The image name needs to match one of the patterns defined in the Allowed Images preference tab.` is always displayed in the Images tab, even when Image Allow List is disabled.

### Proposed Solution

Message of Image Allow list should disappear if Image Allow List is disabled, as user can pull any image.

### Additional Information

Screen Shot 2022-12-02 at 5 38 18 PM

### PR DESCRIPTION
**Pull request by torchiaf**
Fixes #3534

Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### CODE REVIEW

File: pkg/rancher-desktop/pages/images/add.vue [hunk 1]
```diff
@@ -55,6 +55,7 @@ export default {
       imageToPull:                      '',
       imageOutputCuller:                null,
       showOutput:                       false,
+      allowedImagesEnabled:             null,
```
Comment (ericpromislow) [inline pkg/rancher-desktop/pages/images/add.vue:58]: This should be initialized to `false` because it comes from a boolean value. I don't think we need to later distinguish an unset value from `false` (although if we do, there should be a comment explaining why this needs to be tri-state (`true`, `false`, or `null`).

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Can we simplify the way the `imageAllowList` pref is calculated?

File: pkg/rancher-desktop/pages/images/add.vue (hunk 1 above)
Comment (torchiaf) [reply pkg/rancher-desktop/pages/images/add.vue:58]: `allowedImagesEnabled: null` is used in combination with `settings-update` messages to determine if the allowList is enabled:
```
const enabled = this.allowedImagesEnabled ?? this.preferences.containerEngine.imageAllowList.enabled;
```
- When the component is rendered, enabled variable is equal to `this.preferences.containerEngine.imageAllowList.enabled`
- When the settings are updated by the user, the `allowedImagesEnabled` is used because it will be always `true` or `false`

So, I am using the store to get the first value and the `settings-update` events to update the variable when the preferences changes.
Agree with you, even if we already have the first value in memory, this could be a bit confusing by code perspective, so using `once('settings-read')` to determine the first value would work fine.

File: pkg/rancher-desktop/pages/images/add.vue [hunk 2]
```diff
@@ -124,6 +121,9 @@ export default {
     toggleOutput(val) {
       this.showOutput = val;
     },
+    enableAllowedImages(settings) {
```
Comment (ericpromislow) [inline pkg/rancher-desktop/pages/images/add.vue:124]: Please rename to `updateAllowedImagesSetting`
