### PR TITLE
Windows: fix factory reset

### LINKED ISSUE #1061: Make Factory Reset actually clear all files on Windows
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

any

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Home

### What CPU architecture are you using?

x64

### Windows User Only

n/a

### Actual Behavior

Factory Reset doesn't clear the cached files (or many other files for that matter).

### Steps to Reproduce

Click `Troubleshooting | Factory Reset`

### Result

It's not clear if the UI even relaunches. Probably there are some uncaught errors trying to delete cache files, and while the Kubernetes instance is deleted, we're in worse shape.

### Expected Behavior

All files should be deleted and the UI should relaunch.

### Additional Information

Probably the best way to do this is to have `factoryReset` delete the instance, and launch a separate process, and then shut down. This process (which could be another electron applet so we actually have some UI) then monitors the original Rancher Desktop process to make sure it's gone, then deletes as many of the internal files as it can, and finally launches a new instance of Rancher Desktop and shuts itself down.

### LINKED ISSUE #1075: Factory Reset doesn't work on Windows
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

N/A

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 21H1

### What CPU architecture are you using?

x64

### Windows User Only

Running in a clean VM.

### Actual Behavior

Attempting to do a factory reset doesn't appear to do anything.

### Steps to Reproduce

1. Start Rancher Desktop
2. Go to the Troubleshooting tab
3. Click Factory Reset
4. Confirm when it asks about losing data

### Result

Nothing appears to happen

### Expected Behavior

1. Data is deleted
2. Rancher Desktop restarts

### Additional Information

From `background.log`:
```
2021-12-06T22:00:15.559Z: UnhandledRejectionWarning: [Error: EBUSY: resource busy or locked, unlink 'C:\Users\User\AppData\Roaming\rancher-desktop\Cookies'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\User\\AppData\\Roaming\\rancher-desktop\\Cookies'
}
```

### PR DESCRIPTION
**Pull request by mook-as**
This changes factory reset on Windows to use wsl-helper as a secondary executable, so we don't have to worry about deleting files that are in use.

Fixes #1075; fixes #1061.

### CODE REVIEW

**Comment by ericpromislow** [comment]
Ran  `Factory Reset` and a vanilla electron screen came up

**Comment by ericpromislow** [comment]
Note that at least the app isn't still running according to the task bar tray

File: src/go/wsl-helper/pkg/reset/factory_reset_windows.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+		uintptr(unsafe.Pointer(&result)),
+	)
+	// SHGetKnownFolderPath documentation says we _must_ free the result with
+	// CoTaskMemFree, even if the call failed.
+	defer CoTaskMemFree.Call(result)
+	if hr != 0 {
+		return "", windows.Errno(hr)
+	}
+
+	// result at this point containers the path, as a PWSTR
```
Comment (ericpromislow) [inline src/go/wsl-helper/pkg/reset/factory_reset_windows.go:91]: typo: should be "contains"?

File: src/go/wsl-helper/pkg/reset/factory_reset_windows.go [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+	SHGetKnownFolderPath, err := shell32Dll.FindProc("SHGetKnownFolderPath")
+	if err != nil {
+		return "", fmt.Errorf("could not find SHGetKnownFolderPath: %w", err)
+	}
+	CoTaskMemFree, err := ole32Dll.FindProc("CoTaskMemFree")
+	if err != nil {
+		return "", fmt.Errorf("could not find CoTaskMemFree: %w", err)
+	}
+	var result uintptr
+	hr, _, _ := SHGetKnownFolderPath.Call(
```
Comment (ericpromislow) [inline src/go/wsl-helper/pkg/reset/factory_reset_windows.go:78]: No longer a fan of Hungarian notation -- it was invented 35 years ago for working with assembly -- but `hr` is probably as good a name as `status` for anyone familiar with the Win32 API

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Now I'm down to a single typo. Everything works fine with a packaged build. It clears the app for `npm  run dev` but restarting the app that way is way out of scope.

File: src/go/wsl-helper/pkg/reset/factory_reset_windows.go (hunk 2 above)
Comment (mook-as) [reply src/go/wsl-helper/pkg/reset/factory_reset_windows.go:78]: Yeah, I'm only using `hr` here because at this point this is an idiom, much like `rv = x(); NS_ENSURE_SUCCESS(rv, rv);` is in Mozilla-land.
