### PR TITLE
Wait for the container service.

### LINKED ISSUE #1656: Windows fails to start k3s because docker isn't ready
Timing problem - wait for `docker` (or `containerd`) to be ready before starting k3s.

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 10

### What CPU architecture are you using?

x64

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #1656 

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

File: src/k8s-engine/wsl.ts [hunk 1]
```diff
@@ -1104,6 +1104,33 @@ export default class WSLBackend extends events.EventEmitter implements K8s.Kuber
...
+
+    while (true) {
+      const currentTime = Date.now();
+
+      if ((currentTime - startTime) > maxWaitTime) {
+        console.log(`Waited more than ${ maxWaitTime / 1000 } secs for ${ command.join(' ') } to succeed. Giving up.`);
+        break;
+      }
+      try {
+        await this.execCommand(...command);
```
Comment (mook-as) [inline src/k8s-engine/wsl.ts:1125]:
```suggestion
        await this.execCommand({ expectFailure: true }, ...command);
```
This prevents us from logging the failure (because it's expected); it'll still throw, though.

File: src/k8s-engine/wsl.ts [hunk 2]
```diff
@@ -1104,6 +1104,33 @@ export default class WSLBackend extends events.EventEmitter implements K8s.Kuber
...
+        break;
+      } catch (err) {
+        console.log(`Command ${ command } failed: ${ err }:`, err);
```
Comment (mook-as) [inline src/k8s-engine/wsl.ts:1128]: You're including `err` twice; we probably don't need the second instance (where the stack would show).  Maybe including a message about retrying.

Do we need `console.log` here, or `console.debug`?

File: src/k8s-engine/wsl.ts (hunk 1 above)
Comment (mook-as) [reply src/k8s-engine/wsl.ts:1125]: We're logging the command output here; would that be excessive?

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/k8s-engine/wsl.ts [hunk 3]
```diff
@@ -1104,6 +1104,33 @@ export default class WSLBackend extends events.EventEmitter implements K8s.Kuber
...
+      }
+      await util.promisify(setTimeout)(waitTime);
```
Comment (jandubois) [inline src/k8s-engine/wsl.ts:1130]: Is this essentially just sleeping for 0.2s? If yes, then I think I would increase the sleep to 1s instead.

Comment (ericpromislow) [reply src/k8s-engine/wsl.ts:1130]: Once I got this working correctly it only needed one retry to succeed for both engines. How about if we do some exponential backoff then, maxing out at 1 sec, because it doesn't seem to need much time to be ready?

File: src/k8s-engine/wsl.ts (hunk 2 above)
Comment (ericpromislow) [reply src/k8s-engine/wsl.ts:1128]: Good point, should be `console.log`

File: src/k8s-engine/wsl.ts (hunk 3 above)
Comment (jandubois) [reply src/k8s-engine/wsl.ts:1130]: Too complicated. It takes over a minute to start up the VM, so adding 0.8s doesn't make much of a difference. Maybe change it to 0.5s, or leave it as-is, but don't change the logic itself.

Comment (ericpromislow) [reply src/k8s-engine/wsl.ts:1130]: Waiting for 1/2 second now.

File: src/k8s-engine/wsl.ts (hunk 1 above)
Comment (ericpromislow) [reply src/k8s-engine/wsl.ts]: I wasn't seeing any output from this command when it failed, just the exception, but it doesn't matter -- it's normally a transient condition.

**Review by mook-as — APPROVED** [review]
