### PR TITLE
Throw an error when running on the wrong architecture

### LINKED ISSUE #831: Show an error dialog when running on x86_64 version on aarch64 or vice versa
It's always sad to see something like this.

@jandubois I suggest adding a check in the installer or somewhere in the application startup process if this is architecture isn't supported to not waste time grinding Github issues. 
Even mentioning this thing in the release text will impact future users i.e.

> This is a feature release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac(**only** amd64), Windows, and Linux. The release contains some feature changes along with various bug fixes.

_Originally posted by @painhardcore in https://github.com/rancher-sandbox/rancher-desktop/issues/16#issuecomment-947086062_

### LINKED ISSUE #955: Show explainer dialog before asking for sudo password
With #883 we now get a password prompt during startup with the sole explanation: "Rancher Desktop wants to make changes".

I normally decline sudo prompts when I don't expect them, and the application doesn't explain to me why it needs it. That is simply sound security practice.

It looks like there is no mechanism to add more text to the dialog. One pattern I've seen in other apps is that they display a heads-up dialog first: "Rancher Desktop needs your admin password so it can configure network settings. Click OK to get the password prompt!  [OK]" or something like that (will try to take screen shots when I see them again).

Rancher Desktop should add such a dialog to make it more likely that users will understand why RD needs to run an operation as admin and allow it. If they don't allow it, Lima will simply not be working; this is not an optional consent.

### PR DESCRIPTION
**Pull request by jandubois**
Fixes #831

### CODE REVIEW

**Comment by jandubois** [comment]
Currently  shows a dialog like this:

Screen Shot 2021-11-24 at 2 39 30 PM

Things I would like to see improved:

* Get rid of the "unknown error" part of the message; why do we have that?
* Exit the application instead of continuing; does it ever make sense to continue the app when a pre-flight error has occurred?

File: src/k8s-engine/lima.ts [hunk 1]
```diff
@@ -241,6 +237,21 @@ export default class LimaBackend extends events.EventEmitter implements K8s.Kube
...
+    if (os.platform().startsWith('darwin')) {
+      const fileArch = this.arch === 'aarch64' ? 'arm64' : this.arch;
+      const { stdout } = await childProcess.spawnFile(
+        'file', [this.limactl],
+        { stdio: ['inherit', 'pipe', console] });
+
+      if (!stdout.trim().match(`executable ${ fileArch }$`)) {
+        const otherArch = { aarch64: 'x86_64', x86_64: 'aarch64' }[this.arch];
+
+        throw new Error(`Rancher Desktop for ${ otherArch } does not work on ${ this.arch }.`);
```
Comment (mook-as) [inline src/k8s-engine/lima.ts:250]: Please throw a [`KubernetesError`](https://github.com/rancher-sandbox/rancher-desktop/blob/abdb26fee17fb92327d19dab9200e751fdea0cc1/src/k8s-engine/k8s.ts#L19); we have [special handling](https://github.com/rancher-sandbox/rancher-desktop/blob/abdb26fee17fb92327d19dab9200e751fdea0cc1/background.ts#L591) to drop the `unknown error` part of the message (because it's known).

Even better, delete `LimaSudoRejectionError` and make a flag on `KuberentesError` to control quitting the app.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: src/k8s-engine/lima.ts [hunk 2]
```diff
@@ -241,6 +237,21 @@ export default class LimaBackend extends events.EventEmitter implements K8s.Kube
...
+    if (os.platform().startsWith('darwin')) {
+      const fileArch = this.arch === 'aarch64' ? 'arm64' : this.arch;
+      const { stdout } = await childProcess.spawnFile(
+        'file', [this.limactl],
+        { stdio: ['inherit', 'pipe', console] });
+
+      if (!stdout.trim().match(`executable ${ fileArch }$`)) {
+        const otherArch = { aarch64: 'x86_64', x86_64: 'aarch64' }[this.arch];
+
+        throw new K8s.KubernetesError('Fatal Error', `Rancher Desktop for ${ otherArch } does not work on ${ this.arch }.`, true);
```
Comment (mook-as) [inline src/k8s-engine/lima.ts:250]: It might be nice to say something like `Apple M1` instead; this depends on Apple's marketing…

File: src/k8s-engine/lima.ts [hunk 3]
```diff
@@ -241,6 +237,21 @@ export default class LimaBackend extends events.EventEmitter implements K8s.Kube
     return this.#desiredPort;
   }
 
+  protected async ensureArchitectureMatch() {
+    if (os.platform().startsWith('darwin')) {
+      const fileArch = this.arch === 'aarch64' ? 'arm64' : this.arch;
```
Comment (mook-as) [inline src/k8s-engine/lima.ts:242]: This is the _expected_ architecture, right? To me "fileArch" sounds more like "the architecture of the actual file, which might not be what we expect".

File: src/k8s-engine/lima.ts [hunk 4]
```diff
@@ -241,6 +237,21 @@ export default class LimaBackend extends events.EventEmitter implements K8s.Kube
...
+      const { stdout } = await childProcess.spawnFile(
+        'file', [this.limactl],
+        { stdio: ['inherit', 'pipe', console] });
+
+      if (!stdout.trim().match(`executable ${ fileArch }$`)) {
+        const otherArch = { aarch64: 'x86_64', x86_64: 'aarch64' }[this.arch];
```
Comment (mook-as) [inline src/k8s-engine/lima.ts:248]: Alternatively, `const otherArch = stdout.trim().split().pop();` (basically).

**Review by mook-as — CHANGES_REQUESTED** [review]
Basically good; just some comments around actual arch detection (maybe you can convince me to go with the code as-is…)

File: src/k8s-engine/lima.ts (hunk 3 above)
Comment (jandubois) [reply src/k8s-engine/lima.ts:242]: Yes, this is the architecture that we expect the `file` command to return. Curiously it returns `arm64` or `x86_64`.

Normally the names are either `amd64` and `arm64`, or `aarch64` and `x86_64`.

So not sure what to call it, `expectedFileArch`?

File: src/k8s-engine/lima.ts (hunk 4 above)
Comment (jandubois) [reply src/k8s-engine/lima.ts:248]: It should work (because it is the last word); normally I worry about `split` no doing the right thing when there are double spaces or whatever.

I kind of think the current version is fine as-is.

File: src/k8s-engine/lima.ts (hunk 2 above)
Comment (jandubois) [reply src/k8s-engine/lima.ts:250]: I wanted to use the same arch name we use in the filename, `Rancher Desktop.aarch64.dmg` and `Rancher Desktop.x86_64.dmg`, so users can map between the error message and the disk image file.

File: src/k8s-engine/lima.ts (hunk 4 above)
Comment (mook-as) [reply src/k8s-engine/lima.ts:248]: Yeah, I think it's fine as-is.

File: src/k8s-engine/lima.ts (hunk 2 above)
Comment (mook-as) [reply src/k8s-engine/lima.ts:250]: Ah; given _that_ this should be okay. (Maybe add a comment about it if you feel like it.)

File: src/k8s-engine/lima.ts (hunk 3 above)
Comment (mook-as) [reply src/k8s-engine/lima.ts:242]: How about just `expectedArch`?

**Review by mook-as — APPROVED** [review]
